trustwallet/wallet-core

JNI/java/com/wallet/crypto/trustapp/proto/Binance.java, JNI/java/com/wallet/crypto/trustapp/proto/Bitcoin.java, JNI/java/com/wallet/crypto/trustapp/proto/Common.java, JNI/java/org/tron/protos/Protocol.java, js/package-lock.json, src/interface/TWBitcoinTransactionSigner.cpp, src/proto/Bitcoin.proto, swift/Sources/Bitcoin.pb.swift, swift/Tests/BitcoinTransactionSignerTests.swift
Fix #10, return transaction hash in signing output, since we don't expose non-witness encoding method
UT passed
it's a minor bugfix change
1. Add `transaction_hash` to `SigningOutput`
2. Compute and set transaction hash in `WBitcoinTransactionSigner`
3. Update `BitcoinTransactionSignerTests`
=> Return  transaction hash

tests/interface/TWHDWalletTests.cpp
TZ1 addresses are derived with edsig.
Run `.bootstrap.sh`.
Fix tests for Tezos.
- [ x ] Prefix PR title with `[WIP]` if necessary.
- [ x ] Add tests to cover changes as needed.
- [ x ] Update documentation as needed.
=> Use edsig instead of secp to derive Tezos keys

src/Zcash/TAddress.cpp, tests/CoinTests.cpp
Fix #134.  Zcash has two bytes prefix, we should check `buffer[1]`
./boostrap.sh
* Bug fix
=> Fix zcash t address validation

swift/Sources/Blockchains/Bitcoin.swift, swift/Tests/BitcoinTransactionSignerTests.swift
It looks like we are missing `public` scope in following type aliases:
* TWBitcoinSigningInput
* TWBitcoinSigningOutput
* TWBitcoinUnspentTransaction
* TWBitcoinTransactionPlan 
* TWBitcoinOutPoint
Check if following types should be visible outside TrustCore.
I've removed them also from `BitcoinTransactionSignerTests.swift` so test will failed without `public` in `Bitcoin.swift`
=> Change visibility scope of TWBitcoin* type aliases to public

JNI/cpp/NEOAddress.c, JNI/cpp/NEOAddress.h, JNI/java/wallet/core/jni/CoinType.java, JNI/java/wallet/core/jni/NEOAddress.java, include/TrustWalletCore/TWCoinType.h, include/TrustWalletCore/TWNEOAddress.h, src/Coin.cpp, src/PrivateKey.cpp, src/PublicKey.cpp, src/PublicKey.h, src/interface/TWCoinTypeConfiguration.cpp, src/interface/TWNEOAddress.cpp, swift/Sources/Blockchains/BlockchainFactory.swift, swift/Sources/Blockchains/NEO.swift, swift/Sources/CoinType.swift, swift/Sources/NEOAddress.swift, swift/Sources/TrustWalletCore.h, swift/TrustWalletCore.xcodeproj/project.pbxproj, tests/CoinTests.cpp
Part of integration #44. Coin type and related stuff were added.
Run unit tests.
A new `PublicKeyType` was added - `PublicKeyType::nist256p1`.
Need to define proper way to handle `PublicKeyType.type`, `PublicKeyType.isValid` based on `nist256p1Size`.
=> NEO coin type and related stuff

src/Tezos/Forging.cpp, src/Tezos/Forging.h, tests/Tezos/ForgingTests.cpp
This PR fixes a bug where zariths could not be bigger than 16 bits.
Added a test to prove that code is now correct for large values.
Run bootstrap.sh to run tests. 
* Bug fix (non-breaking change which fixes an issue) 
- [ X] Prefix PR title with `[WIP]` if necessary.
- [X ] Add tests to cover changes as needed.
- [ X] Update documentation as needed.
=> Fix overflow in Zarith forging

include/TrustWalletCore/TWCoinType.h, include/TrustWalletCore/TWGroestlcoinAddress.h, include/TrustWalletCore/TWHRP.h, include/TrustWalletCore/TWP2PKHPrefix.h, include/TrustWalletCore/TWP2SHPrefix.h, src/Bitcoin/Script.cpp, src/Coin.cpp, src/Groestlcoin/Address.cpp, src/Groestlcoin/Address.h, src/interface/TWCoinTypeConfiguration.cpp, src/interface/TWGroestlcoinAddress.cpp, src/interface/TWHRP.cpp, tests/CoinTests.cpp, tests/Groestlcoin/AddressTests.cpp, tests/interface/TWCoinTypeConfigTests.cpp, tests/interface/TWGroestlcoinTests.cpp, tests/interface/TWHRPTests.cpp
Groestlcoin differences comparing to Bitcoin from a wallet point of view:
1. Base58check uses Groestl hash for checksum in addresses, WIF and xpub.
2. Transaction signing uses single round of SHA256 instead of double.
This PR adds support for custom hashers in base58check, adds `secp256k1-groestl` trezor-crypto curve (to generate xpubs correctly), implements Groestlcoin address in C++, adds coin configuration and relevant tests. Please review are changes acceptable so far.
=> [WIP/RFC] Groestlcoin (GRS) support

include/TrustWalletCore/TWTezosProto.h, src/Tezos/Forging.cpp, src/proto/Tezos.proto, tests/Tezos/OperationListTests.cpp
Add an origination operation for Tezos. 
Origination operations allow tz1 addresses to originate KT1 addresses which they manage. 
Run ./bootstrap.sh
Forged an operation using a Tezos node and then created a unit test around it.
- [ X ] Prefix PR title with `[WIP]` if necessary.
- [ X ] Add tests to cover changes as needed.
- [ X ] Update documentation as needed.
=> Add origination operation for Tezos

include/TrustWalletCore/TWTezosProto.h, src/Tezos/Forging.cpp, src/proto/Tezos.proto, tests/Tezos/OperationListTests.cpp
Add a delegation operation for Tezos.
Delegations operations allow kt1 addresses to delegate their entire balance to tz1, tz2, and tz3 addresses which are registered as bakers.
Run ./bootstrap.sh
Forged an operation that set a delegate and cleared a delegate using a Tezos node and then created a unit test around it.
- [ X ] Prefix PR title with `[WIP]` if necessary.
- [ X ] Add tests to cover changes as needed.
- [ X ] Update documentation as needed.
=> Tezos delegation

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt
These changes help prevent some coins derivation tests to be left behind.
The refactoring make the check exhaustive.
=> Make address derivation tests exhaustive

CMakeLists.txt
For now project cannot be compile with GNU. For make more clarify compile error.
I propose add this check. When support another compilers will be added, this check can be deleted or changed.
Now the error looks like this:
With my changes:
[Compilers ID](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_COMPILER_ID.html)
Build on Linux with GNU Compiler 
* New feature
=> Add clang compiler check in CMakeLists.txt

README.md, android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt, include/TrustWalletCore/TWCoinType.h, include/TrustWalletCore/TWHRP.h, include/TrustWalletCore/TWP2PKHPrefix.h, include/TrustWalletCore/TWP2SHPrefix.h, src/Bitcoin/Script.cpp, src/Coin.cpp, src/interface/TWCoinTypeConfiguration.cpp, src/interface/TWHRP.cpp, swift/Sources/Addresses/CoinType+Address.swift, swift/Tests/Blockchains/QtumTests.swift, swift/Tests/CoinAddressDerivationTests.swift, swift/Tests/SlipTests.swift, tests/CoinTests.cpp, tests/interface/TWCoinTypeConfigTests.cpp, tests/interface/TWHRPTests.cpp, tests/interface/TWQtumTests.cpp
Added support for send/receive `Qtum` coins.
Support exist for `P2PKH` and `bech32`.
Support for `P2SH` added but disabled due to `Litecoin` and `Qtum` have the same prefix for it, more description in the commits.
Support for smart contracts not added, due to no such functionalities in the trust wallet.
Tested only with unit tests.
Run `./bootstrap.sh` to execute the unit tests for `Qtum`.
=> Add support for Qtum

codegen/bin/codegen
codegen, while iterating over options.input, ignores files named '.DS_Store'.
.DS_Store files are auto-generated inside a directory by macOS when that directory is opened in Finder. If codegen, while parsing it's input directory, encounters this file, it exits with an error such as follows:
> Found a class NimiqSigner
Found an enum HRP
Found a class GroestlcoinTransactionSigner
...wallet-core/codegen/lib/parser.rb:23:in 'skip_until': invalid byte sequence in UTF-8 (ArgumentError)
from .../wallet-core/codegen/lib/parser.rb:23:in 'parse'
from ../codegen/bin/codegen:68:in 'block in \<main>'
from ../codegen/bin/codegen:65:in 'foreach'
from ../codegen/bin/codegen:65:in '\<main>'
My edit simply skips this file when parsing all the files in the input.
I'm uncertain of the exact circumstances …
=> Minor update to codegen to ignore .DS_Store files

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt, include/TrustWalletCore/TWCoinType.h, include/TrustWalletCore/TWEthereumChainID.h, src/Coin.cpp, src/interface/TWCoinTypeConfiguration.cpp, swift/Sources/Addresses/CoinType+Address.swift, swift/Sources/ChainID.swift, swift/Tests/CoinAddressDerivationTests.swift, swift/Tests/Keystore/WalletTests.swift, swift/Tests/SlipTests.swift, tests/CoinTests.cpp, tests/interface/TWCoinTypeConfigTests.cpp
add Ethersocial Network (ESN) support
- Homepage: https://ethersocial.org/
- Block Explorer : https://ethersocial.net
- API node: https://api.esn.gonspool.com
- BIP44 / Chainid `31102` ( satoshilabs/slips#277 )
- Ticker: ESN
- CMC: https://coinmarketcap.com/currencies/ethersocial/
`./bootstrap.sh` or `make -C build tests`
Ethersocial Network support added
=> support Ethersocial Network

js/cpp/TWNapi.h, js/tests/blockchain/bitcoin/SegwitAddress.test.ts, js/tests/utils/HDWallet.test.ts
- Change `Bech32Address` imports and tests
- Fix HDWallet test
=> Fix JS Bech32Address and HDWallet tests

src/Bravo/Asset.h, src/Bravo/Operation.h, src/Bravo/Serialization.h, src/Bravo/Transaction.h
While originally designing the Bravo/graphene code, we had created an interface class "Serializable". This class has no use anymore and hence we are removing it to clean up the codebase. Also, collection sizes are now encoded as uint64 instead of uint32.
Compiling and running existing tests should 
* Non-breaking change which cleans up the code
=> Bravo: Remove "Serializable" class as it is not used anymore

tests/Cosmos/AddressTests.cpp
Add tests for validating various Cosmos addresses
https://github.com/TrustWallet/wallet-core/issues/255
=> Cosmos support - Add cosmos address validation with different prefixes

.codacy.yaml, README.md, android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt, include/TrustWalletCore/TWHRP.h, include/TrustWalletCore/TWZilliqaAddress.h, js/tests/utils/CoinAddressDerivation.test.ts, src/Coin.cpp, src/Zilliqa/Address.cpp, src/Zilliqa/Address.h, src/Zilliqa/AddressChecksum.cpp, src/Zilliqa/AddressChecksum.h, src/Zilliqa/Signer.cpp, src/interface/TWHRP.cpp, src/interface/TWZilliqaAddress.cpp, swift/Tests/Blockchains/ZilliqaTests.swift, swift/Tests/CoinAddressDerivationTests.swift, swift/Tests/HDWalletTests.swift, tests/CoinTests.cpp, tests/Zilliqa/AddressTests.cpp, tests/Zilliqa/SignerTests.cpp, tests/interface/TWCoinTypeConfigTests.cpp, tests/interface/TWHRPTests.cpp, tests/interface/TWZilliqaTests.cpp
=> implement zilliqa bech32 address

src/PublicKey.cpp, swift/Tests/PublicKeyTests.swift, tests/interface/TWPublicKeyTests.cpp
Fix verifying ed25519 signature, this is introduced when we refactored public key type (https://github.com/TrustWallet/wallet-core/pull/378)
=> Fix verifying ed25519 signature

swift/Sources/Keystore/KeyStore.swift, swift/Tests/Keystore/KeyStoreTests.swift
Triggering method updateWallet(wallet: Wallet, password: String, newPassword: String) to update wallet password caused also removing all wallet accounts except the first one. 
1. Create a Wallet with support for multiple coins
2. Update wallet password
Excepted result: 
The same wallet with changed password
Current behavior:
Wallet for first coin with changed password
=> Fix method keystore.updateWallet for multiple accounts wallets

swift/Sources/Keystore/KeyStore.swift, swift/Tests/Keystore/KeyStoreTests.swift
Currently, it's possible to update only wallet password, but it's not possible to update wallet name via KeyStore.
It's very similar operation as updating password (both of them are stored in StoredKey) so I reuse existing code for password updating in new private method to handle KeyStore update and create two public methods - one for updating password (compatible with previous code), the second one for updating the name.
* Create wallet
* Update name
* Check updated name
=> Add option to update Wallet Name

include/TrustWalletCore/TWAnySigner.h, src/AnySigner.cpp, src/AnySigner.h, src/interface/TWAnySigner.cpp, tests/AnySignerTests.cpp
After `pod install` all files are in a flat folder, there is a file already called `TransactionSigner.h`, This fixes potential conflicts
=> Rename TransactionSigner to AnySigner

include/TrustWalletCore/TWCoinType.h, src/IOST/Account.cpp, src/Zilliqa/Address.h, src/interface/TWCoinType.cpp, swift/Sources/Addresses/CoinType+Address.swift, swift/Tests/Addresses/BitcoinAddressTests.swift, swift/Tests/Blockchains/ZilliqaTests.swift, tests/IOST/AddressTests.cpp, tests/interface/TWHRPTests.cpp
* implement code generation for `hrp` in `CoinType.swift`
* refactor address() in CoinType.swift to use the existing validation `TW::validateAddress()` in `Coin.cpp`
=> Move logic in CoinType+Address.swift to C++ side

codegen/bin/coins, codegen/lib/templates/coins.md.erb, coins.json, docs/coins.md
Fix #423 , `docs/coins.md` is also code generated
=> Add rpc node info to coin configuration

src/Any/Signer.cpp, src/proto/Any.proto, tests/Any/SignerTests.cpp
I notice some inconsistencies between ios and android trust provider. This was due to the confusing output message, which I did myself (sorry). This PR is a simplification and improvement to AnySigner output message to remove any doubts about it's result.
Just run `./bootstrap.sh`
* Now `error` and `success` are grouped as `oneof`. If error was set, success is automatically false.
* Now there is only one `output` property, which contains the signing result. Removed `json` and `encoded`.
=> Improve AnySigner output message

include/TrustWalletCore/TWEthereumChainID.h
According to https://chainid.network/, we should use 108, not 18
=> Fix thunder token mainnet chain id

src/Coin.cpp, src/Zcash/TAddress.cpp, src/Zcash/TAddress.h, tests/Zcash/AddressTests.cpp
Minor refactoring: move address prefix check more upstream, from Coin.cpp to Zcash::TAddress.
Add C++ class level unit tests for address (were missing).
Unit tests.
* Minor refactoring, no behaviour change
=> ZCash: move prefix check more upstream, add C++ class level unit tests.

src/Any/Signer.cpp, tests/Any/SignerTests.cpp, tests/interface/TWAnySignerTests.cpp
Include Nano in the supported coins by AnySigner.  Also created AnySigner C interface tests with a few coins (was missing completely).
Note that only block signature is returned (as hex string).
Fixes #731 .
Unit tests.
Extra functionality (in AnySigner), other functionality should not be affected.
=> Add Nano support to AnySigner, (#731)

Dockerfile, protobuf-plugin/CMakeLists.txt, tools/generate-files, tools/install-dependencies
Fix generate-files on Docker.  In addition:
- All dependency binary compilation&install is done by tools/install-dependencies
- On Docker, /usr/local is used to place results, on non-Docker, local build dir
- Binaries are taken from $PREFIX variable
- moved protobuf-plugin compilation to install-dependencies.
Fixes #751 .
see above
docker -i -t trustwallet/wallet-core /bin/bash
cd wallet-core
./tools/generate-files
Note that ./tools/install-dependencies is not needed, but should also work now.
=> Fix generate-files on Docker

docker/wallet-core-run/Dockerfile, docker/wallet-core/Dockerfile, tools/docker-build, tools/install-dependencies
- New docker image, with built, runnable version of the library; called wallet-core-run
- Docker image optimizations:
-- Update docker image base to Ubuntu 18.04 (from 16.04)
-- CMake: install binaries, do not build, to speed up creation
-- Remove Nodejs.
Now it is possible to do:
- docker run -i -t trustwallet/wallet-core-run:latest
- cd wallet-core && ./build/tests/tests tests
- docker build -t trustwallet/wallet-core-run:latest ./docker/wallet-core-run
- docker run -i -t trustwallet/wallet-core-run:latest
- cd wallet-core && ./build/tests/tests tests
=> New runnable docker image

src/Ethereum/ABI/ParamAddress.h, src/interface/TWEthereumAbiFunction.cpp, tests/Ethereum/AbiTests.cpp
Change padding of Address type ABI parameter; treated as UInt160, not ByteArray20; padded to the right, not left.
Fixes #756 .
Unit tests, *Abi*.
=> Ethereum ABI: Fix address parameter padding.

include/TrustWalletCore/TWHDWallet.h, src/Bitcoin/SegwitAddress.cpp, src/interface/TWHDWallet.cpp, tests/interface/TWHDWalletTests.cpp
New shortcut method TWHDWalletGetAddressForCoin() to derive an address from HD wallet directly, without need to handle private key.
Fixes #740 .
Unit tests
* Small new feature (non-breaking change which adds functionality)
=> HDWallet: New method to derive address directly from wallet.

tests/WalletConsoleTests.cpp, walletconsole/lib/Coins.cpp
Public key type was incorrectly derived from curve, which did not account for non-compressed/compressed variation.  Now it is obtained directly.
Fixes #767 .
In walletconsole:
```
> coin harmony
> newKey
> pubPri #
> addrPub #
```
Expected: no error.  Current:  Error while executing command, address may only be an extended SECP256k1 public key
=> Walletconsole: Fix public key type derivation for coins.

include/TrustWalletCore/TWZilliqaSigner.h, src/interface/TWZilliqaSigner.cpp, swift/Tests/Blockchains/ZilliqaTests.swift
If you compile wallet core from source and archive a build, it might fail, this constant should be able to get from RPC
=> Remove potential duplicated symbol error

src/Cbor.cpp, src/Cbor.h, src/PrivateKey.cpp, src/PrivateKey.h, src/PublicKey.cpp, src/PublicKey.h, src/Tezos/Forging.cpp, src/interface/TWPrivateKey.cpp, src/interface/TWPublicKey.cpp, tests/CborTests.cpp, tests/Tezos/AddressTests.cpp, tests/interface/TWPrivateKeyTests.cpp
CBOR (Concise Binary Object Representation) encoding and decoding, to be used by Cardano and Filecoin (see  http://cbor.io  and   RFC 7049).
Also, some minor internal refactor in PrivateKey and PublicKey, use Data instead of byte array.
Unit tests.
=> CBOR implementation and tests.

src/Any/Signer.cpp, tests/Any/SignerTests.cpp, tests/interface/TWAnySignerTests.cpp
Bitcoin Cash with the test was added (taken from Bitcoin Cash signer)
Litecoin was added without the test, because I did not find any signing test at the library. I assume that it is working absolutely the same as Bitcoin
`NetworkNotSupported` test was changed. Currently, the coin type is Zcash, not Bitcoin Cash. 
The `TwAnySignerTests` file was also changed. Bitcoin Cash is supported now.
Run ./boostrap.sh
=> [AnySigner] Add BitcoinCash with test + Litecoin

codegen/bin/newcoin, codegen/lib/templates/newcoin/AddressTests.kt.erb, codegen/lib/templates/newcoin/Proto.erb, codegen/lib/templates/newcoin/Signer.cpp.erb, codegen/lib/templates/newcoin/Signer.h.erb, codegen/lib/templates/newcoin/SignerTests.kt.erb, codegen/lib/templates/newcoin/TWSigner.cpp.erb, codegen/lib/templates/newcoin/TWSigner.h.erb, codegen/lib/templates/newcoin/TWTests.cpp.erb, codegen/lib/templates/newcoin/Tests.swift.erb, coins.json
Based on #817, part of #816 
1. Developers can focus on c++ implementation, don't have to worry about C interfaces for address / signer.
2. A default `proto` file is also added
How to test: 
1. Add below to `coins.json`
```json
{
"id": "nervos",
"name": "Nervos",
"symbol": "CKB",
"decimals": 8,
"blockchain": "Nervos",
"derivationPath": "m/44'/309'/0'/0/0",
"curve": "secp256k1",
"publicKeyType": "secp256k1",
"explorer": {
"url": "https://explorer.nervos.org",
"txPath": "/transaction/",
"accountPath": "/address/"
},
"info": {
"url": "https://www.nervos.org",
"client": "https://github.com/nervosnetwork/ckb",
"clientPublic": "",
"clientDocs": "https://docs.nervos.org/introduction/welcome.html"
}
}
```
2. run `codegen/bin/newcoin nervos`
2. handle `TWCoinTypeNervos` in `Coin.cpp`
3. build and …
=> Improve newcoin scaffold

coins.json, tests/EthereumClassic/TWCoinTypeTests.cpp
Change ETC explorer to etcblockexplorer.com, as blockscout.com is ceasing support.  Fixes issue #822 .
Check explorer URLs from tests/EthereumClassic/TWCoinTypeTests.cpp .
* Minor
=> Update ETC explorer to etcblockexplorer.com.

include/TrustWalletCore/TWString.h, src/interface/TWAnyAddress.cpp, src/interface/TWString.cpp, tests/interface/TWAnyAddressTests.cpp, tests/interface/TWZilliqaTests.cpp
`TWStringCreateWithUTF8Bytes` expects null terminated string, We should call `TWStringCreateWithRawBytes` in tests
=> Fix zilliqa address data tests unstable

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt, coins.json, docs/coins.md, include/TrustWalletCore/TWBlockchain.h, include/TrustWalletCore/TWCoinType.h, include/TrustWalletCore/TWFilecoinSigner.h, src/Coin.cpp, src/Filecoin/Address.cpp, src/Filecoin/Address.h, src/Filecoin/Signer.cpp, src/Filecoin/Signer.h, src/Filecoin/Transaction.cpp, src/Filecoin/Transaction.h, src/interface/TWFilecoinSigner.cpp, src/proto/Filecoin.proto, swift/Tests/Blockchains/FilecoinTests.swift, swift/Tests/CoinAddressDerivationTests.swift, tests/Filecoin/AddressTests.cpp, tests/Filecoin/SignerTests.cpp, tests/Filecoin/TWCoinTypeTests.cpp, tests/Filecoin/TransactionTests.cpp, tests/interface/TWFilecoinSignerTests.cpp
Adds support for Filecoin, implementing a secp256k1-based wallet.
(Old PR https://github.com/trustwallet/wallet-core/pull/784)
- Filecoin support (with secp256k1 wallet)
Closes #780.
=> Filecoin support

codegen/bin/codegen
`codegen -i <value>` and `codegen -o <value>` flags are incorrectly mapped to `options.swift`
Guess the changes are so trivial they don't require any tests or documentation.
Run `./codegen/bin/codegen -i <value>` with a different input directory
=> Fix codegen flag mapping

codegen/bin/newcoin, src/Coin.cpp
In new coin templating script `newcoin` include to automatically add the needed lines to `src/Coin.cpp`: an include and an instance creation line. Fixes #886 .
- Clean workspace
- Add new Dummy coin to coins.json
- run codegen/bin/newcoin dummy
- check resulting Coin.cpp, build, etc.
=> Update newcoin script to auto include coin entry include and creation.

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/harmony/TestHarmonyStakingDelegateSigner.kt, src/Harmony/Signer.cpp, src/Harmony/Staking.h, src/proto/Harmony.proto, swift/Tests/Blockchains/HarmonyTests.swift, tests/Harmony/StakingTests.cpp, tests/Harmony/TWHarmonyStakingTests.cpp
Updated the staking transaction fields based on the latest harmony staking packet
Updated test cases for the new data structure fields:
Note: the field "active" in DirectiveEditValidator has three values 0: nil (no change),  1: change to active, 2: change to inactive. Please update UI in ios/android app for these three values.
message DirectiveEditValidator {
string validator_address = 1;
Description description = 2;
Decimal commission_rate = 3;
bytes min_self_delegation = 4;
bytes max_total_delegation = 5;
bytes slot_key_to_remove = 6;
bytes slot_key_to_add = 7;
bytes slot_key_to_add_sig = 8;
bytes active = 9;   <== 0: nil,  1: active, 2:inactive
}
Passed the following tests
1) ./bootstrap.sh
2) ./tools/ios-test
3) ./tools/android-test
=> [harmony] updated data structures and tests for harmony staking support

src/interface/TWEthereumAbiFunction.cpp, tests/Ethereum/TWEthereumAbiEncoderTests.cpp, tests/Ethereum/TWEthereumAbiValueEncodeTests.cpp
Fix crash in EthereumAbi encoder with wrong parameter type.  Fixes #895 .
Unit tests, incl. new test.
=> Fix crash in EthereumAbi encoder with wrong parameter type.

walletconsole/lib/Util.cpp
Add missing call to `delete` in function `fileR`.
The error was detected using `cppcheck`. For example you can execute `cppcheck --quiet --force walletconsole/`
=> Fix possible memory leak in walletconsole/Util.cpp

src/Bitcoin/TransactionSigner.cpp, src/Decred/Signer.cpp, tests/Bitcoin/TWBitcoinSigningTests.cpp, tests/Decred/SignerTests.cpp
Early check for case with 0 inputs, to prevent asserts.  Fixes #950 .
Bug occurs when invalid address is provided.
Very similar for both Bitcoin and Decred code.
Unit test.
=> Bitcoin&Decred signing: Fix for assert bug for invalid address.

.github/PULL_REQUEST_TEMPLATE.md, .gitignore, swift/Sources/Extensions/Data+Hex.swift, swift/Tests/Blockchains/HarmonyTests.swift, swift/Tests/DataTests.swift, tests/HexCodingTests.cpp
Since hex parsing code is not only for number, to be consistent with c++ `parse_hex` and avoid cases like:
```swift
let gasPrice = Data(hexString: "28fa6ae00")
// gasPrice becomes -> 28fa6ae000
```
we will return nil if length is odd
=> [Swift] Return nil if hex string length is odd

src/Solana/Transaction.h, tests/Solana/SignerTests.cpp, tests/Solana/TWAnySignerTests.cpp, tests/Solana/TransactionTests.cpp
Users may transfer to self as test. For this to succeed on solana, we need an update to node runtime (merged, included in next solana release) and update the transaction format in wallet-core to index the same account twice. This pr implements proper account indexing when pay-to-self is requested.
Unit tests.
Integration: Once Solana cluster updates to the next v1.1 release, attempt TrustWallet app payment to self. Transaction should succeed, account should see fees deducted.
=> Enable Solana pay-to-self transactions

src/Bitcoin/TransactionBuilder.cpp, tests/Bitcoin/TWBitcoinSigningTests.cpp, tests/Decred/TWAnySignerTests.cpp
For non-segwit BTC forks, such as Decred, use simple estimation, to prevent under-estimate.  Fixes #999.
Unit tests, *Decred*.
=> [Decred fee] Use simple estimation for non-segwit coins

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/ethereum/TestEthereumAbiDecoder.kt, include/TrustWalletCore/TWEthereumAbiValueDecoder.h, src/Ethereum/ABI/ValueDecoder.cpp, src/Ethereum/ABI/ValueDecoder.h, src/interface/TWEthereumAbiValueDecoder.cpp, swift/Tests/Blockchains/EthereumAbiTests.swift, tests/Ethereum/TWEthereumAbiValueDecoderTests.cpp, tests/Ethereum/ValueDecoderTests.cpp
A quick fix for cUSDT `balanceOf` parsing, decode hex to big integer string (closes #1002, we can add other types later)
=> Add EthereumAbiDecoder

codegen/lib/templates/jni/method_forward.erb, src/Algorand/BinaryCoding.h, src/Ethereum/RLP.cpp, src/Keystore/EncryptionParameters.cpp, src/Keystore/ScryptParameters.cpp
Fix compiler warnings, Android build.  Fixes #993 .
- Unused 'cleanup' label in generated code: refine code generator to include when it is used
- always true (or false) comparisons (platform dependent!) -- add pragma warning and comment
- unused variable: used in assert only, which is ignored on release -- add pragma warning
- shift overflow: use 1ULL for correct larger size.
Android compile  /tools/android-build
=> Fix compiler warnings.

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/bitcoin/TestBitcoinSigning.kt, include/TrustWalletCore/TWBitcoinScript.h, src/Bitcoin/SigHashType.h, src/interface/TWBitcoinScript.cpp, swift/Tests/Blockchains/BitcoinTests.swift, swift/Tests/Blockchains/BitconCashTests.swift, swift/Tests/Blockchains/DecredTests.swift, swift/Tests/Blockchains/GroestlcoinTransactionSignerTests.swift, swift/Tests/Blockchains/LitecoinTests.swift, swift/Tests/Blockchains/ZcashTests.swift, tests/Bitcoin/TWBitcoinScriptTests.cpp, tests/Bitcoin/TWBitcoinSigningTests.cpp
HashTypeForCoin: fix return type to uint32, invalid enum values did not go through Swift/Kotlin interfaces.
For BitcoinCash and BitcoinGold, hashtype is two enum values OR'ed together, which itself not a valid enum value.  This works in C/C++, but in Swift/Kotlin it results in invalid/null value.  This is fixed by changing return type to uint32_t.  Fixes #1041 .
C++ unit tests, iOS unit tests.
=> HashTypeForCoin: fix return type to uint32

src/Ethereum/ABI/Array.cpp, src/Ethereum/ABI/Array.h, src/Ethereum/ABI/Parameters.cpp, src/Ethereum/ABI/Parameters.h, tests/Ethereum/AbiTests.cpp
- ParamArray.getSize() was incorrect, did not match the size resulting from encode().
- ParamArray encode/decode was incorrect in the case the array elements are dynamic types.
- Added more size checks.
- Fixes #1047 .
Standard unit tests, esp. '*Abi*'.
=> Eth ABI enocde/decode fix (ParamArray)

src/Ethereum/ABI/ParamFactory.cpp, src/Ethereum/ABI/ParamNumber.cpp, src/Ethereum/ABI/ParamNumber.h, tests/Ethereum/AbiTests.cpp, tests/Ethereum/ContractCallTests.cpp, tests/Ethereum/Data/getAmountsOut.json
There was an overlap of ParamUIntN and ParamUInt<N> types, both ParamUInt256 and ParamUIntN(256) has type "uint256".  This caused nullptr in type conversion.
Now I changed ParamFactory accordingly, and forbid using the generic version for the predefined sizes.
It can be still used for sizes: 24, 40, 48, 56, 72, 80, 88, ..., 248 (probably rarely used).
New tests also added.
Fixes #1129 .
Unit tests (esp. EthereumAbi and Contract).
=> Eth ABI decoede types mismatch issue fix.

src/HDWallet.cpp, tests/WalletConsoleTests.cpp, walletconsole/lib/Address.cpp, walletconsole/lib/Address.h, walletconsole/lib/CommandExecutor.cpp, walletconsole/lib/Keys.cpp, walletconsole/lib/Keys.h
Extend walletconsole with dumpXpub and addrXpub commands:
-   dumpXpub                Dump the XPUB of the current mnemonic
-   addrXpub <xpub> <index> Derive a new address from the given XPUB and address index (using current coin)
Unit tests.
* New small feature (non-breaking change which adds functionality)
=> Extend walletconsole with dumpXpub and addrXpub commands

src/Binance/Serialization.cpp, swift/Tests/Blockchains/BinanceChainTests.swift, tests/Binance/SignerTests.cpp
Fixes #1141, mainnet tests in swift added
=> [Binance] Fix timelock unlock signature error

src/Keystore/StoredKey.cpp, src/Keystore/StoredKey.h, src/interface/TWStoredKey.cpp, tests/Keystore/StoredKeyTests.cpp
Instead of a pointer return (which may become unsafe), the object is returned (with optional, as null return is a valid case).
Only 2 internal classes affected, the C inerface and swift/kotlin not.
Fixes #1164 .
Standard unit tests; new unit test  `StoredKey.AccountGetDoesntChange`
=> Fix unsafe pointer return to object return

src/Ethereum/Signer.cpp, src/Ethereum/Transaction.h, src/proto/Ethereum.proto, tests/BinanceSmartChain/SignerTests.cpp, tests/Ethereum/SignerTests.cpp, tests/Wanchain/SignerTests.cpp
#1210 followup
- `transfer` and `contract` underlaying is same, separate cases allow user adding `Transfer`, `Smart Contract Call` easily on UI
- Fix `transfer` case wrong data variable
- some cleanup
=> [Ethereum] Add amount to contract and fix data variable in case transfer

src/Bitcoin/UnspentSelector.cpp, src/Bitcoin/UnspentSelector.h, tests/Bitcoin/TransactionPlanTests.cpp, tests/Bitcoin/UnspentSelectorTests.cpp
Bitcoin Plan: use dynamic dustLevel (for ensuring non-dust change).  So far the hardcoded value of 3*182 was used.  Now singleInputFee is used, multiplied with the current byteFee.
Note that the exact value of the change dustLevel is not critical, because if no input selection is found that would result in non-dust change, as a fallback we use a selection disregarding the non-dust change condition.
Unit tests.
=> BTC Plan: use dynamic dustLevel (for ensuring non-dust change)

src/Bitcoin/TransactionBuilder.cpp, src/proto/Bitcoin.proto, tests/Bitcoin/TransactionPlanTests.cpp, tests/Decred/SignerTests.cpp
BTC signing/planning has two modes:
- UseMax -- TX is prepared with max amount possible, input.amount has no relevance.  Amount will be max available minus fee, with no change.
- Non-max amount: TX is prepared with sent amount equal to requested amount, if possible (fail otherwise).
If UseMax=false, but requested amount equals or is more than available, currently wallet-core returns an error, as it is impossible to send the requested amount.
Change this behavior to be more robust with the caller, and treat this case **as UseMax case**.
No change in the app is needed.
This is an edge case. Some cases when this is relevant, when app behaves differently, may be:
- requested amount == available, but the app forgets to set UseMax amount, or 
- some UTXO is prefiltered by app as dust, but the …
=> BTC plan/sign: if requested amount is same or more than avail, use max

src/Bitcoin/TransactionBuilder.cpp, tests/Bitcoin/TransactionPlanTests.cpp
In BTC plan, if MaxAmount is requested, the requested amount has no meaning, can be anything.  However, the reqAmount=0 case triggered an earlier sanity check, resulting an error.  This is a valid input combination, not error now.
This is a minor change in a low-prob edge case, the apps are not setting reqAmount to 0.
Unit tests; TransactionPlan.MaxAmountRequestedZero.
=> BTC plan: Treat MaxAmount, reqAmount=0 as not error

walletconsole/lib/Util.cpp
Fix for low-prob. minor memory leak, delete[] was missing in a catch branch.  Fixes #1286 .
Unit tests.
=> Fix for missing delete in case of exception.

tests/Oasis/TWCoinTypeTests.cpp
Fix missing memory deallocation in Oasis tests; caught in ASAN memory tests on master CI build.
https://github.com/trustwallet/wallet-core/runs/1961152603
All tests on master (after merging) should be green.
=> [Test only] Oasis tests: Fix missing memory dealloc

android/app/src/androidTest/java/com/trustwallet/core/app/utils/TestPrivateKey.kt, include/TrustWalletCore/TWPrivateKey.h, src/PrivateKey.cpp, src/PrivateKey.h, src/interface/TWPrivateKey.cpp, swift/Tests/PrivateKeyTests.swift, tests/PrivateKeyTests.cpp, tests/interface/TWPrivateKeyTests.cpp
This PR exposes [ECDH Shared Key Computation](https://cryptobook.nakov.com/asymmetric-key-ciphers/ecdh-key-exchange) function on `PrivateKey` interface, which is commonly used across crypto applications. 
Internally it calls `ecdh_multiply()` from `TrezorCrypto`, computes SHA-256 hash from compressed version of resulting key - [in the same manner as libsecp256k1](https://crypto.stackexchange.com/a/57727)
Core library tests:
```sh
$ make -Cbuild
$ ./build/tests/tests tests --gtest_filter="PrivateKey*"
$ ./build/tests/tests tests --gtest_filter="TWPrivateKey*"
```
iOS tests:
```sh
$ ./tools/ios-test
```
Android tests:
```sh
$ ./tools/android-test
```
=> Expose ECDH shared key derivation

include/TrustWalletCore/TWString.h, src/interface/TWString.cpp
No need to append `size` number of '\0' in function TWStringCreateWithRawBytes. TWStringSize would output `2 * size` without this fix, I think this is unnecessary.
```
TWString *_Nonnull TWStringCreateWithUTF8Bytes(const char *_Nonnull bytes) {
auto s = new std::string(bytes);
return s;
}
TWString *_Nonnull TWStringCreateWithRawBytes(const uint8_t *_Nonnull bytes, size_t size) {
auto s = new std::string(bytes, bytes + size);
// append null terminator
s->append(size, '\0');                     // Don't need this
return s;
}
```
Just like TWStringCreateWithUTF8Bytes, we don't append '\0'. We also no need to append '\0' in function TWStringCreateWithRawBytes.
=> Remove unnecessary null terminator

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt, coins.json, include/TrustWalletCore/TWCurve.h, src/HDWallet.cpp, src/HDWallet.h, src/PrivateKey.cpp, swift/Tests/CoinAddressDerivationTests.swift, trezor-crypto/crypto/bip32.c, trezor-crypto/crypto/curves.c, trezor-crypto/crypto/tests/test_check.c, trezor-crypto/include/TrezorCrypto/bip32.h, trezor-crypto/include/TrezorCrypto/curves.h
Oasis has requested that any new address should use a SLIP0010 with a derivation path based on BIP32 and 3 values only.
Given that Trustwallet integration is not available yet, the preference is to support this format only in Trustwallet.
This PR adjust wallet-core functionality according to this.
The CI tests will check the addresses generated with the new curve used.
* Breaking change (fix or feature that would cause existing functionality to change)
=> Oasis backward changes

docs/coins.md, tests/HDWalletTests.cpp, trezor-crypto/crypto/tests/test_check.c
Add official Bip32 tests, specifically to cover an issue with keys with leading zeros.  Test added to trezor-crypto and HDWallet tests.
https://github.com/bitcoin/bitcoin/pull/22095
https://blog.polychainlabs.com/bitcoin,/bip32,/bip39,/kdf/2021/05/17/inconsistent-bip32-derivations.html
https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki
Unit tests; TrezorCryptoTests.
* Tests only
=> [TestOnly] Additional Bip32 tests (leading zeros)

coins.json, tests/THORChain/TWCoinTypeTests.cpp
ThorChain decimals changed to correct value 8.  It has been changed in assets repo info already.
Unit tests.  Retrieve balance from Thorchain RPC.
=> ThorChain decimals changed to 8

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt, android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/bluzelle/TestBluzelleAddress.kt, android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/bluzelle/TestBluzelleSigner.kt, coins.json, docs/coins.md, include/TrustWalletCore/TWCoinType.h, src/Coin.cpp, src/Cosmos/Entry.h, src/interface/TWAnyAddress.cpp, swift/Tests/Blockchains/BluzelleTests.swift, swift/Tests/CoinAddressDerivationTests.swift, tests/Bluzelle/TWCoinTypeTests.cpp, tests/CoinAddressValidationTests.cpp, tests/interface/TWHRPTests.cpp
Added support for the Bluzelle blockchain  This PR supports sending funds and staking.
Since bluzelle uses the Cosmos SDK, the cosmos signing logic is reused. The integration is very similar to the Terra and Kava integration.
`bootstrap.sh` passes locally. Tests pass, coverage needs met.
`tools/android-test` passes locally. Tests pass, coverage needs met.
`tools/ios-test` passes locally. Tests pass, coverage needs met.
=> Bluzelle Chain Support

src/Ethereum/ABI/Bytes.cpp, tests/Ethereum/AbiStructTests.cpp, tests/Ethereum/Data/eip712_rarible.json
For data of variable-length type `bytes` hash is taken if length >32, otherwise the data itself is taken, padded to even 32 bytes.  Correct is to always take the hash.
Fixes #1576 .
- Hashing of ByteArray has been changed, corresponding tests updated
- Added test with the rarible.com data
Unit tests
=> Eth struct encoding fix, bytes type hash

src/Bitcoin/Transaction.h, src/Bitcoin/TransactionBuilder.h, src/Bitcoin/TransactionSigner.h, src/Groestlcoin/Transaction.h, src/Zcash/TransactionBuilder.h, src/proto/Bitcoin.proto, tests/Bitcoin/TWBitcoinSigningTests.cpp, tests/BitcoinGold/TWBitcoinGoldTests.cpp, tests/BitcoinGold/TWSignerTests.cpp
The lockTime field was not exposed through the SigningInput interface.
Although it is not used in Trust Wallet use cases, it is added for completeness and testability.
Some reference Bitcoin tests use non-zero lockTime.
The Proto change is backwards compatible, but breaking on binary level.
Unit tests.
=> Bitcoin proto: Expose LockTime field

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/ethereum/TestEthereumTransactionSigner.kt, src/Ethereum/Signer.cpp, src/proto/Ethereum.proto, swift/Tests/Blockchains/EthereumTests.swift, tests/Ethereum/TWAnySignerTests.cpp
Explicit selector for legacy/enveloped transactions (legacy/Eip1559).  Fixes #1581 .
This change is BREAKING:
- Code needs to be recompiled with new wallet core version (as proto buf numbering has changed)
- Ethereum SigningInput has to be extended with:
`txMode = TransactionMode.Legacy` for legacy transactions (this can be omitted as Legacy has value 0)
`txMode = TransactionMode.Enveloped` for enveloped transactions with EIP1559 fee
Unit tests, esp. TWAnySignerEthereum.
* Breaking change (fix or feature that would cause existing functionality to change)
=> Explicit selector for legacy/enveloped transactions

include/TrustWalletCore/TWHDWallet.h, src/HDWallet.cpp, src/HDWallet.h, src/Mnemonic.h, swift/Tests/HDWalletTests.swift, tests/interface/TWHDWalletTests.cpp, trezor-crypto/crypto/bip39.c, trezor-crypto/crypto/tests/test_check.c, trezor-crypto/include/TrezorCrypto/bip39.h
HDWallet creation is not thread-safe, calling simultaneously from multiple threads may result in invalid recovery phrases, and thus error.
Fix this by making the underlying Trezor lib methods -- mnemonic_generate() and mnemonic_from_data() -- thread safe, by using user-supplied output buffer instead of a common global variable.
Note that this PR is based on #1527 ar/hdwallet-error-fix, it should come after it; diff should be looked relative to that.
(Continuation of #1505 )
Unit tests, esp.`HDWallet.MultipleThreads`.
=> HDWallet creation thread-safe

android/app/src/androidTest/java/com/trustwallet/core/app/utils/TestHDWallet.kt, android/trustwalletcore/build.gradle, include/TrustWalletCore/TWHDWallet.h, src/HDWallet.cpp, src/HDWallet.h, src/Mnemonic.h, src/interface/TWHDWallet.cpp, swift/Tests/Blockchains/EthereumTests.swift, swift/Tests/HDWalletTests.swift, tests/HDWalletTests.cpp, tests/MnemonicTests.cpp, tests/interface/TWHDWalletTests.cpp
Re-add mnemonic validation checks (partial revert of #1601).  Non-English mnemonics are not supported.
Fixes #1607.
The important changed line: https://github.com/trustwallet/wallet-core/pull/1616/files?file-filters%5B%5D=.cpp&file-filters%5B%5D=.h&file-filters%5B%5D=.swift#diff-70145d862894261986b9cbc1be92f3af9e7cb4aeb7bd5c6790bf8ac4e8138e75L54
Unit tests, HDWallet.
=> HDWallet: re-add mnemonic validity check

src/Bitcoin/InputSelector.cpp, src/Bitcoin/InputSelector.h, src/Bitcoin/SignatureBuilder.cpp, src/Bitcoin/SignatureBuilder.h, src/Bitcoin/TransactionBuilder.cpp, src/Bitcoin/TransactionBuilder.h, tests/Bitcoin/InputSelectorTests.cpp, tests/Bitcoin/TWBitcoinSigningTests.cpp, tests/Bitcoin/TransactionPlanTests.cpp, tests/Bitcoin/TxComparisonHelper.cpp
Optimizations for cases with large number of UTXOs:
- In cases with over 1000 UTXOs, use simplified selection strategy -- uisng a single pass over UTXOs (O(N) instead of O(N log N)).
- Always limit to max. 3000 the number of UTXOs used, potentially resulting in a lower transfer amount (even in maxAmount case).
Fixes #1639.
Some benchmarks:
- 2000 utxos, 601 selected:   master:  7.18s   PR: 4.63s  35% speedup
- 5000 utxos, maxamount:    master: 234.0s   PR: 42.9s  81% speedup
(wc part, on dev laptop, median of 5 measurements).
Relevant unit tests.
* Optimization (non-breaking change which does not affect functionality, but improves performance) -->
=> Optimization for input selection in case of huge number of UTXOs

src/Bitcoin/CashAddress.cpp, src/Data.cpp, src/Data.h, src/Ethereum/RLP.cpp, src/Ripple/Transaction.cpp
Fixes buffer overruns.
Run the testing suite using a debug build with out of bounds checks enabled.
=> Fix buffer over-reads

src/FIO/Encryption.cpp
Assert can get compiled away in optimized builds.
Separate the call from the assert.
FIO tests fail under optimized release build under Visual Studio.
=> Fix incorrect assert usage. Assert expressions may be compiled out

src/Solana/Signer.cpp
This fixes the following compilation-error:
```
[ 18%] Building CXX object CMakeFiles/TrustWalletCore.dir/src/Solana/Signer.cpp.o
/home/felix/trustwallet-core/src/Solana/Signer.cpp:56:22: error: no member named 'optional' in namespace 'std'
std::optional<Address> stakeAddress;
```
=> fix Solana compilation error

src/Bitcoin/Script.cpp, src/Bitcoin/Script.h, tests/Bitcoin/BitcoinAddressTests.cpp, tests/Bitcoin/SegwitAddressTests.cpp, tests/Bitcoin/TWBitcoinSigningTests.cpp
For Taproot destination address, in lockScriptForAddress `buildPayToWitnessProgram` was used, with implicit V0 version.  Correct is V1 version (OP_1 0x50). For clarity, new `buildPayToTaprootPublicKey` method is added.
Fixes #1783 .
Unit tests.
https://mempool.space/tx/5df51e13bfeb79f386e1e17237f06d1b5c87c5bfcaa907c0c1cfe51cd7ca446d
=> [Bitcoin] Taproot output script building

include/TrustWalletCore/TWEncryptionParameters.h, include/TrustWalletCore/TWStoredKey.h, include/TrustWalletCore/TWStoredKeyEncryptionLevel.h, src/Keystore/EncryptionParameters.cpp, src/Keystore/EncryptionParameters.h, src/Keystore/ScryptParameters.cpp, src/Keystore/ScryptParameters.h, src/Keystore/StoredKey.cpp, src/Keystore/StoredKey.h, src/interface/TWStoredKey.cpp, swift/Tests/Keystore/KeystoreKeyTests.swift, tests/Keystore/StoredKeyTests.cpp, tests/interface/TWStoredKeyTests.cpp
Expose StoredKey encryption parameters, through C interface, as Json string.
StoredKey unit tests.
=> Expose StoredKey encryption parameters

README.md, tools/ios-xcframework-release
Fixes https://github.com/trustwallet/wallet-core/issues/1804
Currently we need to update `Package.swift` on master branch each time when there is a new release, this is tedious and not pined to exact that version / tag. This improves the process: go to the release page and download it when you need to update wallet core
=> [SPM] Upload Package.swift to GitHub release

android/app/src/androidTest/java/com/trustwallet/core/app/utils/TestKeyStore.kt, include/TrustWalletCore/TWStoredKeyEncryptionLevel.h, src/Keystore/EncryptionParameters.h, src/Keystore/ScryptParameters.cpp, src/Keystore/ScryptParameters.h, tests/Keystore/StoredKeyTests.cpp, tests/interface/TWStoredKeyTests.cpp
BREAKING: in case for new wallet encryption level is not specified explicitly, encryption parameters are changed, from 4k to 16k.
StoreKey: Introduce 3rd, in-between encryption level (16k), and make that default .
Levels are now:
- Minimal -- 4k
- Weak -- 16k <-- new, this is also new Default
- Standard -- 262k
Follow up on #1766 .
Unit tests. New wallet creation.
=> StoreKey: Introduce 3rd encryption level 16k, default

Package.swift, README.md
Update SPM usage guide, we will only bump master `Package.swift` periodically
=> Bump Package.swift on master

src/PublicKey.cpp, tests/PublicKeyTests.cpp
PublicKey.recover(): handle Eip155-style signatures with v>35 (chainId>0).
V values of 0&1 and 27&28 (Eth Eip155) were handled, but not v>35, of the form 35+chainId*2+v.
This is a minor improvement, triggered by #1898.
Unit tests.
=> PublicKey.recover(): handle Eip155-style signatures with v>35

bootstrap.sh
This makes the build work on a system with both gcc and clang installed (gcc being the default)
Specifically ask for clang as the compiler when building the project.
On ubuntu 21.10 with gcc being the default compiler and clang being available, run `./boostrap.sh` and check that it does not fail with the following error: `FATAL_ERROR "You should use clang compiler"`
=> cmake: specify clang as the compiler

include/TrustWalletCore/TWSegwitAddress.h, src/Bitcoin/Entry.cpp, src/Bitcoin/SegwitAddress.cpp, src/Bitcoin/SegwitAddress.h, src/Groestlcoin/Entry.cpp, src/interface/TWSegwitAddress.cpp, tests/Bitcoin/TWBitcoinSigningTests.cpp, tests/Bitcoin/TWSegwitAddressTests.cpp, tests/BitcoinGold/TWSegwitAddressTests.cpp, tests/HDWallet/HDWalletTests.cpp, tests/THORChain/SwapTests.cpp, tests/THORChain/TWSwapTests.cpp
Minor improvements related to Bitcoin Taproot address handling:
- `SegwitAddress()` constructor with PrivateKey does no support Taproot address, so witness version input is removed, it is always 0.  Note: C-version (`TWSegwitAddressCreateWithPublicKey`) had no witver. Note: Schnorr keys are not yet implemented.
- SegwitAddress constructor comment expanded to mention v0 and no Taproot (both C++ and C version)
- Added C accessor for segwit version `TWSegwitAddressWitnessVersion`, this was missing
- Internal witnessVersion field type changed to `byte` (from `int`).
Triggered by #1904 .
Unit tests, `*Segwit*`
=> [BTC] Taproot improvements

src/Bitcoin/CashAddress.cpp, src/Bitcoin/CashAddress.h, src/Bitcoin/Entry.cpp, src/Bitcoin/Script.cpp, src/interface/TWAnyAddress.cpp, tests/BitcoinCash/TWBitcoinCashTests.cpp, tests/HDWallet/HDWalletTests.cpp
The current implementation of `CashAddress` has the `"bitcoincash:"` prefix hardcoded. This PR makes the code ready to support other CashAddress prefixes. This is a first necessary step for suppporting eCash.
This is achieved by refactoring the code in `cashaddresss.h/cpp`, to make `CashAddress` a base class capable of supporting different prefixes, and adding a subclass `BitcoinCashAddress` which is now used in the rest of the codebase where `CashAddress` was used before.
```
cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug \
-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
make -Cbuild -j12 tests
build/tests/tests  tests
```
* Refactoring without change of behavior
* Preparing for new feature (non-breaking change which adds functionality)
=> Refactoring: prepare for supporting different CashAddress prefixes 

tests/HDWallet/HDWalletInternalTests.cpp, tests/HDWallet/HDWalletTests.cpp, tests/interface/TWHDWalletTests.cpp
Add extra derivation checks to HDWallet, demonstrating how a sequence of public keys can be derived from a single XPub, giving the same result as deriving a sequence of private keys (and obtaining public keys).
Unit tests 'HDWallet'.
* Extra Test only
=> [TestOnly] Extra HDWallet derivation tests

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt, android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/smartbitcoincash/TestSmartBitcoinCashAddress.kt, docs/registry.md, include/TrustWalletCore/TWCoinType.h, include/TrustWalletCore/TWEthereumChainID.h, registry.json, src/AnyAddress.h, src/Coin.cpp, src/Ethereum/Entry.h, swift/Tests/Blockchains/SmartBitcoinCashTests.swift, swift/Tests/CoinAddressDerivationTests.swift, tests/SmartBitcoinCash/TWCoinTypeTests.cpp, tests/interface/TWAnyAddressTests.cpp
Add Smart Bitcoin Cash (smartBCH for short). It is a sidechain for Bitcoin Cash and has an aim to explore new ideas and unlock possibilities. It is compatible with Ethereum's EVM and Web3 API and provides high throughput for DApps in a fast, secure, and decentralized manner.
Test in the same manner as BSC or Polygon was tested.
=> Add Smart Bitcoin Cash

include/TrustWalletCore/TWHDWallet.h, src/HDWallet.cpp, src/HDWallet.h, src/interface/TWHDWallet.cpp, tests/HDWallet/HDWalletTests.cpp, tests/interface/TWHDWalletTests.cpp
Add a way to obtain extended public key for non-default accounts.
Method TWHDWalletGetExtendedPublicKey derives an extended public key, but always using the default 0 account value.
Fixes #2084 .
Unit tests.
=> GetExtendedKey with custom account

src/Data.cpp, src/PrivateKey.cpp, src/PrivateKey.h, swift/Tests/Blockchains/CardanoTests.swift, tests/Cardano/AddressTests.cpp, tests/Cardano/TWCardanoAddressTests.cpp, tests/DataTests.cpp, tests/PrivateKeyTests.cpp, tests/interface/TWHDWalletTests.cpp, walletconsole/lib/Keys.cpp
Change approach to double-extended private key (used by Cardano):
instead of storing each subpart differently, store them all in the `bytes` member.
Issue was that in some places (through the C interface) only the `bytes` member was accessed, resulting in 32 bytes only (instead of 192 bytes).
Fixes #2136 .
Unit tests.
=> DoubleExt privatekeys: Access all data (Cardano fix)

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt, docs/registry.md, include/TrustWalletCore/TWCoinType.h, include/TrustWalletCore/TWEthereumChainID.h, registry.json, src/AnyAddress.h, src/Coin.cpp, src/Ethereum/Entry.h, swift/Tests/CoinAddressDerivationTests.swift, tests/Aurora/TWCoinTypeTests.cpp
[Aurora](https://doc.aurora.dev/) is an Ethereum Virtual Machine (EVM) implemented as a smart contract on [NEAR Protocol](https://near.org/)
Same as EVM chains
=> Add Aurora chain support

wasm/CMakeLists.txt, wasm/src/Random.cpp
Fixes https://github.com/trustwallet/wallet-core/issues/2220
Emscripten already uses random API (via `getRandomDevice`) available on Browser or Node, see https://github.com/emscripten-core/emscripten/blob/main/src/library.js#L2204
What we do here is simple, we wrap `std::random_device` with `std::mt19937` and return a random uint32 value, inspired by https://github.com/emscripten-core/emscripten/pull/12240
=> [Wasm] Implement secure random generator

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt, src/Ronin/Address.cpp, swift/Tests/CoinAddressDerivationTests.swift, tests/CoinAddressDerivationTests.cpp, tests/Ronin/TWAnyAddressTests.cpp
When normalizing a Ronin address, use the checksummed format, such as `ronin:EC49280228b0D05Aa8e8b756503254e1eE7835ab`.
Both checksummed and non checksummed versions are accepted as valid, this is not changed.
Ronin unit tests.
* Breaking change (fix or feature that would cause existing functionality to change)
=> Ronin: normalize address to checksummed format (EIP55)

.clang-format, src/Bitcoin/FeeCalculator.cpp, src/Bitcoin/FeeCalculator.h, tests/Bitcoin/FeeCalculatorTests.cpp
- Use constexpr/noexcept constructor to avoid `may throw during initialization storage`
- Make getFeeCalculator const
- Turn the default calculators constexpr
- Use C++17 inline variable for global value and give more readability
- Turn deprecated usage of virtual in an override function
- Use appropriately final when needed.
- Use noexcept when required
- Use `explicit` for single constructor
- Use `nodiscard` for non-void returning functions
- Do not use c-cast as they imply a `const_cast` by the compiler: https://en.cppreference.com/w/cpp/language/explicit_cast
```bash
make -C build tests && build/tests/tests tests
```
Modernize code (use modern c++, improve readability, more safeness)
ps: Regarding the format, my IDE have detected the `.clang-format` and applied format based on it
ps …
=> Modernize Bitcoin Fee Calculator code

src/Cardano/Signer.cpp, tests/Cardano/SigningTests.cpp
Fixes #2276.
Enable sending to legacy address.
Valdiated by TX to `DdzFFzCq...` address.
https://cardanoscan.io/transaction/d8253acbdbc05472143008a56e5f4de3c8efcc1eef54eac10cfc2409c4a9c126
```
83a4008182582043704889442705cbb4d6343af8ab67f6d92e8547f5b6edaee9c9f525e152420401018182584c82d818584283581c68eaca37f9778e1439db9b4c8a217f4f2d553f4291bfc20075e0c786a101581e581ceab1924a7c1ddf11afb3e641d2f475bb082bcf1a02a1780cf213bab5001a8f8f40041a00a54e07021a00028ab9031a03c03868a10081825820458c082404e4a57d915bd8ebd392ed6b36666a82e41e939a44ae3c371bd6f7475840eab5414428f6c8c1cd2ceb26cb9d7dd13406a53815d86d5b810621e01ec0d78a14140ea601e492519c9be4a2cfdb5723cdf0b1701a3888c16ae1b44097e4b20df6
```
Unit tests.  Perform transfer to legacy address (`DdzFF` or `Ae2` prefix).
* Bug fix (non-breaking change which …
=> Cardano: Enable sending to legacy address

src/Bitcoin/OutPoint.h, src/algorithm/to_array.h, tests/algorithm/to_array_tests.cpp
- some input collections may have a different size than the size of the array
- Got confused with the `assert(other.hash.size())` (was assuming every input will be of the size of std::array)
- make to_array take the type of the array
- use std::copy inside instead of index_sequences to avoid buffer overflow reading
run unit tests with ASAN enabled
=> [Fix]: use std::copy in implementation of to_array

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/TestCoinType.kt, include/TrustWalletCore/TWCoinType.h, src/interface/TWCoinType.cpp, swift/Tests/CoinTypeTests.swift, tests/interface/TWCoinTypeTests.cpp
fix #2392
- C++ unit tests
- Kotlin unit tests
- Swift unit tests
- TypeScript unit tests
=> [Interface]: Expose TWCoinTypeDerivationPathWithDerivation to C Interface

CMakeLists.txt, src/HDWallet.cpp, src/memory/memzero_wrapper.h, tests/memory/memzero_tests.cpp
- Add memzero wrapper
- wait for #2381 before modifying HDWallet.cpp
run C++ unit tests
* Improvements
=> [Improvements]: Add memzero wrapper

src/Keystore/StoredKey.cpp, src/Solana/Program.cpp, tests/Keystore/StoredKeyTests.cpp, tests/Solana/ProgramTests.cpp
Two minor fixes:
- StoredKey::privateKey() version with derivation disregarded the supplied derivation
- Solana TokenProgram::findProgramAddress ignored the provided `programId` parameter, but this caused no problem, as it is always invoked with the same constant value.
Found in #2397 
Standard unit tests
=> Fix for StoredKey::privateKey() with derivation

src/Cardano/AddressV3.cpp, src/Cardano/AddressV3.h, tests/Cardano/AddressTests.cpp
So far only the Base address type was supported (with spending and staking keys).
Support also Enterprise type (kind = 6, spending key only) and Reward type (kind = 14, staking key only).
Fixes  #2337
Cardano unit tests.
=> Cardano: Support Enterprise and Reward address types

include/TrustWalletCore/TWPrivateKeyType.h, src/HDWallet.cpp, src/HDWallet.h, src/PrivateKey.cpp, src/PrivateKey.h, tests/PrivateKeyTests.cpp
`PrivateKeyType` was internal to `PrivateKey` class.  Now this is exposed in a separate `TWPrivateKeyType` enum (available in swift/kotlin, if needed).
Also, the curve->pktype mapping is moved from `HDWallet` class to `PrivateKey`.
Note that only Cardano uses a special (96-byte) private key.
=> Expose PrivateKeyType

wasm/README.md, wasm/index.ts, wasm/tsconfig.json
Fixes https://github.com/trustwallet/wallet-core/issues/2417. This was introduced in https://github.com/trustwallet/wallet-core/pull/2332, it breaks wallet core react sample, revert back to old module type
Build and test locally (overwrite built js under `node_modules`
=> [Wasm] Revert module type and add README for NPM

samples/node/index.js, samples/node/package-lock.json, samples/node/package.json, wasm/package.json, wasm/tests/AES.test.ts, wasm/tests/AnyAddress.test.ts, wasm/tests/Base32.test.ts, wasm/tests/Base64.test.ts, wasm/tests/Blockchain/Ethereum.test.ts, wasm/tests/CoinType.test.ts, wasm/tests/HDWallet.test.ts, wasm/tests/HRP.test.ts, wasm/tests/Hash.test.ts, wasm/tests/HexCoding.test.ts, wasm/tests/Mnemonic.test.ts, wasm/tests/PBKDF2.test.ts, wasm/tests/StoredKey.test.ts, wasm/tests/setup.test.ts
Test only, to remove warnings like
```
(node:8671) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
```
Run unit tests
* Bug fix
=> [Test] Reuse global instance to remove max listener warning

src/Theta/Entry.cpp
Recent CI run are failing with this error:
```
void Entry::sign([[maybe_unused]] TWCoinType coin, const TW::Data& dataIn, TW::Data& dataOut) const {
^
/home/runner/work/wallet-core/wallet-core/src/Tezos/Entry.h:15:7: note: candidate found by name lookup is 'TW::Tezos::Entry'
class Entry: public CoinEntry {
^
/home/runner/work/wallet-core/wallet-core/src/Theta/Entry.h:16:7: note: candidate found by name lookup is 'TW::Theta::Entry'
class Entry: public Ethereum::Entry {
```
This change fixes the problem.
CI run should succeed
=> [Fix] Fix ambigious reference compile error

samples/osx/cocoapods/Podfile, samples/osx/cocoapods/Podfile.lock, samples/osx/cocoapods/WalletCoreExample/ViewController.swift
Use meaningful amount conversion in sample app (ios sample app, Eth amount), instead of hardcoded hex constant. It is more realistic this way, more educative, and easier to show best practice.
Note: BigInt is an external dependency.
See e.g. question https://github.com/trustwallet/wallet-core/discussions/2548.
Build & execute sample app, as described in README.
=> [Swift sample app] Use BigInt for Eth amount serialization

codegen/bin/newcoin
Fix incorrect enum constant generated in the `coinDispatcher` function when adding a new coin.
Generating a new coin should now add a new `case` to the `switch` in `coinDispatcher` using the corresponding `TWBlockchain` enum constant
=> Fix the enum constant generated in `coinDispatcher` when adding a new coin

tools/ios-release, tools/library
Fix GitHub API rate limited error when release CocoaPods build
```
{
"message": "API rate limit exceeded for 199.7.166.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
"documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"
}
```
=> [iOS] Add Authentication for curl request

include/TrustWalletCore/TWDataVector.h, swift/Sources/AnySigner.swift, swift/Sources/Extensions/AddressProtocol.swift, tools/ios-doc
Add missing doc string for `AnySigner` (not codegen), `DataVector` and `Address` protocol
Run `tools/ios-doc` and inspect
=> [Documentation] Add missing doc string for Swift classes

trezor-crypto/crypto/sha2.c
Fixed a small warning which were causing a build failure when building with some Emscripten versions.
This change is in line with the upstream version: https://github.com/trezor/trezor-firmware/blob/master/crypto/sha2.c
Unit tests.
=> [Trezor] Fix buffer with unmatched bound warning

src/FIO/Signer.cpp, src/FIO/Signer.h, src/FIO/TransactionBuilder.cpp, tests/FIO/SignerTests.cpp
From the description and implementation of the `signatureToBsase58`, I guess that's a typo, the name should be `signatureToBase58`.
=> [Fio] Fix `signatureToBase58` typo

codegen/lib/templates/swift/parameter_access.erb, include/TrustWalletCore/TWBase32.h, src/interface/TWBase32.cpp
fix(codegen): correct swift template for _Nullable string parameter handling
Before the change, we couldn't use _Nullable strings in C interfaces because incorrect code was generated in Swift resulting in immediate string object de-allocation. See #2368.
Unit tests
=> [Codegen] Fix _Nullable String param codegen for swift, make params _Nullable where needed

src/Polkadot/Extrinsic.cpp
https://github.com/trustwallet/wallet-core/pull/1418
=> Fix `Utility.batch_all` typo in Extrinsic.cpp

src/Aptos/MoveTypes.h, src/Aptos/Signer.cpp, src/Aptos/TransactionPayload.cpp, src/proto/Aptos.proto, tests/chains/Aptos/SignerTests.cpp
For token transfer, a registration is required before sending: https://aptos.dev/tutorials/your-first-coin/#step-432-registering-a-coin
I didn't see it during first iteration as swapping on the AMM I was using implicitly register the token for me
My understanding is that it's a security feature to avoid unwanted airdrop
Note that implementation team can still use `encode_submission` with the payload in the screenshot to register - this PR aims to give an handy way to generate this kind of transaction.
=> [Aptos]: add register token capabilities

android/app/src/androidTest/java/com/trustwallet/core/app/utils/TestAnyAddress.kt, android/app/src/androidTest/java/com/trustwallet/core/app/utils/TestHDWallet.kt, include/TrustWalletCore/TWAnyAddress.h, include/TrustWalletCore/TWHDWallet.h, samples/typescript/devconsole.ts/package-lock.json, samples/typescript/devconsole.ts/package.json, samples/typescript/devconsole.ts/samplescripts/bitcoin.addresses.sampleinput.txt, src/AnyAddress.cpp, src/AnyAddress.h, src/interface/TWAnyAddress.cpp, src/interface/TWHDWallet.cpp, swift/Tests/AnyAddressTests.swift, swift/Tests/HDWalletTests.swift, tests/common/AnyAddressTests.cpp, tests/interface/TWAnyAddressTests.cpp, tests/interface/TWHDWalletTests.cpp
Expose derivation option on `TWAnyAddressCreateWithPublicKey` and `TWHDWalletGetKey`.
New variants:
- `TWAnyAddressCreateWithPublicKeyDerivation` similar to `TWAnyAddressCreateWithPublicKey`
- `TWHDWalletGetAddressDerivation` similar to `TWHDWalletGetAddressForCoin`
- `TWHDWalletGetKeyDerivation` similar to `TWHDWalletGetKeyForCoin`, 
but with an extra `derivation` parameter.
Fixes #2682.
Unit tests.
* New feature (minor, non-breaking change which adds functionality)
=> Expose derivation option in AnyAddress, HDWallet

src/Bitcoin/Script.cpp, src/Bitcoin/Script.h, src/Bitcoin/TransactionBuilder.h, src/Bitcoin/TransactionSigner.cpp, src/Zcash/TransactionBuilder.h, tests/chains/Bitcoin/BitcoinScriptTests.cpp, tests/chains/Bitcoin/TWBitcoinSigningTests.cpp, tests/chains/THORChain/SwapTests.cpp
BitcoinScript/ThorSwap: Treat as error cases when memo is too long (do not truncate as currently).
- OpReturn building: treat as error if data is >80 bytes, as opposed to just truncate it.
- Bitcoin signing: propagate errors over several layers.
- One ThorSwap test changed as it produced memo > 80 bytes.
- Extra ThorSwap test with very long memo.
- In one non-ThorSwap case the error has changed, to a more meaningful one, in case of invalid output address, to `Error_invalid_address` from `Error_missing_input_utxos`.  https://github.com/trustwallet/wallet-core/pull/2741/files#diff-052bd5fec61fdb691c9327c764820d095121cc4e6bdc90c2ae651da8b9f02cbcR1074
Fixes #2730 .
Unit tests, esp. `SwapBtcNegativeMemoTooLong`.
If you're adding a new …
=> BitcoinScript/ThorSwap: Treat memo too long as error.

android/app/src/androidTest/java/com/trustwallet/core/app/utils/TestKeyStore.kt, include/TrustWalletCore/TWBase.h, include/TrustWalletCore/TWStoredKey.h, include/TrustWalletCore/TWStoredKeyEncryption.h, src/Keystore/AESParameters.cpp, src/Keystore/AESParameters.h, src/Keystore/EncryptionParameters.cpp, src/Keystore/EncryptionParameters.h, src/Keystore/StoredKey.cpp, src/Keystore/StoredKey.h, src/interface/TWStoredKey.cpp, swift/Sources/KeyStore.swift, swift/Tests/Keystore/KeyStoreTests.swift, tests/chains/XRP/TWAnySignerTests.cpp, tests/common/Keystore/StoredKeyTests.cpp, tests/interface/TWStoredKeyTests.cpp, wasm/src/keystore/default-impl.ts, wasm/src/keystore/types.ts, wasm/tests/KeyStore+extension.test.ts, wasm/tests/KeyStore+fs.test.ts
fix #2701
Run wasm tests
Run kotlin tests
Run swift tests
=> [Encryption]: add support for aes-256-ctr

include/TrustWalletCore/TWCoinType.h
=> [Swift]: fix warning on public key declaration

Dockerfile, src/Ethereum/EIP2645.cpp
Fixes docker build not working due to changes in cmake and recent addition of rust library (([#2706](https://github.com/trustwallet/wallet-core/pull/2706))
Run the docker build steps.
* Updates libssl in the docker container to 1.1.1 as required per the latest version of cmake that ubuntu installs.
* Installs rustc and cargo, which are required after (([#2706](https://github.com/trustwallet/wallet-core/pull/2706)) was merged in.
=> Updated docker build

trezor-crypto/crypto/sha2.c
archlinux os with clang version 14.0.6 reports error (warning) about 
```
.../trust-wallet-core/trezor-crypto/crypto/sha2.c:592:46: error: argument 2 of type ‘sha2_byte[]’ {aka ‘unsigned char[]’} with mismatched bound [-Werror=array-parameter=]
592 | void sha1_Final(SHA1_CTX* context, sha2_byte digest[]) {
|                                    ~~~~~~~~~~^~~~~~~~
In file included from .../trust-wallet-core/trezor-crypto/crypto/sha2.c:33:
.../trust-wallet-core/trezor-crypto/include/TrezorCrypto/sha2.h:99:28: note: previously declared as ‘uint8_t[20]’ {aka ‘unsigned char[20]’}
99 | void sha1_Final(SHA1_CTX*, uint8_t[SHA1_DIGEST_LENGTH]);
|                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
.../trust-wallet-core/trezor-crypto/crypto/sha2.c:899:50: error: argument 2 of type ‘sha2_byte[]’ …
```
=> Fix array with mismatched bound warnings in sha2.c

codegen/lib/templates/java/class.erb, codegen/lib/templates/java/struct.erb
To avoid open keywork on the doc
Before:
After:
Todo: do the same for the function
Run dokka doc and check
=> [Codegen]: mark java class as final to avoid kt doc confusion

rust/src/encoding/base32.rs, rust/src/encoding/mod.rs, src/Base32.h, src/Base64.cpp
Base32 support in rust without deps and with padding support
=> [Rust/Base32]: Encoding/Decoding support

kotlin/README.md, kotlin/build-logic/src/main/kotlin/convention.proto-generation.gradle.kts, kotlin/wallet-core-kotlin/.gitignore, kotlin/wallet-core-kotlin/build.gradle.kts, tools/kotlin-build, tools/kotlin-release
- Remove :generateCinterop task
- Leave WalletCore.def file empty
- Specify all C interop stuff in build.gradle.kts
=> [Kotlin] Removed :generateCinterop task

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt, android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/TestCoinType.kt, docs/registry.md, include/TrustWalletCore/TWCoinType.h, registry.json, swift/Tests/Blockchains/RippleTests.swift, swift/Tests/CoinAddressDerivationTests.swift, swift/Tests/CoinTypeTests.swift, tests/chains/ThunderToken/TWCoinTypeTests.cpp, tests/common/CoinAddressDerivationTests.cpp, tests/interface/TWCoinTypeTests.cpp, tests/interface/TWHRPTests.cpp
Replace https://github.com/trustwallet/wallet-core/pull/2926, so we have permission to fix mobile tests
=> Update name for ThunderCore

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/filecoin/TestFilecoin.kt, include/TrustWalletCore/TWAnyAddress.h, include/TrustWalletCore/TWFilecoinAddressConverter.h, include/TrustWalletCore/TWFilecoinAddressType.h, src/CoinEntry.h, src/Filecoin/Address.cpp, src/Filecoin/Address.h, src/Filecoin/AddressConverter.cpp, src/Filecoin/AddressConverter.h, src/Filecoin/Entry.cpp, src/Filecoin/Signer.cpp, src/Filecoin/Signer.h, src/Filecoin/Transaction.cpp, src/Filecoin/Transaction.h, src/interface/TWAnyAddress.cpp, src/interface/TWFilecoinAddressConverter.cpp, src/proto/Filecoin.proto, swift/Tests/Blockchains/FilecoinTests.swift, tests/chains/Filecoin/AddressTests.cpp, tests/chains/Filecoin/SignerTests.cpp, tests/chains/Filecoin/TWAddressConverterTests.cpp, tests/chains/Filecoin/TWAnySignerTests.cpp, tests/chains/Filecoin/TransactionTests.cpp, tests/interface/TWAnyAddressTests.cpp
Integrate `f4` address type following the [guideline](https://www.notion.so/Exchange-Integration-Guide-FEVM-Edition-9fe9158360cf423da256b1bb1f47ff26#eb1df3e466cd461788421498feff15e2).
```bash
./tools/build-and-test
./tools/ios-test
./tools/android-test
```
Unlike the `f1`, `f2`, `f3`, the new `f4` address type includes an Actor ID of arbitrary length, and the address payload can also be of arbitrary length.
Thus, I had to significantly refactor `Filecoin::Address`.
=> [Filecoin]: Support new f4 address types

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/cardano/TestCardanoSigning.kt, include/TrustWalletCore/TWCardano.h, src/Cardano/Transaction.cpp, src/Cardano/Transaction.h, src/interface/TWCardano.cpp, src/proto/Cardano.proto, swift/Tests/Blockchains/CardanoTests.swift, tests/chains/Cardano/SigningTests.cpp, tests/chains/Cardano/TransactionTests.cpp
Cardano NFTs are supported in wallet-core. This pull request adds multiple samples (tests) in C++, Kotlin and Swift to explain how to generate and sign an NFT transfer transaction.
This pull request also adds the `TWCardanoOutputMinAdaAmount` FFI that should be used instead of `TWCardanoMinAdaAmount` as it returns a more accurate value for the minimum output amount.
```shell
./tools/build-and-test
./tools/ios-test
./tools/android-test
```
=> [Cardano]: support NFT on Cardano

.dockerignore, .github/workflows/docker.yml, Dockerfile, src/Nebulas/Address.cpp
Reported from @iCell, failed both on CI https://github.com/trustwallet/wallet-core/actions/runs/4383705487 and locally
Changes:
- Replace `git clone` with `COPY`, this should make CI easier to test later
- Move go installation step to comments
How to test locally: `docker build . --platform linux/amd64`
Succeeded on CI: https://github.com/trustwallet/wallet-core/actions/runs/4663344683/jobs/8254583205?pr=3061
=> [Dockerfile] Add missing include

.github/workflows/docker.yml
Backend team is integrating wallet-core to one of their backend project, and they need the Docker image as a basis.
If push commit to `master`, Docker CI will publish the `wallet-core:latest` docker image.
If push new tag (release), Docker CI will publish the `wallet-core:$TAG` docker image.
Changed `.github/workflows/docker.yml` CI workflow.
[Docker CI run](https://github.com/trustwallet/wallet-core/actions/runs/4680852152/jobs/8292718795?pr=3075) has produced and published this docker image: https://gallery.ecr.aws/y4f6g9v9/wallet-core
**Checklist**
=> [Docker]: Push Docker image to TW registry on push to master branch

.github/workflows/kotlin-ci.yml, .github/workflows/kotlin-sample-ci.yml, codegen/lib/kotlin_helper.rb, codegen/lib/templates/kotlin/android_class.erb, codegen/lib/templates/kotlin/android_enum.erb, codegen/lib/templates/kotlin/common_class.erb, codegen/lib/templates/kotlin/common_enum.erb, codegen/lib/templates/kotlin/ios_class.erb, codegen/lib/templates/kotlin/ios_enum.erb, codegen/lib/templates/kotlin/js_accessors_class.erb, codegen/lib/templates/kotlin/js_accessors_enum.erb, codegen/lib/templates/kotlin/js_accessors_struct.erb, codegen/lib/templates/kotlin/js_class.erb, codegen/lib/templates/kotlin/js_enum.erb, kotlin/build-logic/build.gradle.kts, kotlin/build.gradle.kts, kotlin/wallet-core-kotlin/build.gradle.kts, kotlin/wallet-core-kotlin/src/jsMain/kotlin/WalletCore.kt
- Kotlin doesn't have nullable constructors like Swift, so simply throw `IllegalArgumentException` if native constructor returns `null`
- Added `stringValuse` for enums with string value
- Use `interface` instead of `class/object` for safety in JS accessors
- Public getter for `WalletCore.Instance` in JS target
- Switch to Java 17 (new Android Studio requires it)
=> [Kotlin] Nullable constructors throw exception

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/theopennetwork/TestTheOpenNetworkSigner.kt, src/TheOpenNetwork/Address.cpp, src/TheOpenNetwork/Address.h, src/TheOpenNetwork/Signer.cpp, src/proto/TheOpenNetwork.proto, swift/Tests/Blockchains/TheOpenNetworkTests.swift, tests/chains/TheOpenNetwork/SignerTests.cpp, tests/chains/TheOpenNetwork/TWAnySignerTests.cpp, wasm/tests/Blockchain/TheOpenNetwork.test.ts
Bounceable field need to be set manually, wrong branch name, I initially thought it's was for tron - ignore.
Run C++, swift and android unit tests
=> [Ton]: add bounceable field to set it manually

codegen/bin/codegen, tools/generate-files
Opening this regarding: https://github.com/trustwallet/wallet-core/discussions/3166
Imo, given that we're not fully done yet with version 2 (including the processing of `registry.json`), we should just revert `master` to version 1 and not have to tell users to deal with version 2 as of now. The released tags `3.1.33` and `3.1.34` can still be tested and verified regarding the correctness of the Swift codegen-v2 generation.
=> switch back to codegen version 1 for Swift bindings

cmake/Protobuf.cmake
Depending on CMAKE_CURRENT_SOURCE_DIR might cause all sorts of unintended consequences. For instance, this will break configuration when your project is included into another CMake managed project.
Use parent directory of Protobuf.cmake to ensure that CMake configuration process will be deterministic.
Nothing should change from a casual user point of view so there is not much to test actually.
=> Use CMAKE_CURRENT_LIST_DIR

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt, docs/registry.md, include/TrustWalletCore/TWCoinType.h, registry.json, swift/Tests/CoinAddressDerivationTests.swift, tests/chains/Rootstock/TWCoinTypeTests.cpp, tests/common/CoinAddressDerivationTests.cpp
Adds Support for [rootstock](https://rootstock.io/) chain.
Same way as other EVM chains
Checklist
=> Add `rootstock` chain

samples/kmp/shared/build.gradle.kts
=> [kmp]: Fix kmp  by updating WC to 3.1.38

wasm/src/CoinTypeExt.cpp, wasm/src/CoinTypeExt.h, wasm/tests/CoinType.test.ts
`CoinTypeExt` isn't auto-generated, so we should keep it in sync
- Added unit test for `deriveAddressFromPublicKey`
- Added unit test for `deriveAddressFromPublicKeyAndDerivation`
=> [WASM] Fixed CoinType.deriveAddressFromPublicKeyAndDerivation

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt, android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/acala/TestAcalaAddress.kt, android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/acala/TestAcalaSigner.kt, android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/acalaevm/TestAcalaEVMAddress.kt, android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/polkadot/TestPolkadotSigner.kt, docs/registry.md, include/TrustWalletCore/TWCoinType.h, registry.json, src/Polkadot/Entry.cpp, swift/Tests/Blockchains/AcalaEVMTests.swift, swift/Tests/Blockchains/AcalaTests.swift, swift/Tests/CoinAddressDerivationTests.swift, tests/chains/Acala/TWAnyAddressTests.cpp, tests/chains/Acala/TWCoinTypeTests.cpp, tests/chains/AcalaEVM/TWCoinTypeTests.cpp, tests/common/CoinAddressDerivationTests.cpp, tools/install-rust-dependencies, tools/rust-bindgen
Add support for Acala and Acala EVM chains.
Run C++, Swift, Kotlin tests
=> [Acala]: Add Acala and AcalaEVM chains

src/Bitcoin/TransactionBuilder.cpp, src/Bitcoin/TransactionBuilder.h, src/Bitcoin/TransactionPlan.h, src/Decred/TransactionBuilder.h, src/Zen/TransactionBuilder.h, tests/chains/Bitcoin/TWBitcoinSigningTests.cpp, tests/chains/Bitcoin/TxComparisonHelper.cpp, tests/chains/Zen/TransactionBuilderTests.cpp
We inherited a bug https://github.com/trustwallet/wallet-core/issues/3273 from the DeFi wallet during https://github.com/trustwallet/wallet-core/pull/3225
This PR fixes the issue.
Please note that `use_max_amount = true` will lead to an error if [SigningInput::extra_outputs](https://github.com/trustwallet/wallet-core/blob/master/src/proto/Bitcoin.proto#L144) is not empty.
Run C++ tests
=> [Bitcoin]: Fix `TWAnySignerPlan` if `use_max_amount = true`

src/Polkadot/Extrinsic.cpp, src/Polkadot/Extrinsic.h, src/proto/Polkadot.proto, tests/chains/Polkadot/SignerTests.cpp
Don't set `controller` in `Staking::Bond` since `9430` runtime version.
Run C++ tests
`Bond::controller` is automatically ignored if `spec_version >= 9430` (for Kusama and Polkadot chains **only**) as the parameter was removed from the call.
Also `Bond::controller` can be omitted manually for custom Polkadot chains.
=> [Polkadot]: Fix `Staking::Bond` and `Staking::BondAndNominate`

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/aptos/TestAptosSigner.kt, src/Aptos/Signer.cpp, src/proto/Aptos.proto, tests/chains/Aptos/SignerTests.cpp
Add the ability to transfer tokens even if the recipient has not registered them yet by using `0x1::aptos_account::transfer_coins`.
Run C++, Kotlin tests
Add `TokenTransferCoinsMessage` similar to `TokenTransferMessage`.
=> [Aptos]: Add `transfer_coins` function call

rust/tw_encoding/src/hex.rs, rust/tw_evm/src/message/eip712/eip712_message.rs, rust/tw_evm/tests/data/eip712_fixed_bytes.json, rust/tw_evm/tests/message_signer.rs
Fix EIP712 message hashing when fixed byte array is `0x0`.
Run Rust tests
Allow passing `0x0`, `0` values to be passed as `bytes32`.
=> [Eth]: Fix EIP712 message hashing when fixed byte array is `0x0`

.github/workflows/android-ci.yml, .github/workflows/codegen-v2.yml, .github/workflows/docker.yml, .github/workflows/ios-ci.yml, .github/workflows/kotlin-ci.yml, .github/workflows/kotlin-sample-ci.yml, .github/workflows/linux-ci-rust.yml, .github/workflows/linux-ci-sonarcloud.yml, .github/workflows/linux-ci.yml, .github/workflows/linux-sampleapp-ci.yml, .github/workflows/wasm-ci.yml, src/THORChain/Swap.cpp, tests/chains/Cosmos/THORChain/SwapTests.cpp
Fix ETH memo for ->BSC swap.
Same as https://github.com/trustwallet/wallet-core/pull/3548, but targets 3.3.x
Run C++ tests
=> [Swap]: Fix BSC swap

rust/tw_evm/src/message/eip712/eip712_message.rs, rust/tw_evm/tests/data/eip712_different_bytes.json, rust/tw_evm/tests/data/eip712_long_bytes.json, rust/tw_evm/tests/message_signer.rs, rust/tw_misc/src/lib.rs, samples/kmp/shared/build.gradle.kts
This PR fixes a bug with hashing `bytes` properties in EIP712.
At this moment, any `bytes` value will be hashed and then serialized with a two length prefixes that is incorrect.
As the result, the output EIP712 message signature is invalid.
For example, there is a byte array `0xcb5a7173d109f8a59c23109189056c862d843808d00bac069e9b76ca7217d845a94d0ad600000000000000000000000000000000000000000000000000000000000000a07c1a7062fbf633885ae02e0919ec07020a96aa20bf9c79554d2ddcd013113c64579837cd54cb5f05c65c46c04fac9abe54f839a74fa3cc1c47fc9048db037a84000000000000000000000000000000000000000000000000000000000000001b0000000000000000000000000000000000000000000000000000000000000035697066733a2f2f516d61414e35575832525851385852374b5158475a6f726931517461597972356e3547537471456a71706a4e71640000000000000000000000` …
=> [Eth/Eip712]: Fix `bytes` hashing

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/solana/TestSolanaWalletConnectSigning.kt, rust/chains/tw_solana/Cargo.toml, rust/chains/tw_solana/src/blockhash.rs, rust/chains/tw_solana/src/compiler.rs, rust/chains/tw_solana/src/entry.rs, rust/chains/tw_solana/src/modules/message_builder.rs, rust/chains/tw_solana/src/modules/mod.rs, rust/chains/tw_solana/src/modules/proto_builder.rs, rust/chains/tw_solana/src/modules/utils.rs, rust/chains/tw_solana/src/modules/wallet_connect/connector.rs, rust/chains/tw_solana/src/modules/wallet_connect/mod.rs, rust/chains/tw_solana/src/modules/wallet_connect/request.rs, rust/chains/tw_solana/src/signer.rs, rust/chains/tw_solana/src/transaction/mod.rs, rust/tw_any_coin/tests/chains/solana/mod.rs, rust/tw_any_coin/tests/chains/solana/solana_transaction.rs, rust/tw_any_coin/tests/chains/solana/solana_wallet_connect.rs, rust/tw_encoding/src/base58.rs, rust/tw_encoding/src/base64.rs, src/proto/Solana.proto, src/proto/WalletConnect.proto, swift/Tests/Blockchains/SolanaTests.swift, tests/chains/Solana/TWSolanaTransaction.cpp, tests/chains/Solana/TWWalletConnectSolana.cpp
1. Parse the received signing request by using `WalletConnectRequest.parse` method.
2. Adjust fee, add a `privateKey` to the result `Proto::SigningInput` message.
3. Generate and sign a transaction by using `AnySigner.sign` method.
4. Generate a WalletConnect JSON response with the result signature.
Run Rust, C++, Android, iOS tests
=> [WalletConnect/Solana]: Add support for WalletConnect signing requests

src/Bitcoin/SigningInput.cpp, src/Bitcoin/SigningInput.h, src/Bitcoin/TransactionBuilder.cpp, src/Bitcoin/TransactionBuilder.h, src/Bitcoin/TransactionPlan.h, src/Zen/TransactionBuilder.h, src/proto/Bitcoin.proto, tests/chains/Bitcoin/TWBitcoinSigningTests.cpp, tests/chains/Bitcoin/TransactionPlanTests.cpp
This PR introduces a `Proto::SigningInput::output_op_return_index` - an index of the OP_RETURN output in the transaction outputs list.
Currently, OP_RETURN is placed as the latest transaction output (after the P2WPKH and change outputs).
However, to interact with zEVM, OP_RETURN has to be the second output (after P2WPKH and before change outputs).
Documentation: https://www.zetachain.com/docs/developers/omnichain/bitcoin/#example-1-deposit-btc-into-an-account-in-zevm
Run C++ tests
=> [ZetaChain]: Deposit BTC and call a smart contract in zEVM

codegen-v2/src/codegen/template_generator.rs, codegen-v2/src/registry.rs
Fix issue #3724: The generated files of EVM-compatible chain cannot pass test
Root cause:
There is no field displayName in struct CoinInfo, the generated file ./src/Generated/CoinInfoData.cpp use `displayName` (if it exists in registry.json) as `name` in CoinInfo, but the generated test file tests/chains/XXXXX/TWCoinTypeTests.cpp always use `name` in registry.json.
Resolution:
In file tests/chains/XXXXX/TWCoinTypeTests.cpp, use `displayName` if it exists in registry.json, otherwise use `name`.
=> Fix issue #3724: The generated files of EVM-compatible chain cannot pass test

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt, kotlin/wallet-core-kotlin/src/commonTest/kotlin/com/trustwallet/core/test/CoinAddressDerivationTests.kt, registry.json, swift/Tests/CoinAddressDerivationTests.swift
Update derivation path from `m/44'/223'/1'/0/0` to `m/44'/223'/0'/0/0` for `InternetComputer` to be compatible with other wallets.
=> [ICP]: Update derivation path to be compatible with other wallets

rust/chains/tw_binance/src/transaction/message/mod.rs, rust/chains/tw_binance/src/transaction/message/side_chain_delegate.rs, rust/tw_any_coin/tests/chains/binance/binance_sign.rs, rust/tw_any_coin/tests/chains/binance/mod.rs, rust/tw_evm/src/address.rs, src/proto/Binance.proto
Add `cosmos-sdk/MsgSideChainStakeMigration` message type to allow BNB Beacon Chain users to migrate their stake amounts on Binance Smart Chain in one transaction.
https://github.com/bnb-chain/bnc-cosmos-sdk/blob/master/x/stake/types/stake_migration.go#L29-L35
Additional info
JS SDK sample : https://github.com/bnb-chain/javascript-sdk/pull/408/files
Run Rust tests
=> [Binance]: Add `cosmos-sdk/MsgSideChainStakeMigration` message type

src/FIO/Action.cpp, src/FIO/Action.h, src/FIO/Signer.cpp, src/FIO/TransactionBuilder.cpp, src/FIO/TransactionBuilder.h, src/proto/FIO.proto, tests/chains/FIO/SignerTests.cpp, tests/chains/FIO/TWFIOTests.cpp, tests/chains/FIO/TransactionBuilderTests.cpp, tests/chains/FIO/TransactionCompilerTests.cpp
Currently, WC does not support removing address action for FIO blockchain.
Sample from the SDK
https://github.com/fioprotocol/fiosdk_typescript-examples/blob/f4eacd0b7f279f74a1787385a1dc96a4f7c7d9e4/fio.address-remaddress.js#L19
Endpoint to broadcast
https://dev.fio.net/reference/remove_pub_address
Run C++ tests
* Add `Proto::Action::RemovePubAddress` message type.
* Add `Proto::SigningOutput::action_name` field to make the WalletKit easier to broadcast transactions.
=> feat(FIO): Add support for "remaddress" action type

src/FIO/Action.cpp, src/FIO/Action.h, src/FIO/TransactionBuilder.cpp, src/FIO/TransactionBuilder.h, src/proto/FIO.proto, tests/chains/FIO/TWFIOTests.cpp
Add support for `addbundles` and `remalladdr` actions.
Run C++ tests
=> feat(fio): Add support for `addbundles` and `remalladdr` actions

swift/PrivacyInfo.xcprivacy
Add Privacy Manifest file with the [required reason API](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api) used in WalletCore on iOS.
API documented:
* mach_absolute_time (System Boot Time API) - 35F9.1
> Declare this reason to access the system boot time in order to measure the amount of time that has elapsed between events that occurred within the app or to perform calculations to enable timers.
* fstat, lstat (Disk Space API) - 85F4.1
> Declare this reason to display disk space information to the person using the device. Disk space may be displayed in units of information (such as bytes) or units of time combined with a media type (such as minutes of HD video).
Information accessed for this reason, or any derived …
=> [iOS]: Add Privacy Manifest file

src/Coin.cpp, tests/chains/Aeternity/AddressTests.cpp, tests/chains/Aeternity/TWAnyAddressTests.cpp
`AnyAddress.isValid` throws an exception for Aeternity coin when using FIO handles.
We should catch all exceptions and return false in case of using invalid addresses.
Run C++ tests
Add try-catch blocks to `TWAnyAddressIsValid`, `TWAnyAddressIsValidBech32` and `TWAnyAddressIsValidSS58`
=> [Aeternity]: Catch all exceptions on `TWAnyAddressIsValid`

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/ethereum/TestEthereumMessageSigner.kt, rust/tw_evm/src/message/eip191.rs, rust/tw_evm/tests/message_signer.rs
Fixes https://github.com/trustwallet/wallet-core/issues/3831
Run Rust, Android tests
=> [Ethereum]: Properly handle hex encoded EIP-191 messages

registry.json, tests/chains/Algorand/SignerTests.cpp, tests/chains/Algorand/TWAnySignerTests.cpp, tests/chains/Algorand/TWCoinTypeTests.cpp
**Context**
https://app.shortcut.com/trust-wallet-1/story/6263/update-the-algorand-explorer
Change Algorand explorer to https://app.dappflow.org/explorer
**Note**: For comments with testnet, used instead https://explorer.bitquery.io/algorand_testnet , as app.dappflow.org testnet node is not reflected on URL
=> [Algorand]: Update explorer for Tx and Account

.github/workflows/linux-ci-rust.yml, rust/Cargo.lock, rust/Cargo.toml, rust/tw_coin_registry/src/registry.rs, rust/wallet_core_bin/Cargo.toml, rust/wallet_core_bin/src/main.rs, rust/wallet_core_bin/src/registry_stats.rs, tools/registry, tools/rust-bindgen, tools/rust-coverage, tools/rust-test
* Add `registry-stats` command to get the Rust transition statistic
Run `tools/registry registry-stats`
Add `wallet_core_bin` crate that will have some useful commands
=> [Misc]: Add WalletCore binary binary tools

src/Polkadot/Extrinsic.cpp, tests/chains/Polkadot/ExtrinsicTests.cpp, tools/install-sys-dependencies-linux
=> Update Polkadot extrinsic encoding to support spec 1002005

registry.json, tests/chains/TheOpenNetwork/SignerTests.cpp, tests/chains/TheOpenNetwork/TWCoinTypeTests.cpp
- Enable Ton Viewer explorer
- http://tonscan.org/ does not seem to work anymore, and .com is a different one with not the same experience 
- In addition, ton viewer is commonly used in the ecosystem by other wallets such as TonKeeper. Also it provides a lot of more details with transaction graph. Ex: https://tonviewer.com/transaction/6011722bfa45389cfe980661b4290690a19dc8add270ac512d7636bbd41efe82
@satoshiotomakan feel free to close this branch and merge it to yours
=> [TON]: Enable Ton Viewer explorer

include/TrustWalletCore/TWStoredKey.h, src/Keystore/StoredKey.cpp, src/Keystore/StoredKey.h, src/interface/TWStoredKey.cpp, tests/interface/TWStoredKeyTests.cpp
We can use stored account public key to re-derive account address. No need to require a password to decrypt wallet/privateKey.
Run C++ tests
Remove `TWData* password` parameter from the `TWStoredKeyUpdateAddress` function
=> [TON]: Do not require password at `TWStoredKeyUpdateAddress`

src/MultiversX/Transaction.h, src/MultiversX/TransactionFactoryConfig.h
Newer versions of the C++ standard library (both LLVM's `libc++` and GNU's `libstdc++` excluded `cstdint` inclusion on `string`, breaking compilations of the project.
This PR adds `cstdint` inclusion manually to the affected files.
=> fix(MultiversX): Added `cstdint` to headers

trezor-crypto/CMakeLists.txt
The [`_Static_assert` requires C11](https://en.cppreference.com/w/c/language/_Static_assert), which is not correctly set on CMake.
=> Fix TrezorCrypto CMake build

android/app/src/androidTest/java/com/trustwallet/core/app/utils/TestCryptoBox.kt, include/TrustWalletCore/TWCryptoBoxSecretKey.h, rust/tw_keypair/src/ffi/crypto_box/secret_key.rs, rust/tw_keypair/src/nacl_crypto_box/secret_key.rs, rust/tw_keypair/tests/crypto_box_ffi_tests.rs, src/CryptoBox.cpp, src/CryptoBox.h, src/interface/TWCryptoBoxSecretKey.cpp, swift/Tests/CryptoBoxTests.swift, tests/interface/TWCryptoBoxTests.cpp
Add `CryptoBoxSecretKey.isValid(Data)`, `CryptoBoxSecretKey(Data)`, `CryptoBoxSecretKey.data()`
Run Rust, iOS, Android, C++ tests
=> [TON]: Add `CryptoBoxSecretKey` FFIs to create from Bytes, get Bytes

android/app/src/androidTest/java/com/trustwallet/core/app/utils/TestLiquidStaking.kt, docs/registry.md, registry.json, src/proto/LiquidStaking.proto, swift/Tests/LiquidStakingTests.swift, tests/chains/Polygon/TWCoinTypeTests.cpp, tests/common/LiquidStaking/LiquidStakingTests.cpp
https://polygon.technology/blog/save-the-date-matic-pol-migration-coming-september-4th-everything-you-need-to-know
=> feat(Polygon): MATIC to POL rebranding

include/TrustWalletCore/TWSolanaAddress.h, rust/chains/tw_solana/src/program/stake_program.rs, rust/chains/tw_solana/tests/get_default_token_address.rs, rust/wallet_core_rs/src/ffi/solana/address.rs, rust/wallet_core_rs/tests/solana/solana_address.rs, src/interface/TWSolanaAddress.cpp, tests/chains/Solana/TWSolanaAddressTests.cpp
There is a function to generate token addresses for the Token Program, but no function for generating token addresses for the Token-2022 Program. I added a support function to address this.
Run Rust, C++, Kotlin, Swift tests
=> [Solana]: Add a function for generating token addresses for the Token-2022 Program

bootstrap.sh, tools/generate-files, tools/install-sys-dependencies-mac, tools/parse_args, tools/rust-bindgen
Configure `bootstrap.sh` so it installs all dependencies required for development and using of WalletCore.
Improve existing build scripts by better parsing command line arguments.
For example, `./tools/generate-files` and `./tools/rust-bindgen` now support multiple targets at once.
=> [Misc]: Improve build scripts, configure bootstrap.sh

src/Keystore/EncryptionParameters.h, src/Keystore/ScryptParameters.cpp, src/Keystore/ScryptParameters.h, tests/common/Keystore/StoredKeyTests.cpp
Starting from Nov 23, 2021 at https://github.com/trustwallet/wallet-core/commit/e11018827441c496bed0153ea8fa183558aa5a4b, WalletCore always uses empty salt for PrivateKey/Mnemonic encryption.
This PR changes the behaviour to always generate random salt on creating/importing new wallets.
Run C++, iOS, Android tests
* Remove `ScryptEncryption::Minimal`, `ScryptEncryption::Weak`, `ScryptEncryption::Standard` constants
* Add `ScryptEncryption::minimal()`, `ScryptEncryption::weak()`, `ScryptEncryption::standard()` constructors that always generate random salt
=> [Security]: Generate random salt when creating/importing new wallet

.gitignore, android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/TestCoinType.kt, android/app/src/androidTest/java/com/trustwallet/core/app/utils/TestAnyAddress.kt, android/app/src/androidTest/java/com/trustwallet/core/app/utils/TestHDWallet.kt, codegen/bin/coins, codegen/lib/coin_skeleton_gen.rb, codegen/lib/derivation.rb, codegen/lib/file_editor.rb, include/TrustWalletCore/TWDerivation.h, include/TrustWalletCore/TWPurpose.h, registry.json, rust/frameworks/tw_utxo/src/address/derivation.rs, rust/frameworks/tw_utxo/src/address/standard_bitcoin.rs, rust/tw_any_coin/src/test_utils/address_utils.rs, rust/tw_coin_entry/src/derivation.rs, rust/tw_coin_registry/src/tw_derivation.rs, rust/tw_tests/tests/chains/bitcoin/bitcoin_address.rs, src/Bitcoin/Entry.cpp, src/Bitcoin/Entry.h, swift/Tests/AnyAddressTests.swift, swift/Tests/CoinTypeTests.swift, swift/Tests/HDWalletTests.swift, swift/Tests/Keystore/KeyStoreTests.swift, tests/chains/Bitcoin/TWAnyAddressTests.cpp, tests/chains/Bitcoin/TWBitcoinSigningTests.cpp, tests/common/Keystore/DerivationPathTests.cpp, tests/interface/TWHDWalletTests.cpp, tests/interface/TWStoredKeyTests.cpp
This PR adds support for P2TR key-path address generation through.
Please note that by default (`TWDerivationDefault`) is a Native Segwit (P2WPKH).
To generate P2TR address, specify `TWDerivationBitcoinTaproot`.
For example,
```kt
val wallet = HDWallet(words, password)
val address = wallet.getAddressDerivation(CoinType.BITCOIN, Derivation.BITCOINTAPROOT)
assertEquals(address, "bc1pgqks0cynn93ymve4x0jq3u7hne77908nlysp289hc44yc4cmy0hslyckrz")
```
* Refactored `codegen` tool, so new derivations added to registry.json are now appended to the end of the  `TWDerivation` enum on each `./tools/generate-files` command. This is required to avoid changing the order of existing derivations.
=> [Bitcoin]: Add support for Taproot address generation

bootstrap.sh
./bootstrap.sh: line 19: tools/install-sys-dependencies-macos: No such file or directory
Correct name **install-sys-dependencies-mac**
On macOs
_Call_
`./bootstrap.sh all`
=> fixed bootstrap.sh for macOS

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/solana/TestSolanaTransaction.kt, include/TrustWalletCore/TWSolanaTransaction.h, rust/chains/tw_solana/src/modules/compiled_keys.rs, rust/chains/tw_solana/src/modules/insert_instruction.rs, rust/chains/tw_solana/src/modules/instruction_builder/compute_budget_instruction.rs, rust/chains/tw_solana/src/modules/instruction_builder/system_instruction.rs, rust/chains/tw_solana/src/modules/message_decompiler.rs, rust/chains/tw_solana/src/modules/mod.rs, rust/chains/tw_solana/src/modules/utils.rs, rust/chains/tw_solana/src/transaction/legacy.rs, rust/chains/tw_solana/src/transaction/v0.rs, rust/chains/tw_solana/src/transaction/versioned.rs, rust/tw_tests/tests/chains/solana/solana_transaction_ffi.rs, rust/wallet_core_rs/src/ffi/solana/transaction.rs, src/interface/TWSolanaTransaction.cpp, swift/Tests/Blockchains/SolanaTests.swift, tests/chains/Solana/TWSolanaTransaction.cpp
We want to be able to update `ComputeBudgetInstruction::SetComputeUnitPrice` and `ComputeBudgetInstruction::SetComputeUnitLimit` instructions for every transaction goes through Trust Wallet including Swap transactions.
Context: Rango (later Amber), Jupiter and most of the providers return a serialized transaction to sign and broadcast.
Solution: We should be able to deserialize the given raw transaction, add or update `ComputeBudgetInstruction::SetComputeUnitPrice` and `ComputeBudgetInstruction::SetComputeUnitLimit` instructions, compile the transaction again, and sign it.
Run Rust, C++, iOS, Android tests
* SolanaTransaction.getComputeUnitLimit(encodedTransaction: String) -> String?, where:
* encodedTransaction - base64 encoded transaction
* return - optional Unit Limit as a decimal …
=> [Solana]: Add utils to get/set compute unit price/limit

rust/tw_memory/src/ffi/tw_string.rs, src/Cardano/Transaction.cpp, src/Cardano/Transaction.h, src/Data.h, tests/chains/Cardano/SigningTests.cpp, tests/chains/Cardano/TransactionTests.cpp
Fixes https://github.com/trustwallet/wallet-core/issues/3969
Run C++ tests
Treats `assetName` as a byte array by default.
=> [Cardano]: Check if `assetName` is a UTF-8 string

codegen/lib/templates/java/class.erb, jni/java/wallet/core/java/GenericPhantomReference.java, kotlin/wallet-core-kotlin/src/commonAndroidJvmMain/kotlin/com/trustwallet/core/WalletCoreLibLoader.kt
Add missing `GenericPhantomReference.java` class.
Run Native Android tests
=> [Chore]: Fix Android bindings

src/Tron/Protobuf/TronInternal.proto, src/Tron/Serialization.cpp, src/Tron/Signer.cpp, src/proto/Tron.proto, tests/chains/Tron/SignerTests.cpp
Add transaction memo to the TRON transaction builder.
Run C++ tests
Add `Proto::Tron::Transaction::memo` protobuf parameter.
=> [TRON]: Add transaction memo

rust/chains/tw_bitcoincash/src/context.rs, rust/chains/tw_bitcoincash/src/entry.rs, rust/tw_tests/tests/chains/bitcoincash/bitcoincash_sign.rs, rust/tw_tests/tests/chains/solana/solana_transaction_ffi.rs, tests/chains/BitcoinCash/TWBitcoinCashTests.cpp
This PR fixes `AnySigner.plan()` for BitcoinCash through BitcoinV2 protocol.
Run Rust tests
Fix `tw_bitcoincash::Entry`
=> [BCH]: Fix Transaction Planning

registry.json, tests/chains/Callisto/TWCoinTypeTests.cpp
The old one stopped working
https://explorer.callisto.network
->
https://explorer.callistodao.org
=> Update Callisto explorer

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/solana/TestSolanaMessageSigner.kt, include/TrustWalletCore/TWMessageSigner.h, rust/Cargo.lock, rust/chains/tw_solana/Cargo.toml, rust/chains/tw_solana/src/entry.rs, rust/chains/tw_solana/src/modules/mod.rs, rust/chains/tw_solana/src/modules/offchain_message_signer.rs, rust/tw_any_coin/src/ffi/tw_message_signer.rs, rust/tw_tests/tests/chains/ethereum/ethereum_message_sign.rs, rust/tw_tests/tests/chains/solana/mod.rs, rust/tw_tests/tests/chains/solana/solana_message_sign.rs, src/Ethereum/MessageSigner.cpp, src/interface/TWMessageSigner.cpp, src/proto/Solana.proto, swift/Tests/Blockchains/SolanaTests.swift, tests/chains/Solana/SolanaMessageSigner.cpp
https://solana.com/developers/cookbook/wallets/sign-message
Run Rust, C++, iOS, Android tests
Add `TWMessageSignerSign` and `TWMessageSignerVerify` - generic functions to sign messages for any blockchain
=> [Solana]: Add Solana custom message signing

src/Polkadot/Extrinsic.cpp, src/proto/Polkadot.proto, tests/chains/Polkadot/SignerTests.cpp
The Polkadot protobuf was missing custom call indices to support batch calls `BondAndNominate` and `ChillAndUnbond`, the messages only had custom call indices for the top-level batch call.  If a Substrate chain needs to use custom call indices for the batch, then it would also need them for bond, nominate, chill and unbond calls inside the batch.
* Fix Custom call indices support in Polkadot messages `BondAndNominate` and `ChillAndUnbond`.
=> Fix custom call indice support in BondAndNominate and ChillAndUnbond batches

rust/tw_keypair/src/ed25519/keypair.rs, rust/tw_keypair/src/ed25519/modifications/cardano/extended_keypair.rs, rust/tw_keypair/src/ed25519/modifications/cardano/extended_private.rs, rust/tw_keypair/src/ed25519/private.rs, rust/tw_keypair/src/ed25519/secret.rs
The function sign_with_pubkey used in tw_keypair/src/ed25519 is vulnerable to Chalkias attack, this vulnerability allows an attacker to use the signing function with arbitrary public keys leading to the extraction of the private key.
This PR makes `ExpandedSecretKey::sign_with_pubkey` unsafe to require maintainers to pay extra attention when using it.
Ref: https://github.com/trustwallet/wallet-core/security/advisories/GHSA-7g72-jxww-q9vq
=> [Security]: Rename `ExpandedSecretKey::sign_with_pubkey` to `dangerous_sign_with_pubkey`

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/solana/TestSolanaTransaction.kt, include/TrustWalletCore/TWSolanaTransaction.h, rust/chains/tw_solana/src/modules/insert_instruction.rs, rust/chains/tw_solana/src/modules/utils.rs, rust/tw_tests/tests/chains/solana/solana_transaction_ffi.rs, rust/wallet_core_rs/src/ffi/solana/transaction.rs, src/interface/TWSolanaTransaction.cpp, swift/Tests/Blockchains/SolanaTests.swift, tests/chains/Solana/TWSolanaTransaction.cpp
Fix issue https://github.com/trustwallet/wallet-core/issues/4114
Run Rust, C++, iOS, Android tests
=> [Solana]: Support specifying fee payer for an encoded transaction

rust/tw_cosmos_sdk/src/modules/compiler/tw_compiler.rs, rust/tw_cosmos_sdk/src/modules/tx_builder.rs, rust/tw_cosmos_sdk/tests/sign.rs, src/proto/Cosmos.proto
Add ability to sign direct with `TxBody` bytes only.
In other words, generate `AuthInfo` from `SigningInput` parameters if `SignDirect.auth_info_bytes` not provided.
Run Rust tests
=> [Cosmos]: Add ability to sign direct with `TxBody` bytes only

include/TrustWalletCore/TWCardano.h
The TWCardano.h header file does not import TWPublicKey.h. When I generate the dart language bindings, the correct type is not matched.
I don't think this needs testing since the import is obviously missing. But maybe you can test it in [wallet_core_bindings](https://github.com/xuelongqy/wallet_core_bindings).
```shell
cd wallet_core_bindings_native
dart run ffigen
```
=> TWCardano.h header file includes TWPublicKey.h

include/TrustWalletCore/TWMessageSigner.h, rust/chains/tw_sui/Cargo.toml, rust/chains/tw_sui/src/entry.rs, rust/chains/tw_sui/src/modules/intent.rs, rust/chains/tw_sui/src/modules/message_signer.rs, rust/chains/tw_sui/src/modules/mod.rs, rust/chains/tw_sui/src/modules/tx_signer.rs, rust/chains/tw_sui/src/signature.rs, rust/tw_cosmos_sdk/tests/sign.rs, rust/tw_tests/tests/chains/sui/mod.rs, rust/tw_tests/tests/chains/sui/sui_message_sign.rs, src/interface/TWMessageSigner.cpp, src/proto/Sui.proto, tests/chains/Sui/MessageSignerTests.cpp
Support Sui SignPersonalMessage, see: https://sdk.mystenlabs.com/dapp-kit/wallet-hooks/useSignPersonalMessage
Run Rust, C++, iOS, Android tests
=> [Sui]: Support Sui sign personal message

rust/tw_macros/src/tw_ffi.rs
In some CI builds, it seems that the binding yaml file exists but is empty. This PR ensures that the macro handles an invalid file.
CI builds should work
=> Cleanup yaml file if its invalid

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/multiversx/TestMultiversXSigner.kt, src/MultiversX/Serialization.cpp, src/MultiversX/Transaction.cpp, src/MultiversX/Transaction.h, src/MultiversX/TransactionFactory.cpp, src/MultiversX/TransactionFactory.h, src/MultiversX/TransactionFactoryConfig.cpp, src/MultiversX/TransactionFactoryConfig.h, src/proto/MultiversX.proto, swift/Tests/Blockchains/MultiversXTests.swift, tests/chains/MultiversX/SerializationTests.cpp, tests/chains/MultiversX/SignerTests.cpp, tests/chains/MultiversX/TransactionFactoryTests.cpp
This PR brings some support for crafting _relayed_ transactions. The so-called _relayed_ transactions are transactions where the fee is paid by a _relayer_ account (instead of being paid by the _sender_).
Applications that use _wallet-core_ to create & sign transactions can benefit from these changes to support the use case of relayed transactions (e.g. this use case will be supported in _xPortal_).
- The `Transaction` object has been extended to include a new field, called `relayer`.
- The `Serialization` logic has been adjusted to include the the new `relayer` field.
- If one creates a relayed transaction using the transfers-specific methods of the transactions factory, gas limit computation properly handles the extra gas limit needed for such transactions.
- Unit tests have been …
=> [MultiversX]: Add support for relayed (V3) transactions

.gitignore, CMakeLists.txt, codegen-v2/src/codegen/cpp/code_gen.rs, codegen/bin/codegen, kotlin/wallet-core-kotlin/build.gradle.kts, tests/chains/TheOpenNetwork/TWTONAddressConverterTests.cpp
This PR changes the automatic FFI generation to save the created header file in `include/TrustWalletCore`. This ensures that  the downstream packages are able to find the headers correctly.
The existing tests continue to work.
=> Fixes ios package issue with auto-generated C++ header files

src/Cardano/AddressV3.cpp, src/Cardano/AddressV3.h, src/Cardano/Signer.cpp, src/Cardano/Transaction.cpp, src/Cardano/Transaction.h, src/Cbor.cpp, src/Cbor.h, src/proto/Cardano.proto, tests/chains/Cardano/VoteDelegationTests.cpp
This PR adds support for vote delegation in Cardano. 
There are three possible scenarios:
1. A delegation to a valid drep address which requires a `drep_id` to be present
2. Always abstain
3. Always vote as no confidence
Added VoteDelegationTests that compare the transaction id, encoded data and decoded string. The corresponding transactions have been submitted on Cardano mainnet and can be verified on the explorer.
=> [Cardano]: Adds support for vote delegation

wasm/src/keystore/default-impl.ts, wasm/src/keystore/types.ts, wasm/tests/KeyStore.test.ts
This PR fixes `KeyStore.getKey` and `KeyStore.export` for wasm to allow the browser extension to import a wallet with a private key.
Added wasm tests
Bug fix (non-breaking change which fixes an issue) 
=> Allows extension to import a wallet with private key

rust/chains/tw_ripple/src/modules/protobuf_builder.rs, rust/tw_tests/tests/chains/ripple/ripple_sign.rs, src/proto/Ripple.proto
Some parameters were changed from int64 to uint32 during the recent XRP Rust migration. However `protoc` generates Kotlin bindings with using signed integers only, so overflow happens on Kotlin side
* Ripple.OperationPayment.destinationTag is now uint64
* Ripple.OperationEscrowCreate.destinationTag is now uint64
* Ripple.OperationEscrowCreate.cancelAfter is now uint64
* Ripple.OperationEscrowCreate.finishAfter is now uint64
* Ripple.SigningInput.flags is now uint64
* Ripple.SigningInput.sourceTag is now uint64
=> fix(xrp): Fix Ripple.proto Kotlin compatibility

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/tron/TestTronMessageSigner.kt, src/Tron/MessageSigner.cpp, src/Tron/MessageSigner.h, swift/Tests/Blockchains/TronTests.swift, tests/chains/Tron/TronMessageSignerTests.cpp
Fixes #4325
- Use message length instead of constant number.
- Added new test case with different message length
Tests included. Signing a Tron message and verifying the address is recoverable
- Bug fix
=> fix: tron message signing

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/ethereum/TestBarz.kt, include/TrustWalletCore/TWBarz.h, src/Ethereum/Barz.cpp, src/Ethereum/Barz.h, src/interface/TWBarz.cpp, tests/chains/Ethereum/BarzTests.cpp
This pull request introduces changes to the `Barz` class and its associated functions to support the new Biz Smart Contract. The changes include updates to method parameters to accommodate the new contract details.
* [`src/Ethereum/Barz.cpp`](diffhunk://#diff-0061bf7a31d5f2372381bc2128be2aeab09a044bea01899e73a141c447735906L285-R316): Modified the `getEncodedHash` method to include new parameters `codeAddress`, `codeName`, `codeVersion`, `sender`, and `userOpHash`. Updated the logic to handle these new parameters.
* [`include/TrustWalletCore/TWBarz.h`](diffhunk://#diff-18502d5d4f0e30d0d90071d54016cf9f6473736174068176b06f4af84b9776d8L81-R99): Updated the `TWBarzGetEncodedHash` method signature to include new parameters related to the Biz Smart Contract.
Run C++, Android tests
If you're …
=> feat(biz): Adjust `Barz.getEncodedHash` according to the latest changes in Biz contract

rust/tw_evm/src/transaction/user_operation_v0_7.rs
Makes factory and paymaster optional while serialising UserOpV07
Existing tests continue to work
=> [ETH]: Makes factory and paymaster optional while serialising UserOpV07

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/TestCoinType.kt, android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/pactus/TestPactusAddress.kt, android/app/src/androidTest/java/com/trustwallet/core/app/utils/TestHDWallet.kt, codegen-v2/manifest/TWDerivation.yaml, include/TrustWalletCore/TWDerivation.h, registry.json, rust/chains/tw_pactus/src/entry.rs, rust/chains/tw_pactus/src/types/address.rs, rust/chains/tw_pactus/src/types/mod.rs, rust/chains/tw_pactus/src/types/network.rs, rust/chains/tw_pactus/src/types/validator_public_key.rs, rust/tw_coin_registry/src/tw_derivation.rs, swift/Tests/CoinTypeTests.swift, swift/Tests/HDWalletTests.swift, swift/Tests/Keystore/KeyStoreTests.swift, tests/chains/Pactus/WalletTests.cpp, tests/common/Keystore/DerivationPathTests.cpp, tests/common/Keystore/StoredKeyTests.cpp, tests/interface/TWAnyAddressTests.cpp, tests/interface/TWCoinTypeTests.cpp, wasm/tests/CoinType.test.ts
This PR adds support for **Pactus Testnet addresses**. The HRP for Pactus Testnet address strings is set to `tpc1`, and the coin type is defined as `21777`.
**Please note that all addresses and derived data have been manually compared with BIP-39 and the Pactus Native wallet to ensure correctness.**
Test cases for address derivation and address-to-string conversion are included in this PR.
This PR adds a new derivation path for Pactus to support Testnet addresses.
=> feat(pactus): support testnet address derivation

src/Tron/Entry.cpp, src/Tron/Signer.cpp, src/Tron/Signer.h, src/proto/Tron.proto, tests/chains/Tron/SignerTests.cpp, tests/chains/Tron/TransactionCompilerTests.cpp
Support compiling tron raw json from DApp.
=> Support compiling tron raw json from DApp

codegen/lib/templates/jni/parameter_access.erb, codegen/lib/templates/kotlin_jni/parameter_access.erb, jni/android/AnySigner.c, jni/cpp/TWJNI.h, jni/kotlin/AnySigner.c
Fix issue https://github.com/trustwallet/wallet-core/issues/4442
Bug fix (non-breaking change)
=> Throw exception rather than SIGSEGV

rust/chains/tw_solana/src/modules/message_builder.rs, rust/tw_tests/tests/chains/solana/solana_sign.rs, src/proto/Solana.proto
This PR allows the transfer of tokens to the feepayer to compensate for the gas fees.
New Test Added
New feature (non-breaking change which adds functionality) 
=> [Solana]: Adds ability to transfer tokens to the feepayer

rust/tw_evm/src/ffi/barz.rs, rust/tw_macros/src/lib.rs, rust/tw_macros/src/tw_ffi.rs, rust/tw_macros/src/utils.rs
This pull request updates the FFI interface and macro code to improve type safety and prevent issues with unsigned integer types in FFI-exposed class methods. The main changes include switching FFI parameters from unsigned to signed integers in `barz.rs`, adding runtime checks for integer conversion, and introducing compile-time validation in the macro to block unsigned integer types in class methods. A new utility function is also added to help with type checking.
* Changed FFI parameter types from `u32` to `i32` for `salt` and `chain_id` in `tw_barz_get_init_code` and `tw_barz_get_prefixed_msg_hash` to enforce the use of signed integers and updated documentation comments to clarify non-negative requirements. [[1]](diffhunk://#diff-22b60354d54c6f63347aa155e4e544727eb6012b8ef3bb1dab1e7c138 …
=> fix(barz): Replace u32 parameters with i32

rust/tw_keypair/src/ffi/asn.rs, rust/tw_keypair/src/ffi/privkey.rs, rust/tw_keypair/src/ffi/pubkey.rs, rust/tw_memory/src/ffi/c_byte_array_ref.rs, rust/tw_memory/src/ffi/tw_data.rs, rust/tw_memory/src/ffi/tw_string.rs, tests/chains/Ethereum/BarzTests.cpp, tests/common/DataTests.cpp
This pull request refactors memory handling in the Rust FFI layer to simplify error handling and improve API consistency. The main change is that methods like `CByteArrayRef::to_vec()` and `CByteArrayRef::as_slice()` now always return a value (empty if pointer is NULL), instead of an `Option`. Additionally, a new test is added for Ethereum Barz authorization with an empty-array representation of zero nonce.
* [`rust/tw_memory/src/ffi/c_byte_array_ref.rs`](diffhunk://#diff-1b997197f87eefd2c000261fbca414d8e9baea7c87fb79e44d2b5c22bbca0dcbL25-R26): Changed `CByteArrayRef::to_vec()` and `CByteArrayRef::as_slice()` to always return a value (empty on invalid input), removing `Option` from their signatures. [[1]](diffhunk://#diff-1b997197f87eefd2c000261fbca414d8e9baea7c87fb79e44d2b5c22bbca0dcbL25- …
=> fix(data): Allocate empty array on `tw_data_create_with_bytes` if data is NULL
