JNI/cpp/RippleAddress.c
JNI/cpp/RippleAddress.h
JNI/java/com/wallet/crypto/trustapp/jni/CoinType.java
JNI/java/com/wallet/crypto/trustapp/jni/RippleAddress.java
include/TrustWalletCore/TWCoinType.h
include/TrustWalletCore/TWRippleAddress.h
src/HDWallet.cpp
src/Ripple/Address.cpp
src/Ripple/Address.h
src/interface/TWCoinTypeConfiguration.cpp
src/interface/TWRippleAddress.cpp
swift/Sources/CoinType.swift
swift/Sources/RippleAddress.swift
swift/Sources/TrustWalletCore.h
swift/Tests/RippleTests.swift
swift/TrustWalletCore.xcodeproj/project.pbxproj
tests/Ripple/AddressTests.cpp
tests/TWRippleTests.cpp
trezor-crypto/CMakeLists.txt
trezor-crypto/include/TrezorCrypto/TrezorCrypto.h
trezor-crypto/include/TrezorCrypto/ripple/base58.h
trezor-crypto/src/base58.c
trezor-crypto/src/ripple/base58.c

Part of https://github.com/TrustWallet/wallet-core/issues/6.

Add TWRippleAddress model and address derivation

---

README.md

Change dependency string
Add dependency to android project
Update documentation

Update android instruction

---

src/Ethereum/ABI.h
src/Ethereum/ABI/Array.h
src/Ethereum/ABI/Bytes.h
src/Ethereum/ABI/Function.h
src/Ethereum/ABI/Numbers.h
src/Ethereum/ABI/Tuple.h
tests/Ethereum/ABITests.cpp

Fix https://github.com/TrustWallet/trust-wallet-core/issues/63

Implement Ethereum ABI encoding

---

include/TrustWalletCore/TWCoinType.h
src/interface/TWCoinTypeConfiguration.cpp
tests/TWCoinTypeConfigTests.cpp

not used anywhere, just extra switch to implement/handle on the clients

Remove TWCoinTypeTest

---

TrustWalletCore.podspec

Fix podspec [skip ci]

---

JNI/cpp/BitcoinTransactionSigner.c
JNI/cpp/BitcoinTransactionSigner.h
JNI/java/wallet/core/jni/BitcoinTransactionSigner.java
include/TrustWalletCore/TWBitcoinTransactionSigner.h
src/interface/TWBitcoinTransactionSigner.cpp
swift/Sources/BitcoinTransactionSigner.swift

Expose transaction plan for Bitcoin signer

---

src/Bitcoin/CashAddress.cpp
src/Coin.cpp
tests/CoinTests.cpp

Don't check prefix for Bitcoin Cash addresses

---

src/interface/TWBitcoinCashAddress.cpp
tests/interface/TWBitcoinCashTests.cpp

Fix Bitcoin Cash address validation

---

src/NEO/Address.cpp
src/NEO/Address.h
tests/NEO/AddressTests.cpp

Added NEO address with unit tests
Run unit tests

NEO address

---

src/Coin.cpp
swift/Tests/HDWalletTests.swift
tests/CoinTests.cpp
tests/interface/TWHDWalletTests.cpp

Use ed25519 curve and m'/44'/1729'/0'/0' for Tezos

Fix Tezos curve and derivation path

---

src/Coin.cpp
tests/CoinTests.cpp

Now we need to work on https://github.com/TrustWallet/wallet-core/issues/163

Fix ICON public key derivation

---

codegen/lib/swift_helper.rb
codegen/lib/templates/swift/enum.erb
swift/Sources/CoinType.swift
swift/Sources/Curve.swift
swift/Sources/EthereumChainID.swift
swift/Sources/HDVersion.swift
swift/Sources/HRP.swift
swift/Sources/IconAddressType.swift
swift/Sources/P2PKHPrefix.swift
swift/Sources/P2SHPrefix.swift
swift/Sources/Purpose.swift
swift/Sources/StellarMemoType.swift
swift/Sources/StellarVersionByte.swift

 Backtick keywords and make enum CaseIterable

---

TrustWalletCore.podspec
android/gradle.properties

Bump Library version to 0.7.1

---

JNI/cpp/StellarPassphrase.c
JNI/cpp/StellarPassphrase.h
JNI/java/wallet/core/jni/CoinType.java
JNI/java/wallet/core/jni/StellarPassphrase.java
JNI/java/wallet/core/jni/proto/Stellar.java
include/TrustWalletCore/TWCoinType.h
include/TrustWalletCore/TWStellarPassphrase.h
src/Coin.cpp
src/Stellar/Signer.cpp
src/interface/TWCoinTypeConfiguration.cpp
src/proto/Stellar.proto
swift/Sources/Blockchains/BlockchainFactory.swift
swift/Sources/Blockchains/Kin.swift
swift/Sources/CoinType.swift
swift/Sources/Stellar.pb.swift
swift/Sources/StellarPassphrase.swift
swift/Sources/TrustWalletCore.h
swift/Tests/Blockchains/KinSigner.swift
swift/Tests/Blockchains/StellarTests.swift
swift/Tests/CoinAddressDerivationTests.swift
swift/TrustWalletCore.xcodeproj/project.pbxproj
tests/CoinTests.cpp
tests/Stellar/TransactionTests.cpp
tests/interface/TWCoinTypeConfigTests.cpp
tests/interface/TWHDWalletTests.cpp

Add KIN blockchain support

---

JNI/java/wallet/core/jni/proto/Tezos.java
src/Tezos/Address.cpp
src/Tezos/Address.h
src/Tezos/BinaryCoding.cpp
src/Tezos/BinaryCoding.h
src/Tezos/Forging.cpp
src/Tezos/Forging.h
src/Tezos/OperationList.cpp
src/Tezos/OperationList.h
src/Tezos/Signer.cpp
src/Tezos/Signer.h
src/Tezos/Transaction.cpp
src/Tezos/Transaction.h
src/interface/TWTezosSigner.cpp
src/proto/Tezos.proto
swift/Sources/Tezos.pb.swift
swift/Tests/Blockchains/TezosTests.swift
tests/Tezos/AddressTests.cpp
tests/Tezos/ForgingTests.cpp
tests/Tezos/OperationListTests.cpp
tests/Tezos/PublicKeyTests.cpp
tests/Tezos/SignerTests.cpp
tests/Tezos/TransactionTests.cpp

Fix encoding in signing output.
Run swift tests in XCode
* Bug fix (non-breaking change which fixes an issue) 
- [ X ] Prefix PR title with `[WIP]` if necessary.
- [ X ] Add tests to cover changes as needed.
- [ X ] Update documentation as needed.

Encode signing output correctly

---

tools/generate-files

Add warning if xcodegen is missing

---

swift/Sources/Keystore/KeyStore.swift
swift/Tests/Keystore/KeyStoreTests.swift

Import multiple coins instead of one at a time

---

swift/Sources/Addresses/WanchainAddressExtension.swift

Added missed wanchain extension which supports address protocol here https://github.com/TrustWallet/wallet-core/pull/212
Run tests
`WanchainAddressExtension.swift` was added.

Added missed wanchain extension which supports address protocol

---

src/Bitcoin/Address.cpp
src/Bitcoin/Bech32Address.cpp
src/Bitcoin/CashAddress.cpp
src/Ethereum/Address.cpp

Throw on invalid public key when building Ethereum Address

---

src/interface/TWCoinTypeConfiguration.cpp
tests/interface/TWCoinTypeConfigTests.cpp

use blockchair for dash

---

src/Tezos/Address.cpp
src/Tezos/Address.h
src/Tezos/Forging.cpp
tests/Tezos/AddressTests.cpp

Add support for tz2, tz3, and KT1 addresses.
Run bootstrap.sh. Added new tests for additional address formats.
- [ X ] Prefix PR title with `[WIP]` if necessary.
- [ X ] Add tests to cover changes as needed.
- [ X ] Update documentation as needed.

Add support for tz2, tz3, kt1 addresses

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/TestHDWallet.kt
include/TrustWalletCore/TWHDVersion.h
include/TrustWalletCore/TWHDWallet.h
src/Coin.cpp
src/interface/TWHDWallet.cpp
swift/Sources/Blockchains/Bitcoin.swift
swift/Tests/Blockchains/DecredTests.swift
swift/Tests/HDWalletTests.swift
swift/TrustWalletCore.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
tests/interface/TWBitcoinCashTests.cpp
tests/interface/TWDecredTests.cpp
tests/interface/TWHDWalletTests.cpp
tests/interface/TWLitecoinTests.cpp
tests/interface/TWRippleTests.cpp
tests/interface/TWZCoinTests.cpp
tests/interface/TWZcashTests.cpp

Add Decred dpub support

---

src/interface/TWCoinTypeConfiguration.cpp
tests/interface/TWCoinTypeConfigTests.cpp

Change cosmos decimals to 6

---

swift/Sources/Keystore/KeyStore.swift

Add destroy method to keystore

---

include/TrustWalletCore/TWGroestlcoinTransactionSigner.h
src/Bitcoin/Transaction.cpp
src/Bitcoin/Transaction.h
src/Bitcoin/TransactionSigner.cpp
src/Bitcoin/TransactionSigner.h
src/Groestlcoin/Transaction.h
src/Hash.h
src/interface/TWGroestlcoinTransactionSigner.cpp
swift/Sources/TrustWalletCore.h
swift/Tests/GroestlcoinTransactionSignerTests.swift
tests/interface/TWGroestlcoinSigningTests.cpp

Transaction signing in Groestlcoin uses single round of SHA256 instead of double.

Groestlcoin transaction signing

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt
swift/Sources/Addresses/CoinType+Address.swift
swift/Tests/Blockchains/GroestlcoinTests.swift
swift/Tests/HDWalletTests.swift

More Groestlcoin tests

---

include/TrustWalletCore/TWStoredKey.h
src/Keystore/StoredKey.cpp
src/Keystore/StoredKey.h
src/interface/TWStoredKey.cpp
swift/Sources/Keystore/KeyStore.swift
swift/Sources/Keystore/Watch.swift
swift/Tests/Keystore/AccountTests.swift
swift/Tests/Keystore/KeyStoreTests.swift
swift/Tests/Keystore/KeystoreKeyTests.swift
swift/Tests/Keystore/WalletTests.swift
tests/Keystore/Data/key.json
tests/Keystore/StoredKeyTests.cpp

Add name property to StoredKey and Watch

---

include/TrustWalletCore/TWCoinType.h
include/TrustWalletCore/TWHRP.h
include/TrustWalletCore/TWP2PKHPrefix.h
include/TrustWalletCore/TWP2SHPrefix.h
src/Bitcoin/Script.cpp
src/Coin.cpp
src/interface/TWCoinTypeConfiguration.cpp
src/interface/TWHRP.cpp
tests/CoinTests.cpp
tests/interface/TWViacoinTests.cpp

Add support for Viacoin. Chain intergration.
old pull request: https://github.com/TrustWallet/wallet-core/pull/274

Add support for Viacoin [chain-integration]

---

include/TrustWalletCore/TWIocoinAddress.h
src/Iocoin/Address.cpp
src/Iocoin/Address.h
src/interface/TWIocoinAddress.cpp
tests/Iocoin/AddressTests.cpp

creating early I/O coin support pull request for feedback/review purposes Address handling+tests added

---

src/interface/TWCoinTypeConfiguration.cpp

ONT doesn't have a decimal.
ONT decimal was changed to 0

ONT doesn’t have decimal

---

src/interface/TWCoinTypeConfiguration.cpp

Ontology transaction URL fixed

Ontology transaction URL fixed

---

src/interface/TWCoinTypeConfiguration.cpp

ONT explorer URL fix

---

.clang-format
codegen/test/test_parser.rb
tools/codegen-test

Add codegen-test script and fix test

---

include/TrustWalletCore/TWCoinTypeConfiguration.h

Add comments to TWCoinTypeConfiguration.h for more clarify code
* Documentation

Add comments to TWCoinTypeConfiguration.h

---

codegen/lib/parser.rb
codegen/test/test_parser.rb

Now codegen works only with left align pointer 
Run in codegen folder
```
rake
```
or:
```
tools/generate-files
```

Add support different pointer declaration to codegen

---

codegen/lib/code_generator.rb
codegen/lib/js_helper.rb
codegen/lib/napi_helper.rb
codegen/lib/templates/js/class.erb
codegen/lib/templates/js/enum.erb
codegen/lib/templates/js/index.ts.erb
codegen/lib/templates/js/struct.erb
codegen/lib/templates/napi/binding.gyp.erb
codegen/lib/templates/napi/header.erb
codegen/lib/templates/napi/method_forward.erb
codegen/lib/templates/napi/parameter_access.erb
codegen/test/test_js_helper.rb
codegen/test/test_napi_helper.rb
js/.gitignore
js/js/WalletCore.js
js/lib/.gitignore
js/lib/index.ts
js/package-lock.json
js/package.json
js/tsconfig.json
tools/generate-files
tools/js-build

- Add `codegen` tests.
- Clean code in JS and Napi binding templates.
- Add packaging for local npm install to install `trust-wallet-core` local projects.
- Add JavaScript import support.
- Fix uint64_t and size_t parameter issue. Used `long` for uint64_t/size_t, since it is required to be installed to create protobufs with `protobufjs` anyways.
- Fix npm dependency issue (temp)
`cd codegen && rake`

JS bindings - Add tests, clean code, package

---

src/Bitcoin/CashAddress.cpp
swift/Tests/Blockchains/BitconCashTests.swift
tests/interface/TWBitcoinScriptTests.cpp

Fix build script for p2sh cashaddr

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/ontology/TestOntologySigning.kt
src/Ontology/Asset.h
src/Ontology/Ong.cpp
src/Ontology/Ong.h
src/Ontology/OngTxBuilder.cpp
src/Ontology/OngTxBuilder.h
src/Ontology/Ont.cpp
src/Ontology/Ont.h
src/Ontology/OntTxBuilder.cpp
src/Ontology/OntTxBuilder.h
src/proto/Ontology.proto
swift/Tests/Blockchains/OntologyTests.swift
tests/Ontology/OngTests.cpp
tests/Ontology/OntTests.cpp
tests/Ontology/TransactionTests.cpp
tests/interface/TWOntologyTransactionTests.cpp

Refactor ontology transaction as feedback. See https://github.com/TrustWallet/wallet-core/issues/312
Run unit test in the `tests` folder.
Breaking change (fix or feature that would cause existing functionality to change)

Refactor ontology transaction

---

codegen/lib/templates/js/class.erb
codegen/lib/templates/js/enum.erb
codegen/lib/templates/js/index.ts.erb
codegen/lib/templates/js/struct.erb
js/tsconfig.json

Signed-off-by: Sathvik Birudavolu <sathvikb30@gmail.com>
- Fix JS Codegen - static methods
- Fix TS duplicate type error
- Add ability to import JS/TypeScript protobufs from `trust-wallet-core`

Fix JS bindings bugs

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt
include/TrustWalletCore/TWCoinType.h
include/TrustWalletCore/TWP2PKHPrefix.h
include/TrustWalletCore/TWP2SHPrefix.h
src/Bitcoin/Script.cpp
src/Coin.cpp
src/interface/TWCoinTypeConfiguration.cpp
swift/Sources/Addresses/CoinType+Address.swift
swift/Tests/Blockchains/IocoinTests.swift
swift/Tests/CoinAddressDerivationTests.swift
tests/Iocoin/AddressTests.cpp
tests/interface/TWCoinTypeConfigTests.cpp
tests/interface/TWIocoinTests.cpp

Added configuration constants for IOCoin PR for ongoing feedback.

---

src/HDWallet.cpp
src/interface/TWStoredKey.cpp

Fix HDWallet crash, catch all stored key exceptions

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/TestHDWallet.kt
include/TrustWalletCore/TWHDWallet.h
src/HDWallet.cpp
src/HDWallet.h
src/interface/TWHDWallet.cpp
swift/Sources/Bitcoin.swift
swift/Tests/Blockchains/LitecoinTests.swift
swift/Tests/Blockchains/QtumTests.swift
swift/Tests/HDWalletTests.swift
tests/HDWalletTests.cpp
tests/interface/TWBitcoinCashTests.cpp
tests/interface/TWDecredTests.cpp
tests/interface/TWGroestlcoinTests.cpp
tests/interface/TWHDWalletTests.cpp
tests/interface/TWIocoinTests.cpp
tests/interface/TWLitecoinTests.cpp
tests/interface/TWLuxTests.cpp
tests/interface/TWQtumTests.cpp
tests/interface/TWRippleTests.cpp
tests/interface/TWViacoinTests.cpp
tests/interface/TWZCoinTests.cpp
tests/interface/TWZcashTests.cpp

Simplify get key from extended methods

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/stellar/TestAddress.kt
js/tests/blockchain/stellar/StellarAddress.test.ts
src/Stellar/Address.cpp
src/Stellar/Address.h
src/interface/TWStellarAddress.cpp
swift/Tests/Blockchains/StellarTests.swift
tests/Stellar/AddressTests.cpp

Stellar address fixes and improvements

---

README.md
docs/Contributing.md
js/README.md
js/package-lock.json
js/package.json
tools/js-release
tools/js-test

- Add info to `package.json`.
- Add `tools/js-release` script that publishes to the `npm` registry
- Add `README.md` for `npm` registery.
- Update main `README.md` and `docs/Contributing.md` to add JavaScript info

Add JS publishing, Update docs

---

include/TrustWalletCore/TWCurve.h
include/TrustWalletCore/TWPrivateKey.h
include/TrustWalletCore/TWPublicKeyType.h
src/HDWallet.cpp
src/PrivateKey.cpp
src/PublicKey.cpp
src/PublicKey.h
src/interface/TWPrivateKey.cpp
swift/project.yml
trezor-crypto/CMakeLists.txt
trezor-crypto/include/TrezorCrypto/ed25519-donna/ed25519-blake2b.h
trezor-crypto/include/TrezorCrypto/nano.h
trezor-crypto/src/bip32.c
trezor-crypto/src/curves.c
trezor-crypto/src/ed25519-donna/ed25519-blake2b.c
trezor-crypto/src/ed25519-donna/ed25519-hash-custom-blake2b.h
trezor-crypto/src/nano.c
trezor-crypto/tests/test_check.c
trezor-crypto/tests/test_check_nano.h

This is the first pull-request (of 2) for #8 Nano integration, which contains the trezor-crypto changes required for Nano. It's mostly a port of code from KeepKey/trezor-crypto#1 and some wallet-core level changes to accommodate the new functionality.
Contains unit-tests in _trezor-core/tests/_

Trezor-crypto updates for Nano support

---

codegen/lib/templates/js_napi_cc.erb
codegen/lib/templates/napi/method_forward.erb
js/cpp/TWNapi.h
js/cpp/TWNapiData.cc
js/cpp/TWNapiString.cc
js/package.json

Signed-off-by: Sathvik Birudavolu <sathvikb30@gmail.com>
- Fix JS crash (Problem: wrong struct casting)
- Remove C-style casts

Fix JS bug

---

src/Keystore/EncryptionParameters.cpp
src/Keystore/EncryptionParameters.h
src/Keystore/PBKDF2Parameters.cpp
src/Keystore/PBKDF2Parameters.h
src/Keystore/ScryptParameters.cpp
tests/Keystore/Data/pbkdf2.json
tests/Keystore/StoredKeyTests.cpp
trezor-crypto/include/TrezorCrypto/pbkdf2.h
trezor-crypto/src/pbkdf2.c

Add support for PBKDF2 private key encryption

---

android/build.gradle
docs/Contributing.md

Add gradle-nexus-staging-plugin to automate release step

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt
android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/nano/TestNanoAddress.kt
android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/nano/TestNanoSigner.kt
coins.json
include/TrustWalletCore/TWCoinType.h
include/TrustWalletCore/TWNanoAddress.h
include/TrustWalletCore/TWNanoProto.h
include/TrustWalletCore/TWNanoSigner.h
js/tests/blockchain/nano/NanoAddress.test.ts
js/tests/blockchain/nano/NanoSigner.test.ts
js/tests/utils/CoinAddressDerivation.test.ts
src/Coin.cpp
src/Nano/Address.cpp
src/Nano/Address.h
src/Nano/Signer.cpp
src/Nano/Signer.h
src/PrivateKey.cpp
src/interface/TWNanoAddress.cpp
src/interface/TWNanoSigner.cpp
src/proto/Nano.proto
swift/Sources/Addresses/CoinType+Address.swift
swift/Tests/Blockchains/NanoTests.swift
swift/Tests/CoinAddressDerivationTests.swift
tests/CoinTests.cpp
tests/Nano/AddressTests.cpp
tests/Nano/SignerTests.cpp
tests/interface/TWCoinTypeConfigTests.cpp
tests/interface/TWNanoTests.cpp

This is the second pull-request (of 2) for #8 Nano integration, which contains the Nano implementation in wallet-core (C++ APIs, C interface & bindings updates).
Closes #8.
Unit-tests in wallet-core and all (Swift, Android, JS) bindings.

Nano integration

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt
coins.json
include/TrustWalletCore/TWCoinType.h
include/TrustWalletCore/TWIoTeXAddress.h
include/TrustWalletCore/TWIoTeXProto.h
include/TrustWalletCore/TWIoTeXSigner.h
src/Coin.cpp
src/IoTeX/Address.cpp
src/IoTeX/Address.h
src/IoTeX/Signer.cpp
src/IoTeX/Signer.h
src/interface/TWIoTeXAddress.cpp
src/interface/TWIoTeXSigner.cpp
src/proto/IoTeX.proto
swift/Sources/Addresses/CoinType+Address.swift
swift/Tests/CoinAddressDerivationTests.swift
tests/CoinTests.cpp
tests/IoTeX/AddressTests.cpp
tests/IoTeX/SignerTests.cpp
tests/interface/TWCoinTypeConfigTests.cpp

This PR implemented #390 
One question: in src/Coin.cpp, I see TW::validateAddress() and TW::deriveAddress(), but don't see TW::curve(). It seems TW::curve() is only found in swift/wallet-core/Generated/Coins.cpp, but that is a generated file which is marked This is a GENERATED FILE, changes made here WILL BE LOST.
This PR includes unit tests for address and signing class/interface

Adding support for IoTeX blockchain #390

---

include/TrustWalletCore/TWBlockchain.h

Add blockchain enum

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt
coins.json
js/tests/utils/CoinAddressDerivation.test.ts
swift/Tests/Blockchains/IOSTTests.swift
swift/Tests/CoinAddressDerivationTests.swift

Fix #373, compatible with Cobo wallet

Update IOST derivation path

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt
coins.json
include/TrustWalletCore/TWCoinType.h
include/TrustWalletCore/TWZilliqaAddress.h
js/tests/utils/CoinAddressDerivation.test.ts
src/Coin.cpp
src/Zilliqa/Address.cpp
src/Zilliqa/Address.h
src/interface/TWZilliqaAddress.cpp
swift/Sources/Addresses/CoinType+Address.swift
swift/Tests/CoinAddressDerivationTests.swift
tests/CoinTests.cpp
tests/Zilliqa/AddressTests.cpp
tests/interface/TWCoinTypeConfigTests.cpp
trezor-crypto/CMakeLists.txt
trezor-crypto/include/TrezorCrypto/ecdsa.h
trezor-crypto/include/TrezorCrypto/schnorr.h
trezor-crypto/src/ecdsa.c
trezor-crypto/src/schnorr.c

Add Zilliqa address / config

---

coins.json
src/Bitcoin/UnspentCalculator.cpp
tests/Bitcoin/UnspentSelectorTests.cpp
tests/interface/TWCoinTypeConfigTests.cpp

update groestl explorer url and fee

---

include/TrustWalletCore/TWStoredKey.h
src/interface/TWStoredKey.cpp
swift/Sources/Keystore/KeyStore.swift
swift/Tests/Keystore/AccountTests.swift
swift/Tests/Keystore/KeyStoreTests.swift
swift/Tests/Keystore/KeystoreKeyTests.swift

Check private key validity

---

include/TrustWalletCore/TWBitcoinAddress.h
include/TrustWalletCore/TWBitcoinCashAddress.h
include/TrustWalletCore/TWZcashTAddress.h
src/Bitcoin/Address.h
src/interface/TWBitcoinAddress.cpp
src/interface/TWBitcoinCashAddress.cpp
src/interface/TWZcashTAddress.cpp
swift/Tests/Addresses/BitcoinAddressTests.swift
swift/Tests/Blockchains/DogeTests.swift
swift/Tests/Blockchains/LitecoinTests.swift
swift/Tests/Blockchains/QtumTests.swift
swift/Tests/HDWalletTests.swift
tests/interface/TWBitcoinCashTests.cpp
tests/interface/TWLitecoinTests.cpp
tests/interface/TWLuxTests.cpp
tests/interface/TWQtumTests.cpp
tests/interface/TWViacoinTests.cpp
tests/interface/TWZCoinTests.cpp
tests/interface/TWZcashTests.cpp

Make TWBitcoinAddress a class and use C++ implementation

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt
coins.json
include/TrustWalletCore/TWCoinType.h
include/TrustWalletCore/TWEthereumChainID.h
js/tests/utils/CoinAddressDerivation.test.ts
src/Coin.cpp
swift/Sources/Addresses/CoinType+Address.swift
swift/Sources/ChainID.swift
swift/Tests/CoinAddressDerivationTests.swift
swift/Tests/Keystore/WalletTests.swift
swift/Tests/SlipTests.swift
tests/CoinTests.cpp
tests/interface/TWCoinTypeConfigTests.cpp

add Ellaism (ELLA) support
- Homepage: https://ellaism.org/
- Block Explorer : https://explorer.ellaism.org
- API node: https://jsonrpc.ellaism.org
- BIP44 `163` ( https://github.com/satoshilabs/slips/pull/125 )
- Chainid `64` (https://chainid.network/)
- Ticker: ELLA
- CMC: https://coinmarketcap.com/currencies/ellaism/
`./bootstrap.sh` or `make -C build tests`
Ellaism support added
cc: @ellaismer @limax

WIP: support Ellaism

---

js/package-lock.json
src/PrivateKey.cpp
src/PrivateKey.h
src/interface/TWStoredKey.cpp
tests/interface/TWPrivateKeyTests.cpp
tests/interface/TWStoredKeyTests.cpp

Fix importing ethereum private key `fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141` crash
`./bootstrap.sh`
* Bug fix

return nullptr if private key is invalid

---

TrustWalletCore.podspec
swift/Podfile
swift/Podfile.lock
tools/install-dependencies

From https://github.com/apple/swift-protobuf/releases/tag/1.5.0
> Complete support for Swift 5.

Update SwiftProtobuf to 1.5.0

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt
android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/ark/TestArkTransactionSigning.kt
coins.json
include/TrustWalletCore/TWARKAddress.h
include/TrustWalletCore/TWARKProto.h
include/TrustWalletCore/TWARKSigner.h
include/TrustWalletCore/TWBlockchain.h
include/TrustWalletCore/TWCoinType.h
js/tests/blockchain/ark/ARKSigner.test.ts
src/ARK/Address.cpp
src/ARK/Address.h
src/ARK/Signer.cpp
src/ARK/Signer.h
src/ARK/Transaction.cpp
src/ARK/Transaction.h
src/Coin.cpp
src/interface/TWARKAddress.cpp
src/interface/TWARKSigner.cpp
src/proto/ARK.proto
swift/Sources/Addresses/CoinType+Address.swift
swift/Tests/Blockchains/ARKTests.swift
swift/Tests/CoinAddressDerivationTests.swift
tests/ARK/AddressTests.cpp
tests/ARK/SignerTests.cpp
tests/CoinTests.cpp
tests/interface/TWCoinTypeConfigTests.cpp

Based on https://github.com/TrustWallet/wallet-core/pull/430, rebased + cleanup

Add Ark support

---

src/Bitcoin/Script.cpp
tests/interface/TWZcashTests.cpp

Add zcash lock script tests

---

include/TrustWalletCore/TWZilliqaAddress.h
src/Zilliqa/Address.h
src/interface/TWZilliqaAddress.cpp
swift/Sources/Addresses/CoinType+Address.swift
swift/Tests/Blockchains/ZilliqaTests.swift
tests/interface/TWZilliqaTests.cpp

Support creating Zilliqa address from key hash

---

tools/ios-build
tools/ios-release

Auto publish to cocoapods

---

docs/coins.md

Nimiq's currency symbol has always been `NIM` but the full list of currencies shows `NMQ`

Set symbol for Nimiq to NIM

---

src/NULS/Signer.cpp
src/NULS/Signer.h
src/Ontology/OngTxBuilder.cpp
src/Ontology/OngTxBuilder.h
src/Ontology/OntTxBuilder.cpp
src/Ontology/OntTxBuilder.h
src/interface/TWBravoSigner.cpp
src/interface/TWNULSSigner.cpp
src/interface/TWNanoSigner.cpp
src/interface/TWOntologySigner.cpp
tests/interface/TWOntologyTransactionTests.cpp

Fixes #424 , NULS output and refine Ontology builders

Catch signer exceptions

---

android/gradle.properties

Bump Android version

---

codegen/lib/templates/coins.cpp.erb
include/TrustWalletCore/TWBitcoinScript.h
src/Bitcoin/Script.cpp
src/Bitcoin/Script.h
src/Bitcoin/TransactionBuilder.h
src/Bitcoin/TransactionSigner.h
src/Coin.h
src/Decred/TransactionBuilder.h
src/interface/TWBitcoinScript.cpp
swift/Tests/Blockchains/BitconCashTests.swift
tests/HDWalletTests.cpp
tests/interface/TWBitcoinCashTests.cpp
tests/interface/TWBitcoinScriptTests.cpp
tests/interface/TWDashTests.cpp
tests/interface/TWDecredTests.cpp
tests/interface/TWDigiByteTransactionTests.cpp
tests/interface/TWDogeTests.cpp
tests/interface/TWGroestlcoinTests.cpp
tests/interface/TWLitecoinTests.cpp
tests/interface/TWLuxTests.cpp
tests/interface/TWQtumTests.cpp
tests/interface/TWRavencoinTransactionTests.cpp
tests/interface/TWViacoinTests.cpp
tests/interface/TWZCoinTests.cpp
tests/interface/TWZcashTests.cpp

Add coin type to Script::buildForAddress

---

coins.json
tests/interface/TWCoinTypeConfigTests.cpp

use blockchair for doge

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/waves/TestWavesSigner.kt
js/tests/blockchain/waves/WavesSigner.test.ts
src/Waves/Transaction.cpp
src/Waves/Transaction.h
src/interface/TWWavesSigner.cpp
src/proto/Waves.proto
tests/Waves/TransactionTests.cpp
tests/interface/TWWavesSignerTests.cpp

Added Waves transfer transaction json serialization
unit test

Waves tx json serialization

---

coins.json
tests/interface/TWCoinTypeConfigTests.cpp

Update groestlcoin block explorer

---

android/app/src/androidTest/java/com/trustwallet/core/app/utils/TestKeyStore.kt
codegen/lib/templates/jni/method_forward.erb

Check and handle nullable return type for jni string

---

coins.json

Update Terra client docs
Just update terra client docs link.
from
"info": {
"url": "https://terra.money",
"client": "https://github.com/terra-project/core",
"clientPublic": "",
"clientDocs": "https://terra.money"
}
To
"info": {
"url": "https://terra.money",
"client": "https://github.com/terra-project/core",
"clientPublic": "",
"clientDocs": "https://docs.terra.money"
}
- [v] Prefix PR title with `[WIP]` if necessary.
- [v] Add tests to cover changes as needed.
- [v] Update documentation as needed.

Update Terra client docs

---

README.md
js/README.md
js/package-lock.json
js/package.json

- Published version `0.4.0`
- Updated` js/README.md`

Bump npm version to v0.4.0

---

include/TrustWalletCore/TWCosmosProto.h
src/Cosmos/Serialization.cpp
src/Cosmos/Serialization.h
src/Cosmos/Signer.cpp
src/proto/Cosmos.proto
tests/Cosmos/StakingTests.cpp

This PR adds Cosmos Undelegate and WithdrawDelegationReward messages.
Just run unit tests.

Cosmos unstake

---

codegen/lib/code_generator.rb
codegen/lib/templates/napi/binding.gyp.erb
js/js/WalletCore.ts
js/package-lock.json
js/package.json
js/proto/.gitignore
js/tsconfig.json
tools/generate-files
tools/js-binary-release
tools/js-build
tools/js-release
tools/js-test

- Switched to `node-pre-gyp`
- Changes binary name and moved `bindings.gyp` to `js/` (required by `node-pre-gyp`)
- Change` js/build/` to `js/dist/` for npm packaging
- `node-pre-gyp` uses `js/build` to build binary and copies into `js/dist/`
- Remove binary from the npm package
- `npm run build`
- `npm test`

Add S3 support for js binary

---

coins.json
include/TrustWalletCore/TWBlockchain.h
src/Ripple/Transaction.cpp
swift/Tests/Blockchains/RippleTests.swift
tests/Ripple/TransactionTests.cpp
tests/interface/TWCoinTypeConfigTests.cpp

Fix XRP max amount

---

.github/ISSUE_TEMPLATE/new_blockchain.md
src/Bitcoin/TransactionBuilder.h
src/Bitcoin/UnspentCalculator.cpp
src/Decred/Signer.h
src/Decred/TransactionBuilder.h
tests/Bitcoin/TransactionPlanTests.cpp

1. Add Decred fee calculation
2. Remove duplicate `TransactionBuilder::plan` code
Run all the tests

Add Decred fee calculation

---

coins.json
tests/interface/TWCoinTypeConfigTests.cpp

The new block explorer http://dcrdata.decred.org

Update decred explorer

---

src/Any/Signer.cpp
tests/Any/SignerTests.cpp
tests/Tezos/SignerTests.cpp

Add Tezos support to AnySigner.
Transaction sample is the same used in TezosSingerTests, but in JSON format:
```json
{
"operationList": {
"branch": "BL8euoCWqNCny9AR3AKjnpi38haYMxjei1ZqNHuXMn19JSQnoWp",
"operations": [
{
"source": "tz1XVJ8bZUXs7r5NV8dHvuiBhzECvLRLR3jW",
"fee": 1272,
"counter": 30738,
"gasLimit": 10100,
"storageLimit": 257,
"kind": 7,
"revealOperationData": {
"publicKey": "QpqYbIBypAofOj4qtaWBm7Gy+2mZPFAEg3gVudxVkj4="
}
},
{
"source": "tz1XVJ8bZUXs7r5NV8dHvuiBhzECvLRLR3jW",
"fee": 1272,
"counter": 30739,
"gasLimit": 10100,
"storageLimit": 257,
"kind": 8,
"transactionOperationData": {
"destination": "tz1XVJ8bZUXs7r5NV8dHvuiBhzECvLRLR3jW",
"amount": 1
}
}
]
}
}
```

Add Tezos support to AnySigner

---

src/Any/Signer.cpp
src/VeChain/Signer.cpp
src/VeChain/Signer.h
src/interface/TWVeChainSigner.cpp
tests/Any/SignerTests.cpp

[AnySigner] Add support to VeChain

---

include/TrustWalletCore/TWTronProto.h
src/Tron/Protobuf/TronInternal.pb.cc
src/Tron/Protobuf/TronInternal.pb.h
src/Tron/Protobuf/TronInternal.proto
src/Tron/Signer.cpp
src/proto/Tron.proto
tests/Tron/SignerTests.cpp

Add TRON staking messages

---

src/Tron/Protobuf/TronInternal.pb.cc
src/Tron/Protobuf/TronInternal.pb.h
src/Tron/Protobuf/TronInternal.proto
src/Tron/Signer.cpp
tests/Tron/SignerTests.cpp

Fix TRON contract types

---

src/Tron/Signer.cpp
src/proto/Tron.proto

Add fee limit to Tron transaction

---

README.md
src/Cosmos/Serialization.cpp
src/Cosmos/Serialization.h

https://github.com/cosmos/gaia/wiki/Cosmos-Hub-2-Upgrade#notes-for-service-providers

Remove not used Cosmos serialization prefix

---

include/TrustWalletCore/TWTronProto.h
src/Data.h
src/Tron/Signer.cpp
src/proto/Tron.proto
tests/Tron/SignerTests.cpp

Fixes #643 
Improve TRC20 token transfer message and set defaults for timestamp and expiration when not set.

Improve TRC20 token transfer message

---

src/Any/Signer.cpp
src/Cosmos/Serialization.cpp
src/Tron/Serialization.cpp
src/Tron/Serialization.h
src/Tron/Signer.cpp
src/proto/Tron.proto
tests/Any/SignerTests.cpp
tests/Tron/SerializationTests.cpp

Add tron transaction signing as json format

---

src/Tron/Signer.cpp
tests/Tron/SignerTests.cpp

Fix tron signer for freeze and unfreeze balance

---

android/build.gradle
android/trustwalletcore/build.gradle
tools/android-jitpack

Added Jitpack upload to android gradle scripts
Run android-jitpack in tools dir

added jitpack to gradle

---

tools/ios-test

Fixes #658, CI is using Xcode 11 now

Test with xcode 11 simulator

---

jitpack.yml

JitPack needs to install dependencies to build android lib so I added yml script for it. It will run before jitpack build

Added jitpack yml script

---

README.md

Updated dependency to
implementation 'com.trustwallet:wallet-core:0.12.23'

Updated android dependency in readme

---

coins.json
tests/interface/TWCoinTypeConfigTests.cpp

Due to TzScan end of life https://medium.com/@tzscan/tzscan-the-end-of-the-road-bef47e0aa2f1, updating explorer.

Add, update and correct publicly available RPC's. Update Tezos explorer.

---

coins.json
tests/interface/TWCoinTypeConfigTests.cpp

from: https://medium.com/@vechainofficial/announcing-the-new-official-vechain-block-explorer-and-vechain-sync-ledger-wallet-interface-38a4b5360aeb

Update vechain block explorer

---

README.md
tools/maven-android-upload

- Updated android dependency in readmy
- Set android home variable when uploading to maven

Update android dependency

---

src/Algorand/Address.cpp
src/Base32.h
src/Nimiq/Address.cpp
src/Stellar/Address.cpp
tests/BaseEncoding.cpp

Added wrapper for Base32 encoding, calls into Trezor implementation.  Updated 3 coins that use it.  Also added new tests.
Minor refactoring.

New Base32 wrapper and tests.

---

coins.json
tests/Wanchain/TWCoinTypeTests.cpp

https://explorer.wanchain.org doesn't work anymore. The official site https://www.wanchain.org/ hast a new explorer https://www.wanscan.org/

Wanchain explorer url was changed

---

include/TrustWalletCore/TWCosmosProto.h
src/Cosmos/Serialization.cpp
src/Cosmos/Serialization.h
src/Cosmos/Signer.cpp
src/proto/Cosmos.proto
tests/Cosmos/StakingTests.cpp

Added redelegation messages to Cosmos

[ COSMOS ] Add redelegation support

---

codegen/bin/cointests
codegen/bin/newcoin
codegen/lib/templates/newcoin/Address.cpp.erb
codegen/lib/templates/newcoin/Address.h.erb
codegen/lib/templates/newcoin/AddressTests.cpp.erb
tests/Wanchain/TWCoinTypeTests.cpp

Minor touches to the templates.
* Minot

New coin template minor changes, forgotten PR review.

---

coins.json
tests/Nano/TWCoinTypeTests.cpp

Update Nano explorer in coins.json, from nanode to nanocrawler, as requested by Nano team.
Coins.json changed, no functional change.

Update Nano explorer, as requested by Nano team.

---

.gitignore
TrustWalletCore.podspec
include/TrustWalletCore/TWRippleAddress.h
include/TrustWalletCore/TWRippleXAddress.h
src/Aeternity/Transaction.cpp
src/Coin.cpp
src/Data.h
src/Harmony/Staking.h
src/Ripple/Address.cpp
src/Ripple/Address.h
src/Ripple/Transaction.cpp
src/Ripple/Transaction.h
src/Ripple/XAddress.cpp
src/Ripple/XAddress.h
src/interface/TWRippleAddress.cpp
src/interface/TWRippleSigner.cpp
src/interface/TWRippleXAddress.cpp
swift/Sources/Addresses/CoinType+Address.swift
swift/Tests/Blockchains/RippleTests.swift
tests/CoinAddressValidationTests.cpp
tests/Ripple/AddressTests.cpp
tests/Ripple/TransactionTests.cpp
wallet_core.srctrlprj

Fixes #729 and a few minor fixes

Support XRP X-address

---

include/TrustWalletCore/TWCosmosProto.h
src/Cosmos/Serialization.cpp
src/Cosmos/Serialization.h
src/Cosmos/Signer.cpp
src/proto/Cosmos.proto
tests/Cosmos/StakingTests.cpp
tools/tests

https://github.com/cosmos/cosmos-sdk/blob/3aca119fd14514bde99ee33cc7439b9d98f3ea7e/x/distribution/spec/04_messages.md#msgwithdrawdelegationrewardsall

[Cosmos] Add MsgWithdrawDelegationRewardsAll

---

.gitignore
.swiftlint.yml
android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt
android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/cosmos/TestCosmosTransactions.kt
android/build.gradle
include/TrustWalletCore/TWCosmosProto.h
src/Binance/Signer.cpp
src/Cosmos/Serialization.cpp
src/Cosmos/Serialization.h
src/Cosmos/Signer.cpp
src/Cosmos/Signer.h
src/proto/Cosmos.proto
swift/Tests/Blockchains/CosmosTests.swift
swift/Tests/Blockchains/TerraTests.swift
tests/Any/SignerTests.cpp
tests/Cosmos/SignerTests.cpp
tests/Cosmos/StakingTests.cpp

Close #764 
Close #762
Close #587 
`./bootstrap.sh`
* Breaking change
- AnySigner could fail when sign cosmos
- swift/android code needs to change to accept array

Refactor Cosmos implementation

---

src/Bitcoin/TransactionPlan.h
src/Bitcoin/TransactionSigner.cpp
src/Bitcoin/TransactionSigner.h
src/Coin.cpp
src/Zcash/Transaction.cpp
src/Zcash/Transaction.h
src/Zcash/TransactionBuilder.h
src/interface/TWBitcoinTransactionSigner.cpp
src/interface/TWGroestlcoinTransactionSigner.cpp
src/interface/TWZcashTransactionSigner.cpp
src/proto/Bitcoin.proto
swift/Tests/Blockchains/ZcashTests.swift
tests/interface/TWBitcoinCashTests.cpp
tests/interface/TWBitcoinSigningTests.cpp
tests/interface/TWDigiByteTransactionTests.cpp
tests/interface/TWGroestlcoinSigningTests.cpp
tests/interface/TWMonacoinTransactionTests.cpp
tests/interface/TWRavencoinTransactionTests.cpp
tests/interface/TWZcashTransactionTests.cpp
tests/interface/TWZelcashTransactionTests.cpp

Only consensus branch id changed, Add `Zcash::TransactionBuilder`
`./bootstrap.sh`

Zcash Blossom support

---

src/Tezos/Forging.cpp
tests/Tezos/ForgingTests.cpp

Fix binary forging for some edge case values.
1) Run tests
2) Update Podfile.lock and change wallet-core dependency to: `pod 'TrustWalletCore', git: 'https://github.com/trustwallet/wallet-core', branch: 'fix-tezos-forging'`
4) Build and run the app on a simulator
3) Try to send 0.000128 tezos to another wallet.

Fix tezos forge transaction

---

samples/android/README.md
samples/android/app/src/main/java/com/trust/walletcore/example/MainActivity.kt
samples/go/README.md
samples/go/main.go
samples/ios/README.md

Extend with BTC example the Android sample app.
n.a.

Android sample: extend with BTC example, adjust README.

---

android/app/src/androidTest/java/com/trustwallet/core/app/utils/TestKeyStore.kt
codegen/lib/templates/jni/method_forward.erb

Fix return empty data crash

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/terra/TestTerraTransactions.kt
coins.json
src/Cosmos/Serialization.cpp
src/proto/Cosmos.proto
swift/Podfile.lock
swift/Tests/Blockchains/CosmosTests.swift
swift/Tests/Blockchains/KavaTests.swift
swift/Tests/Blockchains/TerraTests.swift
tests/Any/SignerTests.cpp
tests/Cosmos/SignerTests.cpp
tests/Cosmos/StakingTests.cpp
tools/ios-test

Update Terra integration interface with protobuf changes and remove unnecessary type field of tx in `cosmos` and `kava`.
* ./tools/tests 

[Terra] Integration Update

---

coins.json
tests/EthereumClassic/TWCoinTypeTests.cpp

Update ETC block explorer

---

src/Cosmos/Serialization.cpp
src/proto/Cosmos.proto
tests/Cosmos/SignerTests.cpp

Add mode to cosmos signing input

---

src/Nano/Signer.cpp
src/Nano/Signer.h
src/proto/Nano.proto
tests/Nano/SignerTests.cpp

Nano Signer returns signed block as json as well.  Solves issue #831 .
Unit tests, see NanoSigner.sign1 .

Nano: Return signed block as json too

---

coins.json
tests/EthereumClassic/TWCoinTypeTests.cpp

Based on https://github.com/trustwallet/wallet-core/pull/824#issuecomment-578423821

Revert "Update ETC explorer to etcblockexplorer.com. (#824)"

---

README.md

Alice now is available in the App Store: https://apps.apple.com/cn/app/alice-browser/id1472818028
Alice using wallet core to support multiple blockchain such as Binance and Bitcoin.

Adding Alice to project list

---

src/Nano/Signer.cpp
src/interface/TWNanoSigner.cpp
src/proto/Nano.proto
swift/Tests/Blockchains/NanoTests.swift
tests/Nano/SignerTests.cpp

This PR fixes nano signer json output on `TWNanoSigner` interface.
- Just run iOS tests.

Fix nano signer json output

---

tests/Ethereum/RLPTests.cpp
tests/interface/TWHashTests.cpp
tests/interface/TWStoredKeyTests.cpp
tests/interface/TWTestUtilities.cpp
tests/interface/TWTestUtilities.h

Add extra tests to increase test line coverage.
Unit tests.
* Test only, new tests.

[TestOnly] Add tests for better coverage

---

include/TrustWalletCore/TWHash.h
src/Algorand/Address.cpp
src/Base58.cpp
src/Bech32Address.cpp
src/Bravo/Address.cpp
src/Cardano/Address.cpp
src/Ethereum/Address.cpp
src/Groestlcoin/Transaction.h
src/HDWallet.cpp
src/Hash.cpp
src/Hash.h
src/Nebulas/Address.cpp
src/PublicKey.cpp
src/interface/TWHash.cpp
tests/HDWalletTests.cpp
tests/interface/TWHashTests.cpp

Refactor Hash implementation. Solves issue #849 . Changes:
- No logic in TWHash.cpp, calls route to Hash.cpp
- Cover some missing Hash methods in TWHash (with tests)
- Hash methods use (data+size) input, as opposed to (begin, end)
Unit tests.

Refactor Hash, clean up

---

codegen/lib/code_generator.rb
codegen/lib/function_decl.rb
codegen/lib/parser.rb
codegen/lib/templates/swift/method.erb
codegen/lib/templates/swift/static_method.erb
codegen/test/test_parser.rb
include/TrustWalletCore/TWBase.h
include/TrustWalletCore/TWEthereumAbiFunction.h

Fixes #844 
```swift
@discardableResult
public func addParamInt64(val: Int64, isOutput: Bool) -> Int32 {
return TWEthereumAbiFunctionAddParamInt64(rawValue, val, isOutput)
}
```

Add @discardableResult support

---

include/TrustWalletCore/TWAnyAddress.h
src/interface/TWAnyAddress.cpp
swift/Tests/Addresses/NEOAddressTests.swift
swift/Tests/Addresses/OntologyAddressTests.swift
swift/Tests/Blockchains/FIOTests.swift
swift/Tests/Blockchains/IconTests.swift
tests/interface/TWBitcoinCashTests.cpp
tests/interface/TWNebulasTests.cpp
tests/interface/TWTONTests.cpp
tests/interface/TWZilliqaTests.cpp

Rename to TWAnyAddressIsValid

---

src/PublicKey.cpp
tests/PublicKeyTests.cpp
tests/interface/TWPublicKeyTests.cpp

Extended PublicKey tests for better coverage.
Unit tests.
* Test only

[Testonly] Improved PublicKey tests, coverage.

---

src/Keystore/StoredKey.cpp
src/Keystore/StoredKey.h
src/interface/TWStoredKey.cpp
tests/Keystore/StoredKeyTests.cpp
tests/interface/TWStoredKeyTests.cpp

Move logic from TWStoredKey to StoredKey; extend tests for coverage.  Solves #851 .
Unit tests, coverage.
* Refactor

StoredKey: no logic in TWStoredKey, extend tests.

---

tests/WalletConsoleTests.cpp
walletconsole/lib/Address.cpp
walletconsole/lib/CommandExecutor.cpp
walletconsole/lib/CommandExecutor.h
walletconsole/lib/Keys.cpp
walletconsole/lib/Util.cpp
walletconsole/lib/Util.h
walletconsole/lib/WalletConsole.cpp

Extend walletconsole tests for coverage.
Unit tests, coverage report.
* Minor refactor, extra tests.

Extend walletconsole tests

---

jni/cpp/TWJNIString.cpp
src/NULS/BinaryCoding.h
swift/Sources/AnySigner.swift
swift/Tests/Blockchains/BinanceChainTests.swift

1. TWString leaking in JNI
2. cocoapods build from source
3. split AnySigner.swift (like Java implementation)

Misc fixes

---

samples/cpp/CMakeLists.txt

Compile fix for sample/cpp on Linux (docker).
It was missing -stdlib=libc++ flag, and on Linux it had static lib build flags, which is not needed (this is not a lib).
Fixes #856 .
Start a shell in walletcore docker image:
```
docker run -i -t trustwallet/wallet-core
```
Inside, execute:
```
cd /wallet-core
git pull
cd samples/cpp
cmake . -DWALLET_CORE=../../
make
```

[Minor] Compile fix for sample/cpp on Linux (docker).

---

.github/PULL_REQUEST_TEMPLATE.md

Extend PR template with reminder to include linked issue, if any (I often forget to mention it).
n.a.
* GitHub template only

[github template] Extend PR template with issue reminder.

---

tools/ios-release-framework

Enable osx.deployment

---

coins.json
tests/Solana/TWCoinTypeTests.cpp

Solana decimal fix

---

coins.json
tests/Stellar/TWCoinTypeTests.cpp
tests/Zcash/TWCoinTypeTests.cpp

Update zcash/xlm block explorer

---

android/app/src/androidTest/java/com/trustwallet/core/app/utils/TestKeyStore.kt
include/TrustWalletCore/TWStoredKey.h
src/Keystore/EncryptionParameters.cpp
src/Keystore/EncryptionParameters.h
src/Keystore/StoredKey.cpp
src/Keystore/StoredKey.h
src/interface/TWStoredKey.cpp
swift/Sources/KeyStore.swift
swift/Sources/Wallet.swift
swift/Tests/Keystore/AccountTests.swift
swift/Tests/Keystore/KeyStoreTests.swift
swift/Tests/Keystore/KeystoreKeyTests.swift
swift/Tests/Keystore/WalletTests.swift
tests/Keystore/Data/ethereum-wallet-address-no-0x.json
tests/Keystore/Data/myetherwallet.uu
tests/Keystore/Data/web3j.json
tests/Keystore/StoredKeyTests.cpp
tests/interface/TWStoredKeyTests.cpp

Change password type in StoredKey from string to data

---

src/Filecoin/Entry.cpp
src/Filecoin/Entry.h
src/Filecoin/Signer.cpp
src/Filecoin/Signer.h
tests/Filecoin/TWAnySignerTests.cpp

Enable Filecoin json protobuf signing

---

.github/auto_assign.yml

To get notified for new incoming pull requests - best practice to auto assign reviewers

[PR] Add auto assign reviewers to pull requests

---

include/TrustWalletCore/TWBitcoinScript.h
src/Bitcoin/Script.cpp
src/Bitcoin/Script.h
src/Bitcoin/TransactionSigner.cpp
src/Decred/Signer.cpp
src/interface/TWBitcoinScript.cpp
tests/Bitcoin/BitcoinScriptTests.cpp
tests/Bitcoin/TWBitcoinScriptTests.cpp
tests/Bitcoin/TWBitcoinSigningTests.cpp
tests/Groestlcoin/TWGroestlcoinSigningTests.cpp

New tests for Bitcoin Script.  One minor fix in Script::getScriptOp.
Partial for #932 .
Unit tests.
* New tests

Bitcoin Script minor fixes and new tests.

---

android/app/build.gradle
android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/fio/TestFIOAddress.kt
android/build.gradle
include/TrustWalletCore/TWFIOAccount.h
src/Cardano/AddressV3.h
src/FIO/Actor.cpp
src/FIO/Actor.h
src/FIO/Signer.cpp
src/FIO/Signer.h
src/FIO/TransactionBuilder.cpp
src/interface/TWFIOAccount.cpp
swift/Tests/Blockchains/FIOTests.swift
tests/FIO/SignerTests.cpp
tests/FIO/TWFIOAccountTests.cpp

Add TWFIOAccount

---

src/Bitcoin/UnspentSelector.cpp
tests/Bitcoin/UnspentSelectorTests.cpp

Extra tests for Bitcoin UnspentSelector UTXO selection.  Tests only.
Unit tests.
* New tests

(BTC) Extra tests for UnspentSelector UTXO selection

---

.github/workflows/android-ci.yml
android/app/build.gradle
android/trustwalletcore/build.gradle

`ndk-bundle` is always latest, decide to switch to `ndk;<version>`

Bump ndk version

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/tron/TestTronTransactionSigner.kt
src/Tron/Signer.cpp
src/proto/Tron.proto
tests/Tron/SerializationTests.cpp
tests/Tron/SignerTests.cpp

TransferTRC20 contract amount is 256 bits (not 64).  Issue #967 .
- Unit tests
- TRC contract test through app

TransferTRC20 contract amount is 256 bits

---

.gitignore
src/Bitcoin/TransactionSigner.cpp
tools/ios-test

iOS CI finished too quickly 2~3 mins (failed locally)

[iOS CI] Add clean to xcodebuild

---

README.md

Added FrontierWallet to Apps using Wallet-core list.
Readme Update

Added FrontierWallet to Readme

---

src/Cbor.cpp
tests/CborTests.cpp

Extra CBOR tests for coverage.
* Extra tests only.

[Testonly] Extra Cbor tests for coverage.

---

.github/workflows/android-release.yml

Migrate android releases pipeline to github actions

---

.github/workflows/android-ci.yml
.github/workflows/android-release.yml
.github/workflows/ios-ci.yml
.github/workflows/ios-release.yml
.github/workflows/linux-ci.yml
tools/ios-release

Migrate iOS build from s3 to release/assets

---

swift/Sources/SecRandom.m

Fix compile warning: unused variable 'status' 

---

src/PrivateKey.cpp
src/PublicKey.cpp
src/PublicKey.h
src/interface/TWPublicKey.cpp
tests/Bitcoin/TWBitcoinAddressTests.cpp
tests/PrivateKeyTests.cpp
tests/PublicKeyTests.cpp
tests/interface/TWPrivateKeyTests.cpp
tests/interface/TWPublicKeyTests.cpp

New tests:
- TWBitcoinAddressTests
- TWPrivateKey
- PrivateKey
- TWPublicKey
* New tests
* Minor non-breaking fix

[Tests] New TWBitcoinAddressTests.

---

tools/ios-release

zip LICENSE for podspec

---

CMakeLists.txt

Make: treat warnings as error, in order to enforce current zero-warning state.
Add a warning to the code (e.g. "int x = 0;" will generate unused var warning), compile.  Should fail.
* Build parameters, test only.

Remove unneeded warning flags

---

tests/interface/TWBase58Tests.cpp
tests/interface/TWDataTests.cpp
tests/interface/TWTestUtilities.h

Extra TWData and TWBase58 tests.
Standard unit tests, coverage.
* Extra tests only.

[TestOnly] TWData and TWBase58 tests

---

codegen/lib/templates/CoinInfoData.cpp.erb
include/TrustWalletCore/TWCurve.h
src/HDWallet.cpp
src/PrivateKey.cpp
src/interface/TWHDVersion.cpp
tests/HDWalletTests.cpp
tests/interface/TWHDWalletTests.cpp
tests/interface/TWTestUtilities.h

Added new/more HDWallet tests, some code cleanup: remove some unreachable branches, add error checks.
* Code cleanup, New tests

HDWallet tests and code cleanup

---

include/TrustWalletCore/TWAES.h
include/TrustWalletCore/TWAESPaddingMode.h
src/Encrypt.cpp
src/Encrypt.h
src/FIO/Encryption.cpp
src/interface/TWAES.cpp
swift/Tests/AESTests.swift
swift/Tests/CoinTypeTests.swift
tests/EncryptTests.cpp
tests/interface/TWAESTests.cpp

Add TWAESPaddingMode and tests

---

swift/Playground.playground/Contents.swift
swift/Playground.playground/contents.xcplayground

After building `TrustWalletCore`, add `Playground.playground` to `swift/TrustWalletCore.xcworkspace`

Add swift playground

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/elrond/TestElrondSigner.kt
src/Elrond/Serialization.cpp
src/proto/Elrond.proto
swift/Tests/Blockchains/ElrondTests.swift
tests/Elrond/SerializationTests.cpp
tests/Elrond/SignerTests.cpp
tests/Elrond/TWAnySignerTests.cpp

Added two new fields to the `Transaction` message:
- chain ID (will be set to a friendly name of the main network)
- version (the transaction version)
Furthermore, we've slightly changed the encoding logic around the `data` field of the Transaction.

Elrond: update signing procedure

---

protobuf-plugin/CMakeLists.txt

Fixes #1055 verified by pr: https://github.com/trustwallet/wallet-core/pull/1056

Fix docker build

---

codegen/lib/templates/CoinInfoData.cpp.erb
src/Coin.cpp
tests/CoinAddressDerivationTests.cpp

Coin dispatchers are set up at startup, and this was not thread-safe.  When started in multiple threads in short time, that could cause crash, like #1049 .  Should fix #1049 .
Unit tests.

Add locking to setting up dispatchers.

---

coins.json
docs/coins.md
tests/Elrond/TWCoinTypeTests.cpp

We've changed the token symbol from ERD to eGLD.

Elrond: change the token symbol

---

src/interface/TWAnyAddress.cpp
swift/Sources/Extensions/AddressProtocol.swift
swift/Tests/Blockchains/DecredTests.swift
swift/Tests/Blockchains/EOSTests.swift
swift/Tests/Blockchains/KusamaTests.swift
swift/Tests/Blockchains/NEARTests.swift
swift/Tests/Blockchains/PolkadotTests.swift
tests/interface/TWAnyAddressTests.cpp

Expose NEAR public key data from AnyAddress

---

src/Aion/Signer.cpp
src/Aion/Transaction.cpp
src/Aion/Transaction.h
src/proto/Aion.proto
swift/Tests/Blockchains/AionTests.swift
tests/Aion/SignerTests.cpp
tests/Aion/TWAnySignerTests.cpp
tests/Aion/TransactionTests.cpp

[Aion] remove hardcoded timestamp

---

android/app/build.gradle
android/trustwalletcore/build.gradle

Android build: limit debug build to x86 abi, to speed up build.
Fixes #975 .
CI time reduced from over 30 minutes to about 16.
./tools/android-test
* Process change (non-breaking, testing process)

[WIP] Android CI build speedup

---

include/TrustWalletCore/TWEthereumChainID.h
tests/BinanceSmartChain/SignerTests.cpp

From: https://docs.binance.org/smart-chain/developer/rpc.html#mainnetchainid-56

Update Smart Chain mainnet chain id

---

README.md

Frontier Wallet has rebranded to Frontier.
NA
Non-breaking README change.

Frontier Wallet is now Frontier

---

coins.json
tests/BinanceSmartChain/TWCoinTypeTests.cpp

Update bsc display name

---

.github/workflows/ts-ci.yml
.github/workflows/ts-release.yml
android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt
android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/binancesmartchain/TestBinanceSmartChainAddress.kt
codegen/bin/coins
coins.json
docs/coins.md
include/TrustWalletCore/TWCoinType.h
src/Ethereum/Entry.h
src/interface/TWAnyAddress.cpp
swift/Tests/Blockchains/BinanceSmartChainTests.swift
swift/Tests/CoinAddressDerivationTests.swift
swift/Tests/Keystore/KeyStoreTests.swift
tests/BinanceSmartChain/SignerTests.cpp
tests/BinanceSmartChain/TWAnyAddressTests.cpp
tests/BinanceSmartChain/TWCoinTypeTests.cpp
tests/Keystore/StoredKeyTests.cpp
tests/interface/TWHDWalletTests.cpp
typescript/codegen/bin/codegen
typescript/codegen/templates/core_types.ejs
typescript/package.json
typescript/tests/index.test.ts
typescript/tools/set-tag-version

Set typescript package release tag

---

samples/cpp/sample.cpp

Fix error in TWHDWalletGetKey call

little cpp sample fix

---

CMakeLists.txt
cmake/Protobuf.cmake
trezor-crypto/CMakeLists.txt
walletconsole/CMakeLists.txt

Add install directives in cmake files.
Hierarchy:
```
├── bin
│   └── walletconsole
├── include
│   ├── protobuf
│   ├── TrezorCrypto
│   ├── TrustWalletCore
│   └── WalletCore
└── lib
├── libprotobuf.a
├── libTrezorCrypto.a
└── libTrustWalletCore.a
```
TrustWalletCore, TrezorCrypto headers directory for fully using library from cpp project.
make DESTDIR=${PWD} install
find usr/local/

add install directives in cmake

---

docs/coins.md
src/Bitcoin/TransactionBuilder.cpp
src/Bitcoin/UnspentSelector.h
src/proto/Bitcoin.proto
tests/Bitcoin/TWBitcoinSigningTests.cpp

Multi-output BTC TX PR #1103 was put on hold, some non-functional minor improvements are worth taking over.
- Extra comments and ID renumbering in Bitcoin.proto
- Some extra const's added
- Extra Bitcoin signing tests, low-level 3-output (BitcoinSigning.EncodeThreeOutput)
Standard unti tests.
* Non-functional code improvement

Minor non-functional improvements from #1103 (btc proto)

---

src/Filecoin/Signer.cpp
src/Filecoin/Transaction.cpp
src/Filecoin/Transaction.h
src/proto/Filecoin.proto
swift/Tests/Blockchains/FilecoinTests.swift
tests/Filecoin/SignerTests.cpp
tests/Filecoin/TWAnySignerTests.cpp
tests/Filecoin/TransactionTests.cpp

Updates Filecoin ABI, adding gasFeeCap and gasLimit
Fixes #1036 
CI, manually sending generated txs on space race network.
Test fixtures here: https://github.com/terorie/filecoin-trustwallet-fixtures
Upgrades Filecoin "message" ABI to latest network changes

upgrade Filecoin ABI (again again)

---

docs/coins.md
src/Binance/Serialization.cpp
src/proto/Binance.proto
tests/Binance/SignerTests.cpp

In the recently-added Binance Timelock messages, the amount should not be a single amount, but an array of symbol-amount pairs.  Fixes #1110 .
Unit tests, `*Binance*`.

Change type of amount in Binance Timelock messages.

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt
android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/near/TestNEARAddress.kt
include/TrustWalletCore/TWNEARAccount.h
src/FIO/Actor.cpp
src/NEAR/Account.cpp
src/NEAR/Account.h
src/NEAR/Address.cpp
src/NEAR/Address.h
src/NEAR/Entry.cpp
src/NEAR/Entry.h
src/interface/TWAnyAddress.cpp
src/interface/TWNEARAccount.cpp
swift/Tests/Blockchains/NEARTests.swift
swift/Tests/CoinAddressDerivationTests.swift
swift/Tests/Keystore/Data/bnb_wallet.json
swift/Tests/Keystore/KeyStoreTests.swift
tests/CoinAddressDerivationTests.cpp
tests/CoinAddressValidationTests.cpp
tests/NEAR/AccountTests.cpp
tests/NEAR/AddressTests.cpp
tests/NEAR/TWNEARAccountTests.cpp

Fixes https://github.com/trustwallet/wallet-core/issues/1115

Add NEAR account

---

docs/coins.md

Change Smartchain folder to correct smartchain (instead of bsc).
Related to #1128 .
n.a.
* Documentation only

[Doc-only] Change Smartchain folder to correct smartchain (instead of bsc).

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/kava/TestKavaTransactions.kt

formatted json
```
{
"mode": "block",
"tx": {
"fee": {
"amount": [{
"amount": "100",
"denom": "ukava"
}],
"gas": "200000"
},
"memo": "",
"msg": [{
"type": "withdraw_cdp",
"value": {
"collateral": {
"amount": "1000",
"denom": "bnb"
},
"collateral_type": "bnb-a",
"depositor": "kava1hsk6jryyqjfhp5dhc55tc9jtckygx0ept0esed",
"owner": "kava1hsk6jryyqjfhp5dhc55tc9jtckygx0ept0esed"
}
}],
"signatures": [{
"pub_key": {
"type": "tendermint/PubKeySecp256k1",
"value": "AlcobsPzfTNVe7uqAAsndErJAjqplnyudaGB0f+R+p3F"
},
"signature": "TF31bcLSUDiQFa2Ul6AOuMsmQnPq0OfsSto+6AXhCIUETEZQRIXoK1BqyGeTjIKnJrkg/Jo4SOONJQKx2rDFIg=="
}]
}
}
```

Add kotlin kava raw json msg test

---

src/Coin.h

Correct the comment

---

coins.json
tests/Tezos/TWCoinTypeTests.cpp

[Tezos] Switch block explorer to tzstats.com

---

src/Zilliqa/Signer.cpp
src/proto/Zilliqa.proto
swift/Podfile.lock
swift/Tests/Blockchains/ZilliqaTests.swift
tests/Ethereum/Data/zilliqa_data_tx.json
tests/Zilliqa/SignerTests.cpp
tests/Zilliqa/TWAnySignerTests.cpp

[Zilliqa] Refactor proto

---

src/PrivateKey.cpp
tests/PrivateKeyTests.cpp

Extra check in PrivateKey::sign() for the case if digest is short
Unit tests

Signing: Safeguard for short digest case.

---

coins.json
tests/Zcoin/TWCoinTypeTests.cpp

[Zcoin] Rename zcoin display name, symbol and other info

---

android/app/build.gradle
android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties
android/trustwalletcore/build.gradle
coins.json
docs/coins.md
include/TrustWalletCore/TWBitcoinAddress.h
tests/Filecoin/TWCoinTypeTests.cpp

[Filecoin] Update block explorer

---

android/app/build.gradle
android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/aeternity/TestAeternitySigner.kt
android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/cardano/TestCardanoAddress.kt
android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/elrond/TestElrondSigner.kt
android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/filecoin/TestFilecoin.kt
android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/kusama/TestKusamaSigner.kt
android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/neo/TestsNEOSigner.kt
android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/nuls/TestNULSSigner.kt
android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/polkadot/TestPolkadotSigner.kt
codegen/lib/templates/newcoin/SignerTests.kt.erb

[Android] Update sdk and warnings fixes

---

src/Solana/Transaction.cpp

Fix for minor memory leak fix, exception.
See https://github.com/trustwallet/wallet-core/runs/1524721270?check_suite_focus=true 
Linux CI on master branch.

Fix for minor memory leak fix, exception.

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/solana/TestSolanaSigner.kt
src/Solana/Signer.cpp
src/Solana/Transaction.h
src/proto/Solana.proto
swift/Tests/Blockchains/SolanaTests.swift
tests/Solana/TWAnySignerTests.cpp

Add CreateAndTransferToken combined message.  Fixes #1215 .
Unit tests, cpp/Swift/Kotlin test added.

Add CreateAndTransferToken combined message.

---

.gitignore
.gitpod.yml
README.md
gitpod.Dockerfile

Gitpod provides cloud vscode (or theia) + docker container, no need to setup dev env locally

Gitpod setup

---

tests/Bitcoin/TransactionPlanTests.cpp
tests/Bitcoin/UnspentSelectorTests.cpp

Add extra tests for BTC fee estimation / UTXO selection.  Tests only, no prod code change.
* New tests

[Testonly] Extra BTC fee handling tests

---

src/Polkadot/Extrinsic.cpp
src/Polkadot/Extrinsic.h
src/proto/Polkadot.proto
tests/Polkadot/SignerTests.cpp

Refreshed Polkadot staking/transaction test messages.  Fixes #1243 and fixes https://github.com/trustwallet/wallet-core/issues/1079
Test change only.
Unit tests.  Check mentioned TXs in Polkadot explorer.

Update Polkadot staking messages

---

src/Bitcoin/UnspentSelector.cpp
tests/Bitcoin/TransactionPlanTests.cpp

BTC plan(): Optimize for lots-of-UTXOs case, by skipping checks for UTXO subsets of sizes that cannot give enough output.
Fixes #1274 .
Unit tests.  `--gtest_filter=*Plan.Lo*`

BTC plan(): Optimize for lots-of-UTXOs case.

---

src/HDWallet.cpp
src/PublicKey.cpp
src/Solana/Address.cpp
src/Solana/Program.cpp
tests/PrivateKeyTests.cpp
tests/interface/TWHDWalletTests.cpp
trezor-crypto/crypto/bip32.c
trezor-crypto/crypto/bip39.c
trezor-crypto/crypto/ed25519-donna/curve25519-donna-32bit.c
trezor-crypto/crypto/ed25519-donna/curve25519-donna-helpers.c
trezor-crypto/crypto/ed25519-donna/curve25519-donna-scalarmult-base.c
trezor-crypto/crypto/ed25519-donna/ed25519-donna-32bit-tables.c
trezor-crypto/crypto/ed25519-donna/ed25519-donna-basepoint-table.c
trezor-crypto/crypto/ed25519-donna/ed25519-donna-impl-base.c
trezor-crypto/crypto/ed25519-donna/ed25519.c
trezor-crypto/crypto/ed25519-donna/modm-donna-32bit.c
trezor-crypto/crypto/tests/test_check.c
trezor-crypto/crypto/tests/test_check_cardano.h
trezor-crypto/include/TrezorCrypto/bip32.h
trezor-crypto/include/TrezorCrypto/bip39.h
trezor-crypto/include/TrezorCrypto/ed25519-donna/ed25519-donna.h
trezor-crypto/include/TrezorCrypto/monero/xmr.h

Some small changes paving the way for Trezor update.  No change in Trezor code, no change in behavior.
- extend HDWallet mnemonic tests; capture various mnemonic lengths: 12-, 15-, 18-, 21- and 24-words long, casing and extra spaces.
- move header file ed25519-donna.h to subfolder ed25519-donna .
- rename of mnemonic_to_entropy() to mnemonic_to_bits()
- rename of hdnode_from_seed_cardano to hdnode_from_entropy_cardano_icarus()
Unit tests, wallet-core and TrezorCryptoTests .
* Non-functional (non-breaking change, no change in functionality)

Minor Trezor changes; preparation for Trezor update

---

src/Polkadot/Extrinsic.cpp
src/Polkadot/Extrinsic.h
src/Polkadot/ScaleCodec.h
src/SS58Address.h
swift/Tests/Blockchains/PolkadotTests.swift
tests/Polkadot/ScaleCodecTests.cpp
tests/Polkadot/SignerTests.cpp

[Polkadot] prepare for MultiAddress::AccountId

---

.github/workflows/linux-ci.yml
android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties

https://github.com/actions/virtual-environments/issues/2667

[CI] Install boost from default repositories

---

coins.json
tests/Zelcash/TWCoinTypeTests.cpp

Rebrant Zelcash (Zel) to Flux
Change list:
- new explorer
- new symbol
- new name
- new url

[ZelCash] Flux Rebrand

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/polkadot/TestPolkadotSigner.kt
include/TrustWalletCore/TWHDWallet.h
src/Polkadot/Extrinsic.cpp
swift/Tests/Blockchains/PolkadotTests.swift
tests/Polkadot/SignerTests.cpp

Fixes https://github.com/trustwallet/wallet-core/issues/1414

[Polkadot] Use atomic `batch_all` and update tests

---

.gitignore
android/build.gradle
samples/osx/cocoapods/Podfile
samples/osx/cocoapods/Podfile.lock
src/Bitcoin/Transaction.cpp
src/Bitcoin/TransactionSigner.cpp
src/Bitcoin/TransactionSigner.h
src/KeyPair.h
swift/Sources/Extensions/Data+Hex.swift
swift/Tests/Blockchains/BitcoinTests.swift
swift/Tests/Blockchains/BitconCashTests.swift
swift/Tests/Blockchains/DecredTests.swift
swift/Tests/Blockchains/LitecoinTests.swift
tests/Bitcoin/TWBitcoinSigningTests.cpp
tests/Decred/SignerTests.cpp

[Bitcoin] Redeem utxos locked by uncompressed public key hash

---

.github/workflows/linux-ci.yml

[CI] Set default Clang version to 10

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt

Fixed the test as reported in #1548
`tools/android-test`

[TestOnly] #1458 -> Removed GlobalScope.launch for running tests

---

coins.json
include/TrustWalletCore/TWEthereumChainID.h
tests/Polygon/TWCoinTypeTests.cpp

Update and fix block explorer url

[Polygon] Add missing coin type tests

---

android/app/src/androidTest/java/com/trustwallet/core/app/utils/TestMnemonic.kt
src/Mnemonic.cpp
swift/Tests/MnemonicTests.swift

Fixes https://github.com/trustwallet/wallet-core/issues/1486

[Mnemonic] Fix word validation

---

tests/Ethereum/AbiStructTests.cpp

Fix for AbiStructTest C++ tester compile issue on master, resulting from overlapping changes between master (EIP2178) and branch (EIP712) changes.
CI builds, unit tests.

Master compile fix

---

swift/Sources/Extensions/Data+Hex.swift
swift/Tests/DataTests.swift

Data(hexString:) fails if input string contains non-hex characters.

Validate hex characters in Data initializer

---

src/Ethereum/ABI/Bytes.cpp
src/Ethereum/ABI/Bytes.h
tests/Ethereum/AbiStructTests.cpp

Eip encoding: Fix for Bytes type hash
Unit tests, `*EthereumAbi*`.

Eip encoding: Fix for Bytes type hash

---

README.md
android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt
android/build.gradle
codegen/bin/coins
codegen/bin/cointests
codegen/bin/newcoin
codegen/lib/coin_test_gen.rb
codegen/lib/templates/hrp.cpp.erb
codegen/lib/templates/registry.md.erb
docs/registry.md
include/TrustWalletCore/TWCoinType.h
include/TrustWalletCore/TWEthereumChainID.h
registry.json
src/Coin.cpp
src/Ethereum/Entry.h
src/interface/TWAnyAddress.cpp
swift/Tests/CoinAddressDerivationTests.swift
tests/Arbitrum/TWCoinTypeTests.cpp
tests/HECO/TWCoinTypeTests.cpp
tests/Optimism/TWCoinTypeTests.cpp
tests/THORChain/TWCoinTypeTests.cpp
tools/generate-files

Rename `coins.json` to `registry.json`, add more EVM chains (L2 or standalone network).
The rule of `coinId`:
1. `10000000` + unique SLIP44 id (if it has)
2. `10000000` + ETH SLIP44 id + chain id

Add Optimism / Arbitrum / Heco to registry

---

registry.json
tests/Solana/TWCoinTypeTests.cpp

Change Solana explorer to solscan.io.  Fixes #1541 
Unit tests

[Minor] Solana: Change explorer to solscan.io

---

include/TrustWalletCore/TWBitcoinScript.h
src/Bitcoin/Script.cpp
src/Bitcoin/Script.h
src/interface/TWBitcoinScript.cpp
tests/Bitcoin/BitcoinScriptTests.cpp
tests/Bitcoin/TWBitcoinScriptTests.cpp
tests/Bitcoin/TWBitcoinSigningTests.cpp

Additional signing test(s) from the BIP143 spec.
Added Script::buildPayToPublicKey().
Unit test, `*Bitcoin*`.
* Minor new feature (non-breaking change which adds functionality)
* New tests

Additional P2WPKH test from BIP143, Add buildPayToPublicKey

---

src/Bitcoin/Address.h
tests/Bitcoin/BitcoinAddressTests.cpp

Add doc/clarification to Bitcoin::Address class, plus C++ tests.  Related to #1551 .
Unit tests, `*BitcoinAddress*`.
* New tests

[TestOnly] Legacy Bitcoin address: Add clarification doc and tests

---

tests/interface/TWAnyAddressTests.cpp

Add a test for validity of Taproot (Segwit v1, Bech32m) address, through the AnyAddress interface.  Test vectors from BIP350.
Unit tests, `*AnyAddress*`.
* New test

[TestOnly] Add AnyAddress test for Taproot address

---

.github/workflows/android-ci.yml
android/build.gradle
samples/android/app/build.gradle
samples/android/app/src/main/java/com/trust/walletcore/example/MainActivity.kt
samples/android/build.gradle
samples/android/gradle/wrapper/gradle-wrapper.properties

Fixes https://github.com/trustwallet/wallet-core/issues/1577

Update android sample with latest wallet core build

---

swift/fastlane/Fastfile

continue https://github.com/trustwallet/wallet-core/pull/1592, fixes https://github.com/trustwallet/wallet-core/issues/1595

[iOS] Remove not used types framework from Fastfile

---

src/interface/TWAnyAddress.cpp
swift/Tests/Blockchains/AvalancheTests.swift

continue https://github.com/trustwallet/wallet-core/pull/1592

[Avalanche] Add c-chain data tests

---

samples/cpp/sample.cpp

In the CPP sample app, fix Json input for Eth transaction creation/signing.  Fixes #1627 .
Build & run sample app
https://github.com/trustwallet/wallet-core/tree/master/samples/cpp#readme
and decode it (e.g using https://flightwallet.github.io/decode-eth-tx/); all fields should be set.

[Sample app] Fix Json input for Eth transaction creation/signing

---

src/HDWallet.cpp
src/HDWallet.h
tests/HDWalletTests.cpp

Remove unneeded assert in HDWallet, check=false case.  Also add more tests with invalid mnemonic, empty mnemonic, check true/false.
Unit test.

Remove unneeded assert in HDWallet

---

registry.json
tests/Terra/TWCoinTypeTests.cpp

Latest will be columbus-5 https://twitter.com/terra_money/status/1432927061849427968

[Terra] Update terra block explorer

---

src/Base58.cpp
src/Bitcoin/Script.cpp
src/Ontology/ParamsBuilder.cpp
src/PrivateKey.cpp
src/PublicKey.cpp
src/Solana/Signer.cpp
src/interface/TWBitcoinScript.cpp

Got it building under VS on Windows.
Still cleaning things up, so I'll just be doing pull requests one at a time for changes that are clean.

Include required missing headers to compile under Visual Studio

---

swift/project.yml

[iOS] Ignore interna Cosmos protos

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt
android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/osmosis/TestOsmosisAddress.kt
android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/osmosis/TestOsmosisSigner.kt
docs/registry.md
include/TrustWalletCore/TWCoinType.h
registry.json
src/Coin.cpp
src/Cosmos/Entry.h
src/interface/TWAnyAddress.cpp
swift/Tests/Blockchains/OsmosisTests.swift
swift/Tests/CoinAddressDerivationTests.swift
tests/Osmosis/AddressTests.cpp
tests/Osmosis/SignerTests.cpp
tests/Osmosis/TWAnyAddressTests.cpp
tests/Osmosis/TWAnySignerTests.cpp
tests/Osmosis/TWCoinTypeTests.cpp
tests/interface/TWHRPTests.cpp

Osmosis support.  New chain, Cosmos-based.  Address and OSMO transfer supported.  Swap is not handled in this PR.
Fixes #1672 .
Osmo unit tests.
Get some Osmo using Osmosis app, and create transfer TX to another address.

Initial Osmosis support, Address support

---

.github/workflows/ios-ci.yml

Seems not working, wait for better solution from GitHub

[CI] Revert iOS concurrency config

---

README.md

Fixes https://github.com/trustwallet/wallet-core/issues/1797, we might not merge them into master but we still appreciate community's efforts

Add community projects

---

.github/workflows/ios-ci.yml
android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt
registry.json
swift/Tests/CoinAddressDerivationTests.swift
tools/ios-test

[Celo] Update derivation path

---

registry.json
tests/Cosmos/TWCoinTypeTests.cpp
tests/Kava/TWCoinTypeTests.cpp
tests/Osmosis/TWCoinTypeTests.cpp

Fixes https://github.com/trustwallet/wallet-core/issues/1826, also changed kava/osmosis format

[Cosmos] Update explorer link

---

.github/workflows/linux-ci.yml
samples/cpp/CMakeLists.txt
samples/cpp/sample.cpp

Currently sample app building fails, if not Clang is picked. It fails on Ubuntu, where gcc is chosen.
Add step to Linux CI to build and run sample cpp app.

Add step to CI to build sample cpp app

---

.github/workflows/linux-ci.yml
samples/cpp/CMakeLists.txt

Fix CI on master branch; Fix compilation issue of CPP sample app, related to ASAN.  Fixes #1850 . 
CI build on master branch!

Fix CI on master branch; sample app/ASAN 

---

.github/workflows/linux-sampleapp-ci.yml
samples/cpp/CMakeLists.txt

Fixes https://github.com/trustwallet/wallet-core/issues/1851

Link pthread for cpp sample

---

src/Algorand/Transfer.cpp
swift/Tests/Blockchains/AlgorandTests.swift

Fixes https://github.com/trustwallet/wallet-core/issues/1888, don't encode 0 amount

[Algorand] Fix sending 0 amount issue

---

src/Ripple/Signer.cpp
src/proto/Common.proto
src/proto/Ripple.proto
tests/Ripple/TWAnySignerTests.cpp

Fixes https://github.com/trustwallet/wallet-core/issues/1895

[XRP] Return sign error tag is invalid

---

registry.json
tests/Nano/TWCoinTypeTests.cpp

From https://medium.com/@nanocurrency/say-hello-to-xno-7ed55e419e3f

[Nano] Update XNO symbol

---

swift/common-xcframework.yml

Continue of https://github.com/trustwallet/wallet-core/pull/1903, add missing changes

Fix linking error for CocoaPods build

---

codegen/bin/coins
codegen/lib/templates/CoinInfoData.cpp.erb
codegen/lib/templates/registry.md.erb
docs/registry.md
registry.json
tests/xDai/TWCoinTypeTests.cpp

xDai rebranded to Gnosis Chain

Rename xDai to Gnosis Chain

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/terra/TestTerraTransactions.kt
src/Cosmos/JsonSerialization.cpp
src/Cosmos/Protobuf/terra_wasm_v1beta1_tx.proto
src/Cosmos/ProtobufSerialization.cpp
src/Cosmos/ProtobufSerialization.h
src/proto/Cosmos.proto
swift/Tests/Blockchains/TerraTests.swift
tests/Terra/SignerTests.cpp

Terra WC20 token support.  Fixes #1876 .
Terra unit tests.  Adapt a sending test to a wallet with some ANC and LUNA, and broadcast resulting tx.

Terra CW20 token support

---

src/Solana/Signer.cpp
src/Solana/Transaction.h
src/proto/Solana.proto
tests/Solana/SignerTests.cpp
tests/Solana/TWAnySignerTests.cpp
tests/Solana/TransactionTests.cpp

Solana: Support Memo field in transfer.  Fixes #1988
- Optional Memo in (native) transfer
- Optional Memo in token transfer
- Optional References in transfers
Solana unit tests.

Solana: Memo & References in transfer

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt
docs/registry.md
include/TrustWalletCore/TWCoinType.h
registry.json
src/Bitcoin/Entry.cpp
src/Bitcoin/Entry.h
src/Coin.cpp
src/Ethereum/Address.h
src/interface/TWAnyAddress.cpp
swift/Tests/Blockchains/ZcoinTests.swift
swift/Tests/CoinAddressDerivationTests.swift
swift/Tests/HDWalletTests.swift
tests/CoinAddressDerivationTests.cpp
tests/CoinAddressValidationTests.cpp
tests/Firo/TWCoinTypeTests.cpp
tests/Firo/TWZCoinAddressTests.cpp
tests/interface/TWHRPTests.cpp

From https://github.com/trustwallet/wallet-core/issues/1927#issuecomment-1030441638

[Firo] Change id to match assets repo

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt
codegen/bin/newcoin
docs/registry.md
include/TrustWalletCore/TWCoinType.h
include/TrustWalletCore/TWEthereumChainID.h
registry.json
src/Coin.cpp
src/Ethereum/Entry.h
swift/Tests/CoinAddressDerivationTests.swift
tests/Cronos/TWCoinTypeTests.cpp

Fixes https://github.com/trustwallet/wallet-core/issues/2015

Add Cronos to registry

---

include/TrustWalletCore/TWPBKDF2.h
src/interface/TWPBKDF2.cpp
swift/Tests/PBKDF2Tests.swift
tests/interface/TWPBKDF2Tests.cpp

Fixes https://github.com/trustwallet/wallet-core/issues/1522

Add TWPBKDF2 C interface

---

include/TrustWalletCore/TWTransactionCompiler.h

TWTransactionCompiler only has static methods, and it is not an
object, so change ti to struct, and then wallet-core-python can
parse wallet-core header correctly.

Change TWTransactionCompiler to struct

---

trezor-crypto/crypto/sha3.c

Fixes #2082 , compile error on macOS.
Build library on macOS with SDK v 12.3.

Fix macOS 12.3 SDK `pointer-to-numerical conversion` compile error

---

docs/registry.md
include/TrustWalletCore/TWAccount.h
include/TrustWalletCore/TWStoredKey.h
registry.json
src/Keystore/Account.cpp
src/Keystore/Account.h
src/Keystore/StoredKey.cpp
src/Keystore/StoredKey.h
src/interface/TWAccount.cpp
src/interface/TWStoredKey.cpp
swift/Sources/Extensions/Account+Codable.swift
swift/Tests/Keystore/KeyStoreTests.swift
tests/Cosmos/TWCoinTypeTests.cpp
tests/Keystore/StoredKeyTests.cpp
tests/interface/TWStoredKeyTests.cpp

Fixes https://github.com/trustwallet/wallet-core/issues/2051
Changes:
- Expose `publicKey` to keystore
- Fix some typos
- Update Cosmos display name

Expose public key for account

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/thorchain/TestTHORChainSigner.kt
src/Cosmos/Protobuf/thorchain_bank_tx.proto
src/Cosmos/ProtobufSerialization.cpp
src/proto/Cosmos.proto
tests/Bitcoin/InputSelectorTests.cpp
tests/THORChain/SignerTests.cpp

Instead of the legacy Json serialization (which is currently outdated, see #2089), support protobuf serialized Cosmos messages (Stargate).
Note that Thorchain uses its own message format (from and to addresses are bytes-encoded instead of string (contain key hashes instead of string address), and own type).
Fixes #2089 .
Note: Thorchain-specific message is included within Cosmos (along with a Terra-specific message), separating out is not trivial; addressed in #2093 .
Thorchain unit tests, Thorchain RUNE transfers.

[Thorchain] Support protobuf serialization messages (Stargate)

---

swift/Sources/Extensions/Account+Codable.swift
swift/Tests/Blockchains/THORChainTests.swift

Changes: 
1. Update swift test
2. Handle more `publicKey` cases in `Account+Codable.swift`

Update thorchain swift test

---

src/AnyAddress.h
src/Cardano/AddressV3.h
swift/Tests/Blockchains/CronosTests.swift
tests/Cronos/TWAnyAddressTests.cpp

It was missing from `AnyAddress.h`, tests added

Fix Cronos address data

---

.github/workflows/stale.yml

Add labels to exempt from stale bot

---

tests/interface/TWTransactionCompilerTests.cpp

fix TWTransactionCompiler unittest memleak issue

---

Package.swift

Bump SPM build to 2.7.8 on master

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt
docs/registry.md
include/TrustWalletCore/TWCoinType.h
include/TrustWalletCore/TWEthereumChainID.h
registry.json
src/AnyAddress.h
src/Coin.cpp
src/Ethereum/Entry.h
swift/Tests/CoinAddressDerivationTests.swift
tests/Boba/TWCoinTypeTests.cpp
tests/Oasis/TWCoinTypeTests.cpp

Add support for Boba chain. Boba is L2 chain. For more information, [visit the official site](https://boba.network/).
Test in same manner as other EVM chains.
New feature (non-breaking change which adds functionality

Add Boba Chain Support

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt
docs/registry.md
include/TrustWalletCore/TWCoinType.h
include/TrustWalletCore/TWEthereumChainID.h
registry.json
src/AnyAddress.h
src/Coin.cpp
src/Ethereum/Entry.h
swift/Tests/CoinAddressDerivationTests.swift
tests/Metis/TWCoinTypeTests.cpp

Adds support for Metis L2 Chain. For more information, [visit Metis official site](https://www.metis.io/).
Same as other EVM chains

Add Metis Chain Support

---

.github/workflows/stale.yml

multiple labels with space don't work

Update labels in stale.yml

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/terra/TestTerraTransactions.kt
src/Cosmos/JsonSerialization.cpp
src/Cosmos/Protobuf/terra_wasm_v1beta1_tx.proto
src/Cosmos/ProtobufSerialization.cpp
src/proto/Cosmos.proto
swift/Tests/Blockchains/TerraTests.swift
tests/Terra/SignerTests.cpp

Added `WasmMessageExecuteContractGeneric` for to execute any kind of smart contract calls in terra chain.
`./build/tests/tests tests`
`tools/android-test`
`tools/ios-test`
#2182 
Added Introduced `WasmMessageExecuteContractGeneric` proto model
✅  Prefix PR title with `[WIP]` if necessary.
✅ Add tests to cover changes as needed.
✅ Update documentation as needed.
🙅  I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain (not a new blockchain integration)
✅ If there is a related Issue, mention it in the description (e.g. Fixes #<issue_number> ).

Support for generic implementation of MsgExecuteContract for any kind of terra smart contract calls

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/cosmos/TestCosmosTransactions.kt
android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/kava/TestKavaTransactions.kt
android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/terra/TestTerraTransactions.kt
include/TrustWalletCore/TWStoredKey.h
src/interface/TWStoredKey.cpp

Expose derivation in `TWStoredKeyAddAccount`
Deprecate it in favor of a new version `TWStoredKeyAddAccountDerivation`, with derivation as additional parameter.
Leftover from #1816.
Unit tests.

Expose derivation in TWStoredKeyAddAccount

---

docs/registry.md
registry.json
tests/Binance/TWCoinTypeTests.cpp
tests/BinanceSmartChain/TWCoinTypeTests.cpp

Rename BNB chains, displayNames:
BNB -> BNB Beacon Chain
SmartChain -> BNB Smart Chain
Fixes #2023
* Non-breaking change

Rename BNB chains

---

include/TrustWalletCore/TWStoredKey.h
src/Keystore/StoredKey.cpp
src/Keystore/StoredKey.h
src/interface/TWStoredKey.cpp
tests/Keystore/StoredKeyTests.cpp
tests/interface/TWStoredKeyTests.cpp

Additional remove methods to StoredKey, to filter by derivation / derivationPath.
Fixes #2196 .
Unit tests `*StoredKey*`.

StoredKey: Add Remove method variants with derivation parameter

---

.github/PULL_REQUEST_TEMPLATE.md

Replace [WIP] with draft pull request

---

README.md
src/NEAR/Serialization.cpp
src/proto/NEAR.proto
tests/NEAR/SerializationTests.cpp

Support NEAR function calls. Fixes #2226 
NEAR unit tests.
Valid test result is generated with https://github.com/near/near-api-swift.

NEAR function calls

---

src/Bitcoin/Entry.cpp
tests/Litecoin/LitecoinAddressTests.cpp

fix litecoin legacy address not correct in deriveAddress

---

src/Ronin/Address.cpp
tests/Ronin/TWAnyAddressTests.cpp

Ronin accepts & normalizes Eth address as well

---

docs/registry.md
registry.json
tests/Terra/TWCoinTypeTests.cpp

Fixes https://github.com/trustwallet/wallet-core/issues/2245

[Terra] Rename classic name / symbol

---

swift/project.yml
tools/ios-xcframework-release

Fixes https://github.com/trustwallet/wallet-core/issues/2244

[SPM] zip and upload xcframework dSYMs

---

codegen/bin/newcoin
src/Binance/Entry.cpp

Fix for `newcoin` code generation utility, follow-up on #2258 .
Also minor change in Binance Entry, no chainId fallback value.
`codegen/bin/newcoin ethereum`

Fix for newcoin code generation

---

wasm/package-lock.json
wasm/package.json

Fixes dependent bot warning: Prototype Pollution in protobufjs

Bump protobufjs version

---

android/app/build.gradle
android/trustwalletcore/build.gradle

Trying to fix flaky Android CI

[Android] Revert split apk, update compileSdkVersion version

---

android/app/build.gradle
android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties
android/trustwalletcore/build.gradle
src/EOS/Transaction.cpp
src/EOS/Transaction.h
tests/EOS/TransactionTests.cpp

In EOS expiration date formatting:
- there is an error branch with an exception but missing `throw`
- length condition is wrong, so if is always triggered (but doesn't do anything)
EOS unit test

EOS date handling fix

---

android/app/build.gradle
android/trustwalletcore/build.gradle
src/AnyAddress.h

Fixes https://github.com/trustwallet/wallet-core/issues/2281, easier to add new cosmos sdk / evm chain

[AnyAddress] Switch by blockchain type first

---

src/Bitcoin/Amount.h
src/Bitcoin/CashAddress.cpp
src/Bitcoin/CashAddress.h

- Use inline variable instead of static const variable when possible
- noexcept
- refactor to respect DRY idiom
- use `nodiscard` for functions that should use their result
- do not use `strncmp` - use `string::compare` instead
- use braces initializer to initialize a variable
- use for the prefix a version and a switch case instead of if/elseif
- remove unused code
```bash
make -C build tests && build/tests/tests tests
```
Modernize code (use modern c++, improve readability, more safeness)

Modernize CashAddress code

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt
docs/registry.md
include/TrustWalletCore/TWCoinType.h
registry.json
src/AnyAddress.h
swift/Tests/CoinAddressDerivationTests.swift
tests/Moonbeam/TWCoinTypeTests.cpp
tests/Moonriver/TWCoinTypeTests.cpp

Adds Support for Moonbeam, and Moonriver.
Same way as other EVM chains

Adds Support for Moonbeam, and Moonriver

---

src/Bitcoin/Entry.cpp
src/Bitcoin/Entry.h

Format Entry.h and Entry.cpp
No Test required
Apply clang-format

[Format]: Bitcoin Entry

---

src/Bitcoin/InputSelector.cpp
src/Bitcoin/InputSelector.h

Format InputSelector.{h/cpp}
No Test required
Apply clang-format

[Format]: Bitcoin Input Selector

---

codegen/lib/templates/cpp/includes.erb
codegen/lib/templates/jni_c.erb

Fixes https://github.com/trustwallet/wallet-core/issues/2313

[Codegen] use `Set` for both ruby 2 and 3

---

codegen/bin/newcoin
codegen/lib/entity_decl.rb
codegen/lib/enum_decl.rb
codegen/lib/function_decl.rb
codegen/lib/parser.rb
codegen/lib/templates/java/class.erb
codegen/lib/templates/java/enum.erb
codegen/lib/templates/java/header.erb
codegen/lib/templates/java/struct.erb
codegen/lib/templates/swift/class.erb
codegen/lib/templates/swift/class_properties.erb
codegen/lib/templates/swift/enum.erb
codegen/lib/templates/swift/enum_extension.erb
codegen/lib/templates/swift/method.erb
codegen/lib/templates/swift/static_method.erb
codegen/lib/templates/swift/struct.erb
codegen/lib/templates/swift/struct_properties.erb
codegen/test/test_jni_helper.rb
codegen/test/test_parser.rb
include/TrustWalletCore/TWAES.h

Reverts trustwallet/wallet-core#2297

Revert "Codegen: preserve comments"

---

src/Ethereum/ABI/ParamFactory.cpp
src/Ethereum/ABI/ParamFactory.h
src/Ethereum/ABI/ParamStruct.cpp
swift/Tests/Blockchains/EthereumAbiTests.swift
tests/Ethereum/Data/seaport_712.json

Fixes https://github.com/trustwallet/wallet-core/issues/2323

[EIP712] Fix encode struct type order

---

src/Bitcoin/OutPoint.h

Format OutPoint.{h/cpp}
No Test required
Apply clang-format

[Format]: Bitcoin OutPoint

---

wasm/src/AnySigner.cpp

[CI] Fix binding symbol typo

---

src/Bitcoin/Entry.cpp
tests/BitcoinGold/TWSegwitAddressTests.cpp

fix btg addressToData not correct

---

src/Bitcoin/InputSelector.cpp
tests/algorithm/erase_tests.cpp
trezor-crypto/CMakeLists.txt
trezor-crypto/crypto/bignum.c

see https://github.com/trustwallet/wallet-core/pull/2331#issuecomment-1162423284

[Fix] bunch of fixes for cpp20 upgrade

---

Package.swift
samples/android/app/build.gradle
samples/android/app/src/main/AndroidManifest.xml
samples/android/build.gradle
samples/android/gradle/wrapper/gradle-wrapper.properties
samples/node/index.js
samples/node/package-lock.json
samples/node/package.json
samples/osx/cocoapods/Podfile.lock
samples/osx/cocoapods/WalletCoreExample.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist

Update package version for android / osx / node sample

Update various samples

---

include/TrustWalletCore/TWHDWallet.h
src/HDWallet.cpp
src/HDWallet.h
src/interface/TWHDWallet.cpp
swift/Tests/Blockchains/AvalancheTests.swift
tests/HDWallet/HDWalletTests.cpp
tests/interface/TWHDWalletTests.cpp

Fixes https://github.com/trustwallet/wallet-core/issues/2334

Fix building derivationPath for xpub

---

src/Bitcoin/InputSelector.cpp
tools/install-wasm-dependencies

Revert for: #2344 , introduced in https://github.com/trustwallet/wallet-core/pull/2305
run unit tests
Should fix #2344 will re-open the improvements as a draft for further research

Revert InputSelector.cpp until further research

---

registry.json
tests/Avalanche/TWCoinTypeTests.cpp

Update registry.json and Avax C Chain unit test.
resolve #2119 
run Avax coin test
update meta-data informations

[Blockchain]: Update Avax C-Chain explorer

---

.clang-format
src/Bitcoin/Transaction.cpp
src/Keystore/StoredKey.cpp
src/Polkadot/Extrinsic.cpp
src/PublicKey.cpp

Fixes #2351 
Format
Interesting reading:
- https://stackoverflow.com/questions/33607284/control-reaches-end-of-non-void-function-with-fully-handled-case-switch-over-a
- https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0627r0.pdf
Run unit tests

Fix Non-void return type missing warnings

---

src/NEAR/Serialization.cpp
src/proto/NEAR.proto
tests/NEAR/SerializationTests.cpp
tests/NEAR/TWAnySignerTests.cpp

Support Near actions: stake, add key, delete key, create account, delete account 
unit test already write at:  tests/NEAR/SerializationTests.cpp

[NEAR] Add stake / add key / delete key / create account / delete account

---

android/app/src/androidTest/java/com/trustwallet/core/app/utils/TestBase32.kt
include/TrustWalletCore/TWBase32.h
src/interface/TWBase32.cpp
swift/Tests/Base32Tests.swift
tests/interface/TWBase32Tests.cpp
wasm/tests/AES.test.ts
wasm/tests/Base32.test.ts

implements #2120 
Todo: 
- run c++ unit test
- run wasm tests
- run type script tests
- run swift tests

[Feature]: Base32 to C interface

---

src/Base64.cpp
src/Bitcoin/SigningInput.cpp
src/Bitcoin/TransactionBuilder.h
src/Cbor.cpp
src/Decred/Transaction.cpp
src/EOS/Name.h
src/Ethereum/RLP.cpp
src/Filecoin/Address.cpp
src/NEO/ReadData.h
src/Polkadot/SS58Address.h
src/Result.h
src/Solana/Program.cpp
src/Solana/Signer.cpp
src/Solana/Transaction.h
src/TransactionCompiler.cpp
src/Waves/Address.cpp

Fix all 22 high warnings from pvs-studio described in #2371 
fix #2371 
run c++ unit tests

[Fix]: PVS-studio high warnings

---

registry.json

Fixes https://github.com/trustwallet/wallet-core/issues/2398

[Polygon] Update rpc url in registry

---

src/Ethereum/Address.cpp
src/Ethereum/AddressChecksum.cpp
src/Ethereum/AddressChecksum.h
src/Ronin/Address.cpp

Remove unused Ethereum ChecksumType.  Found in #2397
Unit tests.
* Bug fix (non-breaking change which fixes an issue) 

Remove unused Ethereum ChecksumType

---

src/Cosmos/ProtobufSerialization.cpp
src/proto/Cosmos.proto
tests/Cosmos/SignerTests.cpp

Add way to SignDirect: create signed tx based on provided TxBody bytes.
Fixes #2412
Cosmos unit tests.

[Cosmos] SignDirect support

---

android/app/build.gradle
android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/near/TestNEARSigner.kt
android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/stellar/TestStellarSigner.kt
android/trustwalletcore/build.gradle
jni/java/wallet/core/java/AnySigner.java
tools/generate-files

[Breaking] Try to use protobuf-lite for android

---

src/Aeternity/Address.h
src/Aeternity/Signer.h
src/Algorand/AssetTransfer.h
src/Algorand/OptInAssetTransaction.h
src/Bech32.h
src/Defer.h
src/Tezos/Forging.h

fix #2423 
Browse c++ headers files

[Fix]: add missing header guards

---

tests/interface/TWBase64Tests.cpp

Fix base64 warnings integer comparison
Compile wallet-core

[Fix]: Base64 warnings

---

include/TrustWalletCore/TWHDWallet.h
src/HDWallet.cpp
src/HDWallet.h
src/interface/TWHDWallet.cpp
tests/HDWallet/HDWalletTests.cpp
tests/interface/TWHDWalletTests.cpp

Add new method for get private key by curve type
This PR is a slight rework of original #2350 .
HDWallet/Key unit tests.

Add getKeyByCurve method

---

src/Ethereum/ABI/Array.cpp
src/Ethereum/ABI/Array.h
tests/Ethereum/AbiStructTests.cpp
tests/Ethereum/AbiTests.cpp
wasm/tests/AnyAddress.test.ts

[Ethereum] Support fixed array in ABI

---

src/interface/TWBitcoinAddress.cpp
src/interface/TWBitcoinScript.cpp
src/interface/TWCardano.cpp
src/interface/TWEthereumAbi.cpp
src/interface/TWEthereumAbiFunction.cpp
src/interface/TWEthereumAbiValue.cpp
src/interface/TWFIOAccount.cpp
src/interface/TWNEARAccount.cpp
src/interface/TWRippleXAddress.cpp
src/interface/TWSegwitAddress.cpp
src/interface/TWStoredKey.cpp

There was still some source in interface folder that was using namespace
Improvements

[Test]: Fix interfaces sources for unity build

---

samples/android/app/build.gradle
samples/android/build.gradle

This is frequently asked question
Open Android samples to try to build

[Sample] Fix reading grp user/key from local.properties for Android

---

tests/Bitcoin/BitcoinScriptTests.cpp
tests/Bitcoin/SegwitAddressTests.cpp
tests/Bitcoin/TWBitcoinScriptTests.cpp
tests/Cardano/AddressTests.cpp
tests/EOS/TransactionTests.cpp
tests/EncryptTests.cpp
tests/HDWallet/HDWalletInternalTests.cpp
tests/HDWallet/HDWalletTests.cpp
tests/Solana/TWAnySignerTests.cpp

Put HDWallet tests under unique namespace
UT

One more fix for unity build

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/tezos/TestTezosSigner.kt
src/Tezos/Address.cpp
src/Tezos/Address.h
src/Tezos/BinaryCoding.cpp
src/Tezos/BinaryCoding.h
src/Tezos/Entry.cpp
src/Tezos/Entry.h
src/Tezos/Forging.cpp
src/Tezos/Forging.h
src/Tezos/Michelson.cpp
src/Tezos/Michelson.h
src/Tezos/OperationList.cpp
src/Tezos/OperationList.h
src/Tezos/Signer.cpp
src/Tezos/Signer.h
src/proto/Tezos.proto
swift/Tests/Blockchains/TezosTests.swift
tests/Tezos/ForgingTests.cpp
tests/Tezos/TWAnySignerTests.cpp

[Tezos]: FA1.2/FA2 support

---

src/Ontology/Oep4.cpp
src/Ontology/Ong.cpp
src/Ontology/Ont.cpp
src/Ontology/ParamsBuilder.cpp
src/Ontology/ParamsBuilder.h
tests/Ontology/ParamsBuilderTests.cpp
tests/Ontology/TransactionTests.cpp

fix #2522 
run c++ unit tests
Improvements

[Ontology]: Switch boost::any to std::variant

---

wasm/CMakeLists.txt

Fixes https://github.com/trustwallet/wallet-core/issues/2544
N/A
* Document

[Wasm] Document flags and options in CMakeLists.txt

---

registry.json
tests/Cosmos/TWCoinTypeTests.cpp
tests/Kava/TWCoinTypeTests.cpp
tests/Terra/TWCoinTypeTests.cpp

TODO: add more unit tests
Bug fix #2557 

[Cosmos]: Add missing chain id

---

tools/doxygen_convert_comments
tools/generate-files
tools/ios-build
tools/ios-doc
tools/ios-xcframework
tools/ios-xcframework-release
tools/library

Fixes https://github.com/trustwallet/wallet-core/issues/2216 doc API Swift codegen
Regarding host with website: https://developer.apple.com/documentation/xcode/distributing-documentation-to-external-developers
```bash
./tools/generate_files
./tools/ios-doc
open swift/doc_archives/WalletCore.doccarchive
```
Improvements

[Tools]: Swift API codegen

---

src/Keystore/EncryptionParameters.cpp
src/Keystore/EncryptionParameters.h
tests/Keystore/StoredKeyTests.cpp

one step of #2540 
run c++ unit tests
Improvements

Improvements: remove boost::variant usage in favor of std::variant

---

src/Cosmos/JsonSerialization.cpp
src/Cosmos/JsonSerialization.h
src/Cosmos/Signer.cpp
src/Cosmos/Signer.h
src/proto/Cosmos.proto
tests/Evmos/SignerTests.cpp
tests/FIO/TWFIOTests.cpp
tests/FIO/TransactionBuilderTests.cpp

fix #2566
Improvements for cosmos signing output

[Improvements]: add json signatures to cosmos signing output

---

.github/CODEOWNERS

update CODEOWNERS review assignments

[Improvements]: update CODEOWNERS for review assignments

---

samples/node/index.ts
samples/node/package-lock.json
samples/node/package.json
samples/node/tsconfig.json

Update the node sample using Typescript, add `KeyStore` usage
Run sample
Test only

[Sample] Add KeyStore to node sample

---

README.md

Update Android installation guide in readme

---

src/Cardano/AddressV2.cpp
src/Cardano/AddressV2.h
src/Cardano/AddressV3.cpp
src/Cardano/AddressV3.h
src/Cardano/Signer.cpp
src/Cardano/Signer.h
src/Cardano/Transaction.cpp
src/Cardano/Transaction.h

- Clang Fixes
- Code improvements
Improvements

[Cardano]: clang fix and improvements

---

samples/typescript/devconsole.ts/package-lock.json
samples/typescript/devconsole.ts/package.json
samples/typescript/devconsole.ts/samplescripts/wallets.sampleinput.txt
samples/typescript/devconsole.ts/src/index.ts

Devconsole.ts now uses KeyStore to store wallets persistently.
See https://github.com/trustwallet/wallet-core/blob/ar/devconsole-keystore/samples/typescript/devconsole.ts/samplescripts/wallets.sampleinput.txt for demo script
```
cd samples/typescript/devconsole.ts
npm install
npm run build
echo "await walletCreate(256, 'TEST'); \n walletDump(); \n .exit" | npm run start
echo "await walletDump() \n .exit" | npm run start
```

[devconsole] Keystore in devconsole, support stored wallets

---

tools/install-wasm-dependencies

Upgrade Emscripten version to 3.1.22 (latest) from 3.1.14
WASM unit tests should pass

[WASM] Upgrade Emscripten version to 3.1.22

---

swift/Tests/TransactionCompilerTests.swift
tests/TransactionCompilerTests.cpp
tests/interface/TWTransactionCompilerTests.cpp

Add swift version of test for External Signature use case. Fixes #2131 .
Only a Bitcoin (one of the most complex) test was added. 
Check swift test `testBitcoinCompileWithSignatures()`
* New test

[TestOnly] New swift test for external signature feature

---

registry.json
src/Bitcoin/Entry.cpp
src/Bitcoin/SegwitAddress.h
tests/Bitcoin/SegwitAddressTests.cpp

Add ability to generate Bitcoin Testnet address, using a special Derivation.  Fixes #2611.
See relevant unit test (in PR).

Support Bitcoin testnet address

---

samples/typescript/devconsole.ts/src/index.ts

Help in `devconsole.ts`; some walletXxx() helper were not in the help, added
Also, minor `await` fix for `walletAddCoin()`.
Start devconsole.ts, then `help()`.
* Documentation only

[Devconsole] Add missing walletXxx utilities to help

---

src/Aptos/Address.h
src/Aptos/MoveTypes.h
src/Aptos/Signer.cpp
src/proto/Aptos.proto
tests/Aptos/SignerTests.cpp
tests/interface/TWTestUtilities.h

Second step of #2594
Blockchain transaction additions

[Aptos]: Aptos NFT capabilities

---

registry.json
tests/chains/Aptos/TWCoinTypeTests.cpp

Update to aptos mainnet values

[Aptos]: update aptos registry.json with mainnet values

---

codegen/lib/templates/newcoin/Address.h.erb
codegen/lib/templates/newcoin/Entry.h.erb
codegen/lib/templates/newcoin/Signer.h.erb

Fixes #2604.
- Made generated Entry class final
- Fixed include for Data.h
Run ./codegen/bin/newcoin, build the project and run unit tests (done).

[Codegen]: Codegen fixes - coin templates

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/elrond/TestElrondSigner.kt
swift/Tests/Blockchains/ElrondTests.swift
tests/chains/Elrond/SignerTests.cpp

Implement Elrond staking from #2674 
https://docs.elrond.com/validators/delegation-manager/#delegating-and-managing-delegated-funds
I hide the real private key and changed value of the unit tests since my funds are lock for 9 days, but broadcasting was successful

[Elrond]: add elrond staking unit tests

---

.github/workflows/linux-ci-sonarcloud.yml
.github/workflows/linux-ci.yml
sonar-project.properties
src/HDWallet.cpp
src/Mnemonic.cpp
src/Result.h
src/interface/TWTransactionCompiler.cpp
tools/sonar-scanner.properties
tools/sonarcloud-analysis

[CodeQuality]: Enable sonarcloud on CI run

---

src/Aptos/Address.h
src/Aptos/MoveTypes.h
tests/chains/Aptos/AddressTests.cpp
tests/chains/Aptos/MoveTypesTests.cpp
tests/chains/Aptos/TransactionPayloadTests.cpp
wasm/tests/Blockchain/Aptos.test.ts

[Aptos]: Fix Wasm Global variable generation

---

swift/Tests/TransactionCompilerTests.swift
swift/project.yml

Fix some warnings found in Xcode
Run iOS UT

[Swift] Fix some warnings

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/smartbitcoincash/TestSmartBitcoinCashAddress.kt

Minor update in SmartBCH test, change test data.
Unit tests.

Update in SmartBCH swift test

---

wasm/package-lock.json
wasm/package.json

[Wasm] upgrade mocha to 10.1.0

---

src/Solana/Signer.cpp
src/proto/Solana.proto
tests/chains/Solana/TWAnySignerTests.cpp

[Solana]: add unsigned_tx support

---

swift/Tests/Blockchains/SmartBitcoinCashTests.swift

Minor update in SmartBCH test, change test data.  Kotlin test was updated in #2692, but not the swift test :(
Unit tests.

[Minor] Update in SmartBCH swift(!) test

---

.github/workflows/android-ci.yml
.gitignore
tools/kotlin-doc

Fix `dokka-out` folder might not be created
Android CI

[CI] Test Kotlin doc 

---

registry.json
tests/chains/Optimism/TWCoinTypeTests.cpp

Fixes https://github.com/trustwallet/wallet-core/issues/2710
Unit test

Update Optimism Ethereum name

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/ethereum/TestEthereumTransactionSigner.kt
swift/Tests/Blockchains/EthereumTests.swift
tests/chains/Ethereum/TWAnySignerTests.cpp

Add tests for ETH staking tx using RocketPool (see #2674).
Run unit tests

[Staking]: add ETH pooled staking tests

---

README.md

The link on Google play, 
https://play.google.com/store/apps/details?id=com.memeswallet

Add Memes wallet to the list that use Wallet core

---

Package.swift

[iOS]: Update Swift.package

---

wasm/src/Random.cpp

[emscripten]: use javascript for random generation

---

src/NEAR/Serialization.cpp
src/proto/NEAR.proto
tests/chains/NEAR/TWAnySignerTests.cpp
tests/common/HDWallet/HDWalletTests.cpp

Add tests for NEAR staking, as a part of #2674.
Run the new test manually.

[Staking]: add NEAR staking

---

src/THORChain/Swap.cpp
tests/chains/THORChain/SwapTests.cpp

[ThorSwap]: ERC20 token transfer

---

tools/android-release

Fixed android-release script so it would upload kotlin docs without an error
Manually

[Fix]: Fix error when uploading kotlin docs

---

tests/chains/Aptos/SignerTests.cpp

Using tortuga finance: https://explorer.aptoslabs.com/account/0x8f396e4246b2ba87b51c0739ef5ea4f26515a98375308c31ac2ec1e42142a57f/modules

[Aptos]: Add Staking/Unstaking example

---

bootstrap.sh

[Build]: update bootstrap.sh

---

android/trustwalletcore/maven-push.gradle

Unify system environment variable name
Should be fixed in next android release

Read `GITHUB_USER` without WC_ prefix

---

src/THORChain/Swap.cpp
src/THORChain/Swap.h
tests/chains/THORChain/SwapTests.cpp

start #2714 
run C++ unit tests

[ThorSwap]: full DOGE/BCH/LTC support

---

include/TrustWalletCore/TWBitcoinMessageSigner.h
include/TrustWalletCore/TWEthereumEip2645.h
include/TrustWalletCore/TWEthereumMessageSigner.h
include/TrustWalletCore/TWStarkExMessageSigner.h
include/TrustWalletCore/TWStarkWare.h

Those classses only have static methods so change them to struct. wallet-core-python depends on it for paring header files.

Change several classes to structs

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt
android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/agoric/TestAgoricAddress.kt
android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/agoric/TestAgoricSigner.kt
docs/registry.md
include/TrustWalletCore/TWCoinType.h
registry.json
swift/Tests/Blockchains/AgoricTests.swift
swift/Tests/CoinAddressDerivationTests.swift
tests/chains/Agoric/AddressTests.cpp
tests/chains/Agoric/TWCoinTypeTests.cpp
tests/common/CoinAddressDerivationTests.cpp

Add supports for Agoric blockchain
https://docs.agoric.com
Unit tests are written in chain specific folder
Transaction hash for signer test
https://atomscan.com/agoric/transactions/142BF63F54D059D8B3C356F6E6F36EA3A979AEE6A0875E0F350D71F3799B030F

Agoric Support

---

src/THORChain/Swap.cpp
src/THORChain/Swap.h
tests/chains/THORChain/SwapTests.cpp

[ThorSwap]: SWAP from atom support

---

src/THORChain/Swap.cpp
src/THORChain/Swap.h
tests/chains/THORChain/SwapTests.cpp

[ThorSwap]: Add full avax support

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/elrond/TestElrondSigner.kt
docs/registry.md
registry.json
src/Elrond/Codec.cpp
src/Elrond/Codec.h
src/Elrond/NetworkConfig.h
src/Elrond/TransactionFactory.h
swift/Tests/Blockchains/ElrondTests.swift
tests/chains/Elrond/SignerTests.cpp
tests/chains/Elrond/TWCoinTypeTests.cpp

[`Elrond` is now `MultiversX`](https://twitter.com/beniaminmincu/status/1588162448103612416).
Applied the rename in `registry.json` and in a few comments (with links).
A PR against https://github.com/trustwallet/assets/ will follow.

Rename Elrond to MultiversX (configuration change)

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt
docs/registry.md
include/TrustWalletCore/TWCoinType.h
registry.json
swift/Tests/CoinAddressDerivationTests.swift
tests/chains/WAX/TWAnySignerTests.cpp
tests/chains/WAX/TWCoinTypeTests.cpp
tests/common/CoinAddressDerivationTests.cpp

Add WAX chain with basic transfer functions (#2670).
Unit tests, check transaction on explorer

[WAX]: Add WAX chain

---

SECURITY.MD

[Misc]: add SECURITY.MD

---

rust/src/move_parser/mod.rs
tests/chains/Aptos/TransactionPayloadTests.cpp

https://github.com/aptos-labs/aptos-core/issues/6235

[Fix]: fix serialization for aptos tx (pancake swap)

---

src/THORChain/Swap.cpp
src/THORChain/Swap.h
tests/chains/THORChain/SwapTests.cpp

we were using uint64_t for amount, that's unsafe for some chains such as ETH.

[Thorchain]: fix overflow for big amount

---

.github/workflows/linux-ci-sonarcloud.yml
src/Bitcoin/Script.cpp
swift/Tests/Blockchains/ZcashTests.swift
tools/install-rust-dependencies
tools/ios-build
tools/rust-bindgen

Fixes https://github.com/trustwallet/wallet-core/issues/2904, this was introduced when refactoring HRP check in previous PR https://github.com/trustwallet/wallet-core/pull/2814

Fix empty lock script data for Flux (zelcash)

---

swift/common-xcframework.yml
swift/project.yml

feat(ios-build): remove catalyst for fastlane

---

wasm/src/CoinTypeExtension.cpp
wasm/src/CoinTypeExtension.d.ts
wasm/tests/CoinType.test.ts

#2391 POC - we may merge it to unlock CoinType for WASM, but can serve as an example for codegen.

[CoinType]: Add cointype extension for wasm

---

src/Solana/Instruction.h
src/Solana/LegacyMessage.cpp
src/Solana/MessageHeader.h
tests/chains/Solana/TransactionTests.cpp

Fixes a couple nits I noticed when looking at #2935
No functional changes
Noop
- Code comments: correct Instruction field descriptions
- Rename: update MessageHeader field names to match definitions https://github.com/solana-labs/solana/blob/f91e63dfe9527199acb692a43629a97f0bf78e1f/sdk/program/src/message/mod.rs#L96

[Solana] Refine `programId` and `accounts` comments, `CreditOnly` -> `ReadOnly`

---

src/Tron/Protobuf/TronInternal.proto
src/Tron/Serialization.cpp
src/Tron/Signer.cpp
src/proto/Tron.proto
tests/chains/Tron/SignerTests.cpp

Tron Staking V2 - https://github.com/tronprotocol/tips/issues/467
Tx not broadcasted because fast block time but got same value as API:
```
{
"visible": true,
"txID": "b18e7dbeaf8691a314c6e07885ad8f00cbc17ae90679e0f9155039f1f2d28fdd",
"raw_data": {
"contract": [
{
"parameter": {
"value": {
"frozen_balance": 1000000,
"owner_address": "TWWb9EjUWai17YEVB7FR8hreupYJKG9sMR"
},
"type_url": "type.googleapis.com/protocol.FreezeBalanceV2Contract"
},
"type": "FreezeBalanceV2Contract"
}
],
"ref_block_bytes": "d0d6",
"ref_block_hash": "c13c4c6b12f3dcdf",
"expiration": 1676384775000,
"timestamp": 1676384717246
},
"raw_data_hex": "0a02d0d62208c13c4c6b12f3dcdf40d8d6c682e5305a57083612530a34747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e467265657a6542616c616e63655632436f6e7472 …
```

[Tron]: Staking V2

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/tron/TestTronTransactionSigner.kt
src/Tron/Signer.cpp
src/proto/Tron.proto
swift/Tests/Blockchains/TronTests.swift
tests/chains/Tron/SignerTests.cpp

Add a way to sign txId provided by dapps json payload.

[Tron]: Direct Sign support

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt
android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/stargaze/TestStargazeAddress.kt
android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/stargaze/TestStargazeSigner.kt
docs/registry.md
include/TrustWalletCore/TWCoinType.h
registry.json
samples/rust/Cargo.lock
swift/Tests/Blockchains/StargazeTests.swift
swift/Tests/CoinAddressDerivationTests.swift
tests/chains/Stargaze/AddressTests.cpp
tests/chains/Stargaze/TWAnySignerTests.cpp
tests/common/CoinAddressDerivationTests.cpp
tests/common/HDWallet/HDWalletTests.cpp

fix #3027
Run Swift/KT unit tests

[Stargaze] Add NFT chain support for Cosmos ecosystem

---

.github/workflows/android-ci.yml
.github/workflows/ios-ci.yml
.github/workflows/kotlin-ci.yml

It seems good improvements for android and kotlin CI

[CI]: Use MacOS GitHub new xl runners

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/algorand/TestAlgorandSigner.kt
src/Algorand/Signer.cpp
src/proto/Algorand.proto
swift/Tests/Blockchains/AlgorandTests.swift
tests/chains/Algorand/SignerTests.cpp
tests/chains/Algorand/TWAnySignerTests.cpp

fix #3028 
Run Swift/KT unit tests
```json
{
"hgi": true,
"sig": "nXQsDH1ilG3DIo2VQm5tdYKXe9o599ygdqikmROpZiNXAvQeK3avJqgjM5o+iByCdq6uOxlbveDyVmL9nZxxBg==",
"txn": {
"aamt": 1,
"arcv": "362T7CSXNLIOBX6J3H2SCPS4LPYFNV6DDWE6G64ZEUJ6SY5OJIR6SB5CVE",
"fee": 1000,
"fv": 27963950,
"lv": 27964950,
"note": "VFdUIFRPIFRIRSBNT09O",
"snd": "ZJAHTHNM3NLE2EEWMEOZ3JWKPJVESFXW22ATQODAOJNO3L7JCYL5DEJNJI",
"type": "axfer",
"xaid": 989643841
}
}
```
from:
curl --location 'algorand_rest_rpc_url/v2/blocks/27963952'

[Algorand]: NFT support on algorand 

---

.github/CODEOWNERS
samples/kmp/shared/build.gradle.kts

[Misc]: update CODEOWNERS

---

src/THORChain/TWSwap.cpp
src/proto/THORChainSwap.proto
tests/chains/THORChain/TWSwapTests.cpp

Add missing enum for BCH, DOGE, LTC, AVAX and ATOM

[Thorswap]: add missing enum / proto to support extra chains

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt
docs/registry.md
include/TrustWalletCore/TWCoinType.h
registry.json
swift/Tests/CoinAddressDerivationTests.swift
tests/chains/Axelar/TWAnyAddressTests.cpp
tests/chains/Axelar/TWCoinTypeTests.cpp
tests/common/CoinAddressDerivationTests.cpp

similar to #3054 - adding axelar, will refactor unit tests in a unique folder after adding all chains
to merge after #3054 
Run C++, Kotlin, Swift unit tests

[Cosmos]: Add Axelar

---

README.md

[Misc]: update projects README.md section

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt
docs/registry.md
include/TrustWalletCore/TWCoinType.h
registry.json
swift/Tests/CoinAddressDerivationTests.swift
tests/common/CoinAddressDerivationTests.cpp
tests/common/HDWallet/HDWalletTests.cpp

Similar to other EVM based chains
Run C++, Swift and KT unit tests

[IoTeX]: Add support for IoTeX EVM.

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt
docs/registry.md
include/TrustWalletCore/TWCoinType.h
registry.json
swift/Tests/CoinAddressDerivationTests.swift
tests/chains/Cosmos/Neutron/TWAnyAddressTests.cpp
tests/chains/Cosmos/Neutron/TWCoinTypeTests.cpp
tests/common/CoinAddressDerivationTests.cpp

similar to other cosmos chains - testnet for now
Run C++, kt and swift unit tests

[Cosmos]: add Neutron support

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt
docs/registry.md
include/TrustWalletCore/TWCoinType.h
registry.json
swift/Tests/CoinAddressDerivationTests.swift
tests/chains/Cosmos/FetchAI/TWAnyAddressTests.cpp
tests/chains/Cosmos/FetchAI/TWCoinTypeTests.cpp
tests/common/CoinAddressDerivationTests.cpp

similar to other cosmos chains

[Cosmos]: Adding support for Fetch.ai

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt
docs/registry.md
include/TrustWalletCore/TWCoinType.h
registry.json
swift/Tests/CoinAddressDerivationTests.swift
tests/chains/Cosmos/Umee/TWAnyAddressTests.cpp
tests/chains/Cosmos/Umee/TWCoinTypeTests.cpp
tests/common/CoinAddressDerivationTests.cpp

similar to other cosmos chains

[Cosmos]: add support for Umee

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt
docs/registry.md
include/TrustWalletCore/TWCoinType.h
registry.json
swift/Tests/CoinAddressDerivationTests.swift
tests/chains/Cosmos/Coreum/TWAnyAddressTests.cpp
tests/chains/Cosmos/Coreum/TWCoinTypeTests.cpp
tests/common/CoinAddressDerivationTests.cpp
tests/common/HDWallet/HDWalletTests.cpp

Similar as other cosmos chains

[Cosmos]: add support for Coreum

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt
docs/registry.md
include/TrustWalletCore/TWCoinType.h
registry.json
swift/Tests/CoinAddressDerivationTests.swift
tests/chains/Cosmos/Noble/TWAnyAddressTests.cpp
tests/chains/Cosmos/Noble/TWCoinTypeTests.cpp
tests/common/CoinAddressDerivationTests.cpp

similar to other cosmos chains

[Cosmos]: Add support for Noble

---

.github/workflows/android-ci.yml
.github/workflows/ios-ci.yml
.github/workflows/kotlin-ci.yml
.github/workflows/kotlin-sample-ci.yml
tools/android-test
tools/ios-test

[Actions/CI]: switch to self hosted runner

---

.github/workflows/android-ci.yml
.github/workflows/ios-ci.yml
.github/workflows/linux-ci-sonarcloud.yml

https://github.com/Swatinem/rust-cache/issues/16

[CI]: disable rust cache for self hosted runner

---

registry.json
tests/chains/Cosmos/Neutron/TWAnySignerTests.cpp
tests/chains/Cosmos/Neutron/TWCoinTypeTests.cpp

[Neutron]: finalize neutron airdrop example

---

.github/workflows/android-ci.yml
.github/workflows/codegen-v2.yml
.github/workflows/docker.yml
.github/workflows/ios-ci.yml
.github/workflows/kotlin-ci.yml
.github/workflows/kotlin-sample-ci.yml
.github/workflows/linux-ci-rust.yml
.github/workflows/linux-ci-sonarcloud.yml
.github/workflows/linux-ci.yml
.github/workflows/linux-sampleapp-ci.yml
.github/workflows/wasm-ci.yml

Create `dev` branch as the target for Pull Requests with sensitive changes.

Set up CI for dev branch

---

src/Aptos/Signer.cpp
src/LiquidStaking/LiquidStaking.cpp
src/LiquidStaking/LiquidStaking.h
src/proto/Aptos.proto
src/proto/LiquidStaking.proto
tests/chains/Aptos/SignerTests.cpp
tests/common/LiquidStaking/LiquidStakingTests.cpp

stake/unstake/withdraw ops for tortuga finance (aptos)

[LiquidStaking]: add aptos liquid staking support

---

include/TrustWalletCore/TWDerivationPath.h

[Header]: fix self referenced header

---

src/Cosmos/Protobuf/stride_liquid_staking.proto
src/Cosmos/ProtobufSerialization.cpp
src/LiquidStaking/LiquidStaking.cpp
src/LiquidStaking/LiquidStaking.h
src/proto/Cosmos.proto
src/proto/LiquidStaking.proto
tests/chains/Cosmos/Stride/TWAnySignerTests.cpp
tests/common/LiquidStaking/LiquidStakingTests.cpp

Extend liquid staking module with LS support on Atom through stride

[Atom]: Add liquid staking for atom and extend liquid staking module

---

Package.swift
samples/kmp/shared/build.gradle.kts

Update `Package.swift` accordingly to the new version and checksum.

Update Package.swift accordingly to 3.1.31

---

registry.json
tests/chains/Cosmos/Neutron/TWCoinTypeTests.cpp

I didn't change tx/account sample because there is no tx/account yet on neutron: https://www.mintscan.io/neutron

[Neutron]: switch to mainnet

---

rust/Cargo.lock
rust/tw_starknet/Cargo.toml

Update `starknet-ff` crate to the latest 0.3.3
Run Rust, C++ tests

[Rust]: Update starknet-ff crate

---

.github/workflows/ios-ci.yml
.github/workflows/kotlin-ci.yml
.github/workflows/linux-ci-sonarcloud.yml
.github/workflows/linux-ci.yml
.github/workflows/linux-sampleapp-ci.yml
.github/workflows/wasm-ci.yml
Dockerfile
tools/build-and-test
tools/rust-bindgen

Fix android build, improve `tools/rust-bindgen`
CI workflows should pass

[r2r] Fix android build, improve `tools/rust-bindgen`

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/TestCoinType.kt
swift/Tests/CoinTypeTests.swift
swift/Tests/TransactionCompilerTests.swift

Add tests to check if new methods available on iOS and android
Run Swift, Kotlin tests
Add tests to check if new methods available on iOS and android

[test]: Add iOS and android tests to check if new methods available

---

codegen/lib/kotlin_helper.rb
codegen/lib/templates/kotlin/android_enum.erb
codegen/lib/templates/kotlin/common_enum.erb
codegen/lib/templates/kotlin/ios_enum.erb
codegen/lib/templates/kotlin/js_enum.erb

- Added `val value: UInt` property to enums
- Added companion `fun fromValue(value: UInt)` function to enums

[Kotlin] Added UInt value to enums

---

README.md

- Removed broken IFWallet link
- Updated supported blockchain count according to docs/registry.md
- Corrected some typos and grammatical mistakes

[README]: Update README.md

---

android/app/src/androidTest/java/com/trustwallet/core/app/utils/TestWebAuthn.kt
include/TrustWalletCore/TWWebAuthn.h
src/WebAuthn.cpp
src/WebAuthn.h
src/interface/TWWebAuthn.cpp
swift/Tests/WebAuthnTests.swift
tests/common/WebAuthnTests.cpp

1) extract r,s values from asn encoded webauthn signature
2) reconstruct the original signed message based on authenticatorData & clientDataJSON

[Webauthn] Add some helpers to extract P256 values

---

src/Cardano/AddressV2.cpp
wasm/tests/Blockchain/Cardano.test.ts

Don't throw exception on `AddressV2::isValid`.
Run C++, WASM tests

[Cardano]: Fix signing in JS

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/theopennetwork/TestTheOpenNetworkSigner.kt
samples/kmp/shared/build.gradle.kts
src/Everscale/CommonTON/CellBuilder.cpp
src/Everscale/CommonTON/CellBuilder.h
src/TheOpenNetwork/Payloads.cpp
src/TheOpenNetwork/Payloads.h
src/TheOpenNetwork/Signer.cpp
src/TheOpenNetwork/Signer.h
src/TheOpenNetwork/wallet/Wallet.cpp
src/TheOpenNetwork/wallet/Wallet.h
src/proto/TheOpenNetwork.proto
swift/Tests/Blockchains/TheOpenNetworkTests.swift
tests/chains/TheOpenNetwork/SignerTests.cpp
wasm/tests/Blockchain/TheOpenNetwork.test.ts

Add The Open Network fungible token (jetton) transfer functionality according to TEP-74
Issue: https://github.com/trustwallet/wallet-core/issues/3196
There are tests for C++, wasm, ios, android

Add The Open Network token (jetton) transfer functionality

---

src/Cosmos/Protobuf/thorchain_bank_tx.proto
src/Cosmos/ProtobufSerialization.cpp
src/THORChain/Swap.cpp
src/THORChain/Swap.h
src/THORChain/TWSwap.cpp
src/proto/Cosmos.proto
tests/chains/Cosmos/THORChain/SignerTests.cpp
tests/chains/Cosmos/THORChain/SwapTests.cpp
tests/chains/Cosmos/THORChain/TWSwapTests.cpp

Support RUNE on `THORChainSwap`
Run C++ tests

[ThorSwap]: support swap RUNE

---

registry.json

This updates the Arbitrum RPC URL from an old, outdated and non-supported RPC URL to the correct one as shown here: https://docs.arbitrum.io/node-running/node-providers#rpc-endpoints

[Arbitrum] Update RPC URL and docs URL

---

rust/tw_starknet/src/key_pair.rs

The loop inside `ecdsa_sign()` can run infinitely. This can occur if the `rfc6979_generate_k` generates a random number that is invalid.
Run Rust tests

[Starknet]: Add `ecdsa_sign` retry limit

---

.github/workflows/kotlin-ci.yml
kotlin/.editorconfig
kotlin/wallet-core-kotlin/build.gradle.kts
kotlin/wallet-core-kotlin/src/androidUnitTest/kotlin/com/trustwallet/core/LibLoader.kt
kotlin/wallet-core-kotlin/src/commonTest/kotlin/com/trustwallet/core/LibLoader.kt
kotlin/wallet-core-kotlin/src/commonTest/kotlin/com/trustwallet/core/test/CoinAddressDerivationTests.kt
kotlin/wallet-core-kotlin/src/iosTest/kotlin/com/trustwallet/core/LibLoader.kt
kotlin/wallet-core-kotlin/src/jsTest/kotlin/com/trustwallet/core/LibLoader.kt
kotlin/wallet-core-kotlin/src/jvmMain/kotlin/com/trustwallet/core/WalletCoreLibLoader.kt
kotlin/wallet-core-kotlin/src/jvmMain/resources/jni/linux-x86_64/.gitignore
kotlin/wallet-core-kotlin/src/jvmMain/resources/jni/macos-arm64/.gitignore
kotlin/wallet-core-kotlin/src/jvmTest/kotlin/com/trustwallet/core/LibLoader.kt
tools/kotlin-test

- Added helper class for library loading on JVM: `WalletCoreLibLoader`
- Added first test for Kotlin project (copied from Android project)
- Run tests on CI for Kotlin (only JVM target)

[Kotlin] JVM support (part 2)

---

Dockerfile

[Docker]: Fix Docker pipeline

---

registry.json
samples/kmp/shared/build.gradle.kts
tests/chains/Greenfield/TWCoinTypeTests.cpp

Update `chainId`, `sampleTx`, `sampleAccount`.
Please note that we had no chance to test transactions on mainnet.
Run C++ tests

[Greenfield]: Update to mainnet

---

registry.json
samples/kmp/shared/build.gradle.kts
tests/chains/Scroll/TWCoinTypeTests.cpp

[Scroll] Update rpc and block explorer for mainnet

---

trezor-crypto/crypto/scrypt.c

Fixes: https://github.com/trustwallet/wallet-core/issues/3391
The problem in the mentioned issue is related to an incorrect working of the `scrypt` function.
When we compile WalletCore using Xcode 14.3.1 in Release mode, `scrypt` starts computing weird password hashes.
The reason of the problem is in `salsa20_8(B)` function.
From what I could understand, the compiler optimises and, looks like, skips operations on columns and on rows:
https://github.com/trustwallet/wallet-core/blob/0dd563f742fc314efb2ae14b4e875a788fd57c34/trezor-crypto/crypto/scrypt.c#L85-L111
Run C++ tests with `-Os` optimisation level.
```cmake
set(CMAKE_BUILD_TYPE Release)
set(CMAKE_CXX_FLAGS "-Wall -Wextra")
set(CMAKE_CXX_FLAGS_DEBUG "-Os")
set(CMAKE_CXX_FLAGS_RELEASE "-Os")
set(CMAKE_C_FLAGS "-Wall -Wextra") …
```

[Crypto]: Fix salsa20_8(B) when compiled with `-Os` optimisation level

---

.github/workflows/linux-ci.yml
.github/workflows/linux-sampleapp-ci.yml

feat(linux): ci fix

---

registry.json
tests/chains/Cosmos/Tia/TWCoinTypeTests.cpp

Change Celestia chainId, explorer URL
Run C++ tests

feat(Celestia): Add support for Celestia mainnet

---

src/THORChain/Swap.cpp
tests/chains/Cosmos/THORChain/SwapTests.cpp

Fix ETH memo for ->BSC swap.
Run C++ tests

[Swap]: Fix BSC swap

---

tools/install-sys-dependencies-mac

[CI]: Install rustup in a correct way

---

codegen-v2/src/codegen/cpp/entry_generator.rs
codegen-v2/src/codegen/rust/coin_crate.rs
samples/kmp/shared/build.gradle.kts

[KMP]: Bump to 4.0.9

---

.github/workflows/linux-ci.yml
.github/workflows/linux-sampleapp-ci.yml

Version number changed, breaking our workaround for https://github.com/actions/runner-images/issues/8659.
LinuxCI

[CI/Linux]: Bump libc6 downgrade version

---

.github/CODEOWNERS

Update owners for kotlin/ related files
1. Make changes to any of the files under kotlin/
2. Create a Pull Request (should request a review from new code owners)
Repository Configuration Update (non-breaking change which enhances repository settings)
- [n/a] ~Add tests to cover changes as needed.~
- [n/a] ~Update documentation as needed.~
- [n/a] ~If there is a related Issue, mention it in the description.~

Update CODEOWNERS for Kotlin files

---

registry.json
samples/kmp/shared/build.gradle.kts
tests/chains/Bitcoin/TWCoinTypeTests.cpp
tests/chains/Cosmos/BandChain/TWCoinTypeTests.cpp
tests/chains/NEAR/TWAnySignerTests.cpp
tests/chains/NEAR/TWCoinTypeTests.cpp
tests/chains/Nano/TWCoinTypeTests.cpp
tests/chains/OKXChain/TWCoinTypeTests.cpp
tests/chains/Oasis/TWCoinTypeTests.cpp
tests/chains/Stellar/TWCoinTypeTests.cpp
tools/registry

Update blockchain explorers for Bitcoin and Nano.
Run C++ tests
Changes in registry.json and C++ tests.

[Explorer]: Update blockchain explorers for Bitcoin and Nano

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/CoinAddressDerivationTests.kt
android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/dydx/TestDydxAddress.kt
docs/registry.md
include/TrustWalletCore/TWCoinType.h
kotlin/wallet-core-kotlin/src/commonTest/kotlin/com/trustwallet/core/test/CoinAddressDerivationTests.kt
registry.json
rust/tw_any_coin/tests/chains/cosmos/cosmos_address.rs
rust/tw_any_coin/tests/chains/dydx/dydx_address.rs
rust/tw_any_coin/tests/chains/dydx/mod.rs
rust/tw_any_coin/tests/chains/mod.rs
rust/tw_any_coin/tests/coin_address_derivation_test.rs
swift/Tests/Blockchains/DydxTests.swift
swift/Tests/CoinAddressDerivationTests.swift
tests/chains/Dydx/TWCoinTypeTests.cpp
tests/common/CoinAddressDerivationTests.cpp

Add support for dYdX Cosmos chain
Run Rust, C++, mobile tests

feat(dYdX): Add support for dYdX Cosmos chain

---

rust/tw_coin_entry/src/common/compile_input.rs
rust/tw_evm/src/modules/compiler.rs
tests/chains/Ethereum/TransactionCompilerTests.cpp

As evm public key is optional, we need to keep compatible with before implemented in C++. Otherwise we have to change our existing prod codes to adapt this change.

[EVM]Make public key as optional

---

samples/kmp/shared/build.gradle.kts

Add a workaround to fix "unknown options: -ios_simulator_version_min -sdk_version" with Xcode 15 beta 3" error.
https://youtrack.jetbrains.com/issue/KT-60230
Please note this won't be required when https://github.com/trustwallet/wallet-core/pull/3609 is merged.

[KMP]: Fix KMP sample

---

registry.json
src/proto/Aeternity.proto
src/proto/Aion.proto
src/proto/Cardano.proto
src/proto/EOS.proto
src/proto/Ethereum.proto
src/proto/Filecoin.proto
src/proto/Harmony.proto
src/proto/Icon.proto
src/proto/NULS.proto
src/proto/Nebulas.proto
src/proto/Polkadot.proto
src/proto/Theta.proto
src/proto/VeChain.proto
src/proto/Zilliqa.proto
tests/chains/Ravencoin/TWCoinTypeTests.cpp
tests/chains/Ravencoin/TWRavencoinTransactionTests.cpp

Replace the broken https://ravencoin.network block explorer with the working one https://blockbook.ravencoin.org
Also, fix Protobuf comments regarding the U256 encoding.

[RVN]: Update block explorer

---

rust/chains/tw_solana/src/modules/message_builder.rs
tests/chains/Solana/TransactionCompilerTests.cpp

In solana, the advance nonce instruction must be before priority fee instructions.

[Solana]: Fix advance nonce not work with priority fee instruction

---

.github/workflows/linux-ci-rust.yml
Dockerfile
rust/chains/tw_solana/src/compiler.rs
rust/chains/tw_solana/src/modules/message_builder.rs
rust/chains/tw_solana/src/transaction/versioned.rs
rust/tw_any_coin/tests/chains/solana/solana_transaction.rs
tests/chains/Firo/TransactionCompilerTests.cpp
tools/release-size

Do not require to provide a `SigningInput::sender` address if `SigningInput::raw_message` specified.
Run Rust tests
Extract necessary signers from `MessageVersioned`, not from `SigningInput`.

[Solana]: Improve `TransactionDecoder` API

---

.github/workflows/codegen-v2.yml
codegen-v2/Cargo.lock
samples/kmp/shared/build.gradle.kts
tools/release-size

[CI]: Fix codegen-v2 CI

---

.github/workflows/linux-ci-rust.yml
rust/chains/tw_solana/src/modules/instruction_builder/stake_instruction.rs
rust/chains/tw_solana/src/program/stake_program.rs
rust/chains/tw_solana/tests/get_default_token_address.rs
rust/tw_any_coin/tests/chains/solana/solana_sign.rs

Fix [StakeProgram::address_from_recent_blockhash](https://github.com/trustwallet/wallet-core/blob/bd4279f745e00cf7909d9fd037aa44227ad7eacb/rust/chains/tw_solana/src/program/stake_program.rs#L25-L35)
Run Rust tests

[Solana]: Fix Solana delegate stake transaction

---

rust/tw_bitcoin/tests/p2tr_script_path.rs
rust/tw_utxo/src/compiler.rs
trezor-crypto/crypto/bignum.c

chore: fix some comments

---

rust/chains/tw_solana/src/compiler.rs
rust/tw_any_coin/tests/chains/solana/solana_compile.rs
rust/tw_hash/src/hash_array.rs

Related issue: https://github.com/trustwallet/wallet-core/issues/3749
Run the newly added unit tests in `solana_compile.rs`
Enhancement

Skip sig-verify for all-zero signature in Solana compiler.

---

README.md

Update the GitHub Issue policy at README.md

[README]: Update the GitHub Issue policy at README.md

---

docs/registry.md
registry.json
tests/chains/Merlin/TWCoinTypeTests.cpp
tests/chains/Optimism/TWCoinTypeTests.cpp
tests/common/WalletConsoleTests.cpp

Change "Optimism Ethereum" display name to "OP Mainnet" for Optimism chain.
Change "ETH" display name to "BTC" for Merlin chain.

[registry]: Set "OP Mainnet" for Optimism, "BTC" for Merlin display names

---

Package.swift

Update Package.swift to 4.0.33

feat(swift): Update Package.swift to 4.0.33

---

.github/workflows/linux-ci.yml
.github/workflows/linux-sampleapp-ci.yml

[CI]: Fix linux CI

---

rust/chains/tw_sui/src/address.rs
rust/tw_any_coin/tests/coin_address_derivation_test.rs

This PR fixesa bug when the leading zeros are trimmed.
Run Rust tests
Hot fix

[Sui]: Fix address formatting

---

src/Polkadot/Extrinsic.cpp
tests/chains/Polkadot/SignerTests.cpp

Update Polkadot signature encoding to support spec 1002005

---

Dockerfile
rust/Cargo.lock
rust/chains/tw_internet_computer/src/address.rs
rust/chains/tw_solana/src/transaction/short_vec.rs
rust/tw_evm/src/transaction/mod.rs
rust/tw_hash/Cargo.toml
rust/tw_keypair/Cargo.toml
rust/tw_misc/Cargo.toml
rust/tw_number/src/i256.rs
tools/install-rust-dependencies

Update rust toolchain from nightly-2024-02-09 to nightly-2024-06-13.
This should fix Docker build

[Rust]: Update rust toolchain to nightly-2024-06-13

---

README.md

Unfortunately, there is no a website for ECOIN Wallet yet. So I put a link to the Google Play market.
* Add ECOIN Wallet to the `Projects using Wallet Core` list.
* Remove Alice Dapp from the list

[ECOIN]: Add ECOIN Wallet to the Projects using WC list

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/theopennetwork/TestTheOpenNetworkSigner.kt
rust/chains/tw_ton/src/message/payload/jetton_transfer.rs
rust/chains/tw_ton/src/signing_request/builder.rs
rust/chains/tw_ton/src/signing_request/cell_creator.rs
rust/chains/tw_ton/src/signing_request/mod.rs
rust/tw_tests/tests/chains/ton/ton_sign.rs
rust/tw_tests/tests/chains/ton/ton_sign_wallet_v5r1.rs
src/proto/TheOpenNetwork.proto
swift/Tests/Blockchains/TheOpenNetworkTests.swift

Support TON mintless jettons, see https://docs.ton.org/develop/dapps/asset-processing/mintless-jettons
Run Rust, C++, Kotlin, Swift tests

[TON]: Support TON mintless jettons

---

Package.swift

Update Package.swift version to 4.1.12 (SPM)

Update Package.swift version to 4.1.12

---

.github/workflows/codegen-v2.yml
.github/workflows/docker.yml
.github/workflows/linux-ci-rust.yml
.github/workflows/linux-ci-sonarcloud.yml
.github/workflows/linux-ci.yml
.github/workflows/linux-sampleapp-ci.yml
.github/workflows/wasm-ci.yml

ubuntu-latest should have been upgraded to Ubuntu 24.04, but sometimes our pipelines are run on Ubuntu 22.04.
In this PR I set `ubuntu-24.04` explicitly.

[CI]: Upgrade to Ubuntu 24.04 explicitly

---

docs/registry.md

Updated the correct logo for KAIA
Reference:
https://kaia.io
https://docs.kaia.io
Test the if the image path renders expected image.
Updated the correct path for the image

Corrected the Kaia Logo

---

registry.json
tests/chains/Cosmos/THORChain/TWSwapTests.cpp

Update `chainId` and `rpc` after recent chainId update following a hardfork.
https://github.com/trustwallet/wallet-core/issues/4161
Note we haven't changed `chainId` in unit tests, because otherwise the transaction hashes, hence links to the successfully sent transaction won't be valid.

[THORChain]: Update `chainId` and `rpc`

---

registry.json
tests/chains/Algorand/SignerTests.cpp
tests/chains/Algorand/TWAnySignerTests.cpp
tests/chains/Algorand/TWCoinTypeTests.cpp
tests/chains/Boba/TWCoinTypeTests.cpp
tests/chains/Callisto/TWCoinTypeTests.cpp
tests/chains/Nano/TWCoinTypeTests.cpp
tests/chains/SmartBitcoinCash/TWCoinTypeTests.cpp

Update block explorers for Algorand, BOBAETH, Nano, Callisto, SmartBCH chains
Run C++ tests

[Misc]: Update block explorers

---

android/app/build.gradle
android/build.gradle
android/wallet-core/build.gradle
kotlin/gradle/libs.versions.toml
kotlin/wallet-core-kotlin/build.gradle.kts
samples/kmp/build.gradle.kts

[MISC] Android 16kb page fixes

---

kotlin/wallet-core-kotlin/build.gradle.kts

MISC: remove expect-actual classes warnings

---

tools/install-rust-dependencies

Added compilation support for Linux operating system CPU architecture aarch64.
1. Use an operating system with aarch64 CPU architecture
2. Compile Linux dynamic library
```
./tools/build-and-test
```

[Linux]: Add support for Linux aarch64.

---

jni/cpp/Random.cpp

Throw an exception if `/dev/urandom` is unavailable when WalletCore library is loaded in runtime.

security(JNI): Throw an exception if `/dev/urandom` is unavailable

---

.github/CODEOWNERS
tools/android-release
tools/ios-release
tools/ios-xcframework-release
tools/library

Use `gh release upload` command line tool to upload release assets instead of `curl`.
In addition, updated CODEOWNERS
Run all releases

chore(ci): Use `gh release upload` cmd to upload release assets

---

rust/wallet_core_rs/build.rs

Adds a fix for FFI binding cleanup
CI actions succeed

Adds fix for FFI binding cleanup

---

rust/tw_macros/src/tw_ffi.rs

This PR removes the panic if the file to be deleted was deleted by another thread.
CI builds continue to work

[FFI]: Don't panic if file was already deleted

---

include/TrustWalletCore/TWBarz.h
rust/tw_evm/src/modules/tx_builder.rs
rust/tw_evm/src/transaction/mod.rs
rust/tw_evm/src/transaction/user_operation_v0_7.rs
rust/tw_evm/tests/barz.rs
src/Ethereum/Barz.cpp
src/Ethereum/Barz.h
src/interface/TWBarz.cpp
src/proto/Ethereum.proto
tests/chains/Ethereum/BarzTests.cpp

This PR adds support for User Operation v0.7 to enable EIP-7702 compatible ERC 4337 transactions
Added a test to validate user operation hash
New feature (non-breaking change which adds functionality) 

[ETH]: Adds support for User Operation v0.7 to enable EIP-7702 compatible ERC 4337 transactions

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/ethereum/TestBarz.kt

Adds Kotlin tests for EIP-7702 Auth and UserOpV07
Added tests

[ETH]: Adds Kotlin tests for EIP-7702 Auth and UserOpV07

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/ethereum/TestBarz.kt

Adds UserOp Hash Encoding and Signing tests as well
Added tests

[ETH]: Adds UserOp Hash Encoding and Signing tests as well

---

Dockerfile
codegen-v2/src/codegen/cpp/code_gen.rs
swift/common-xcframework.yml
tools/ios-release

Uses Path API to fix docker CI build and modify headers to fix Cocoapods build
CI builds continue to work

Fixes Docker and Cocoapods builds

---

tests/common/PrivateKeyTests.cpp

Merge master into dev

---

tests/CMakeLists.txt
tools/dependencies-version
tools/download-dependencies
tools/install-dependencies

chore(dependencies): Update `gtest` to 1.16.0

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/ethereum/TestBarz.kt
rust/tw_evm/src/modules/tx_builder.rs
rust/tw_evm/tests/barz.rs
src/proto/Ethereum.proto
swift/Tests/BarzTests.swift
tests/chains/Ethereum/BarzTests.cpp

Allow to call `Biz.execute` when EOA is delegated already. In other words, no need to sign authorization list.
This pull request includes breaking changes to how we build Ethereum transaction payload and user operation.
* `Ethereum.SigningInput.transaction` payload needs to be manually wrapped into `Ethereum.Transaction.Execute` message to be able to call a Smart Contract Wallet function through EIP-4337 entry point and UserOperation.
For example,
```diff
- transaction = Ethereum.Transaction.newBuilder().apply {
-     erc20Transfer = Ethereum.Transaction.ERC20Transfer.newBuilder().apply {
-         to = "0x95dc01ebd10b6dccf1cc329af1a3f73806117c2e"
-         amount = ByteString.copyFrom("0xb5e620f48000".toHexByteArray())
-     }.build()
- }.build()
+ transaction = …
```

feat(biz): Allow to call `Biz.execute` when EOA is delegated already

---

android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/ethereum/TestBarz.kt
rust/tw_encoding/src/hex.rs
rust/tw_evm/Cargo.toml
rust/tw_evm/src/modules/tx_builder.rs
rust/tw_evm/src/signature.rs
rust/tw_evm/src/transaction/user_operation_v0_7.rs
rust/tw_evm/tests/barz.rs
rust/tw_number/Cargo.toml
rust/tw_number/src/lib.rs
rust/tw_number/src/serde.rs
rust/tw_number/src/u256.rs
src/proto/Ethereum.proto
swift/Tests/BarzTests.swift
tests/chains/Ethereum/BarzTests.cpp

Merge master to dev

---

rust/tw_evm/src/transaction/user_operation_v0_7.rs

Fix the incorrect user op v7 encode:
gasFees = maxPriorityFeePerGas (16 bytes) + maxFeePerGas (16 bytes) // expected (correct)
gasFees = maxFeePerGas (16 bytes) + maxPriorityFeePerGas (16 bytes) // actual (incorrect)

Fix incorrect user op v7 encode

---

rust/chains/tw_solana/src/instruction.rs
rust/chains/tw_solana/src/modules/insert_instruction.rs
rust/chains/tw_solana/src/modules/utils.rs
rust/tw_tests/tests/chains/solana/solana_transaction_ffi.rs
rust/wallet_core_rs/src/ffi/solana/transaction.rs

Support adding instruction in Solana transaction. Developers can use this feature to implement advanced capabilities, such as charging additional fees on transactions or providing fee reimbursements to users, etc.

Support adding instruction in Solana transaction

---

src/interface/TWStoredKey.cpp

Remove deprecated code and fix build issue in newer compiler
See https://github.com/llvm/llvm-project/commit/e30a148b098d462d0267c479cd9e4783363c2761

Remove deprecated code and fix build issue in newer compiler

---

rust/tw_evm/src/modules/tx_builder.rs
rust/tw_evm/src/transaction/authorization_list.rs
rust/tw_evm/src/transaction/user_operation_v0_7.rs
rust/tw_tests/tests/chains/ethereum/ethereum_compile.rs
src/proto/Ethereum.proto

Support extra eip7702Auth parameter in eip4337 user operation
See https://eips.ethereum.org/EIPS/eip-4337#support-for-eip-7702-authorizations

Support extra eip7702Auth parameter in eip4337 user operation

---

rust/tw_crypto/src/crypto_scrypt/params.rs

This pull request updates the parameter validation logic in the `Params` struct for Scrypt within `rust/tw_crypto/src/crypto_scrypt/params.rs`. The main goal is to support legacy wallets by relaxing a previous restriction and introducing a new upper bound for the `log_n` parameter.
Parameter validation logic changes:
* Updated the documentation to explain that legacy wallets may have `log_n > r * 16`, and now the code restricts `log_n` to be less than `r * 19` instead of the original check.
* Added a new validation: if `log_n` is greater than or equal to `r * 19`, the function returns an error, enforcing the new upper bound for Scrypt parameters.

security(scrypt): Add Scrypt check
